### ISSUE TITLE
Bump version and publish to npm

### ISSUE THREAD

**Issue by pasviegas** [timarney/react-app-rewired#10]
Now that we have rewires, would be nice to publish so everyone can use them :D

**Comment by timarney** [comment]
I haven't had a chance to jump in / test these out yet. Just wondering about the dependencies i.e. sass-loader node-sass or whatever else is needed for each of the rewires.  Thoughts on that or am I missing something? 

I don't want to complicate things but I was thinking about setting things up either the same or similar to CRA - https://github.com/facebookincubator/create-react-app/tree/master/packages I believe this is done using (https://github.com/lerna/lerna) .  I haven't tried it yet but it's something I want to look into.

**Comment by pasviegas** [comment]
Hmm, yes, using lernajs we can create isolated rewire packages, each with its own dependencies. Should be simple to set up. I will try it out!

**Comment by timarney** [comment]
Cool - I think that will bring a lot of flexibility in the long run.

**Comment by timarney** [comment]
Published.

**Comment by pasviegas** [comment]
Nice, just saw the packages! 🎉

**Comment by timarney** [comment]
Thanks for getting that setup.  Works great.

We'll need to add README files to the packages .  I did a quick one for the Sass package.
