### ISSUE TITLE
Why create-react-app to use SASS has been deprecated?

### ISSUE THREAD

**Issue by zhaojinxiang** [timarney/react-app-rewired#100]
react-app-rewire-sass  isn't the same thing as [Adding a CSS Preprocessor (Sass, Less etc.)](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc). The method in  document of facebookincubator/create-react-app didn't allow us using `import './sss.scss'` .

**Comment by timarney** [comment]
Please see https://github.com/timarney/react-app-rewired/issues/66#issuecomment-330649196

That issue has an updated way on how to rewire with SASS + additional notes.

If @hwaterke has time sounds like he will publish as a package and we will link to it from this repo.  In the meantime follow his notes for modifying your config file.

**Comment by JonET** [comment]
It would still be nice if you could fix and un-deprecate the original module. It would be easier for people to find. Having webpack handle SASS is _much_ nicer than the solution Facebook proposes.

**Comment by zhaojinxiang** [comment]
@JonET https://gist.github.com/zhaojinxiang/63eeadb124852890ba4f548fd0f8bd7b
