### ISSUE TITLE
Loading path of env files is not compatible with --scripts-version option

### ISSUE THREAD

**Issue by dawnmist** [timarney/react-app-rewired#103]
Issue with commit: https://github.com/timarney/react-app-rewired/commit/d7e7397206937eb5936b0d76b22b751bbff5df4f#diff-c85f4f73618215cb2646fbfc89cf044d

The files scripts/start.js and scripts/build.js are loading the env files by referring to "react-scripts" directly. This means that they are incompatible for anyone using a custom react-scripts package (e.g. "react-scripts-ts" for typescript).

The path to the env files needs to be relative to paths.scriptVersion parameter from scripts/utils/paths.js.

**Comment by Guria** [comment]
Yes, you are right. It could be fixed by using 
`require(paths.scriptVersion + '/config/env');`

Of course you should move it under requiring `paths`.

Would you like to make a PR?
