### ISSUE TITLE
Does .eslintignore not work?

### ISSUE THREAD

**Issue by fadehelix** [timarney/react-app-rewired#106]
I want to ignore `src/registerServiceWorker.js` file and the simplest way to achieve this is to add the path to the `.eslintignore` file. 
But the file is always linted.

If I add `/* eslint-disable */` at the top of the ignored file then it works as expected.

**Comment by timarney** [comment]
Not familiar with how that works myself but likely has to do with https://github.com/facebookincubator/create-react-app/issues/2339#issuecomment-303397558
