### ISSUE TITLE
Decorators rewire

### ISSUE THREAD

**Issue by gioragutt** [timarney/react-app-rewired#111]
Is there a rewire for ESNext decorators?

**Comment by timarney** [comment]
The MobX rewire is a good one to looks at https://github.com/timarney/react-app-rewired/blob/master/packages/react-app-rewire-mobx/index.js

**Comment by gioragutt** [comment]
@timarney wow, looking at the file, rewiring looks easy. I was wondering what the mobx rewire does, but didn't look at it.

This looks so easy. Thank you!

**Comment by timarney** [comment]
Nice to hear - 

Note for decorators plugin order matters (if your adding additional plugins) see
https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy#note-order-of-plugins-matters
