### ISSUE TITLE
Test runner not working

### ISSUE THREAD

**Issue by maxsalven** [timarney/react-app-rewired#117]
When I run `react-scripts test --env=jsdom` all my tests pass (they are testing just plain functions, not react components).

When I run `react-app-rewired test --env=jsdom`, all my tests fail:

```
Test suite failed to run

    TypeError: Path must be a string. Received undefined
      
      at assertPath (path.js:28:11)
      at Object.relative (path.js:1268:5)
```

Version 1.3.3

**Comment by timarney** [comment]
Can you check using 1.3.2?  Might be something with the last commit.

**Comment by maxsalven** [comment]
Same issue on 1.3.2 (and 1.2.0, just as another test)

**Comment by timarney** [comment]
Okay please provide a test sample so we're on the same page and can reproduce, actually If you could spin up demo repo would speed things up (limited time on my end).  Also any other notable details.

**Comment by chrbala** [comment]
I build [a test repo](https://github.com/chrbala/react-app-rewired-jest-fail) for this issue. At least for me, it's only happening when I run it as part of a monorepo.

You can recreate this issue with the following commands:
```bash
yarn # npm
cd submodule
yarn # npm
yarn test # npm test
```
I get an error with no stack trace or message when I try to run the test.

**Comment by chrbala** [comment]
I have a rough fix for my problem. If you apply [this change](https://github.com/chrbala/react-app-rewired/commit/101e51adbaa5e2a0a5e9d39ac7daf6027ba994d1) to react-app-rewired and add: `"main": "./bin/react-scripts.js",` to [this file](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/package.json), the test runner works in a monorepo setup.

The main property addition is necessary for require.resolve to work. I'm not sure how to get the package path properly if there isn't a main file.
