### ISSUE TITLE
Cannot read property 'find' of undefined?

### ISSUE THREAD

**Issue by gyt95** [timarney/react-app-rewired#118]
I want to use packages both react-app-rewire-sass and react-app-rewire-mobx. But the error is shown as follows :    
   
![image](https://user-images.githubusercontent.com/23090676/32011201-a0142362-b9e6-11e7-8a40-0bacd5f68fc5.png)

   
What is the reason for the error? This is my package.json :  
  
![image](https://user-images.githubusercontent.com/23090676/32010916-b6d9fb86-b9e5-11e7-9000-2362ce268592.png)
   
The configuration of config.js is as follows :   
    
![image](https://user-images.githubusercontent.com/23090676/32011027-25cc5a34-b9e6-11e7-8f08-20089900a464.png)
    
It's ok to use react-app-rewire-mobx alone.

**Comment by timarney** [comment]
The Sass rewire is deprecated / hasn't been updated to work with newer versions react-scripts.  Trying the code outlined here for Sass https://github.com/timarney/react-app-rewired/issues/66#issuecomment-330649196

**Comment by gyt95** [comment]
@timarney The problem is solved. Thank you!
