### ISSUE TITLE
.env.local can not override .env

### ISSUE THREAD

**Issue by henrydf** [timarney/react-app-rewired#119]
Now I can not override values in .env by using .env.local file.

**Comment by Guria** [comment]
Can you check if it working in CRA?

**Comment by henrydf** [comment]
Yes, it works after remove react-app-rewired.

**Comment by Guria** [comment]
Thanks, then would be great to have clonable demo. Could make such?

**Comment by henrydf** [comment]
There is somthing weired in yarn.lock .......  Everything is OK after re-generating a new lock file....
