### ISSUE TITLE
Cannot read property 'exclude' of undefined

### ISSUE THREAD

**Issue by varHarrie** [timarney/react-app-rewired#123]
I use `react-app-rewire-less` with following error:
```
  fileLoader.exclude.push(lessExtension);
            ^
TypeError: Cannot read property 'exclude' of undefined
```

I try to downgrade the version of `react-scripts` from `1.0.15` to `1.0.14`,  And it works well.

"react-app-rewired": "^1.3.4"
"react-app-rewire-less": "^2.0.7"
"react-app-rewire-typescript": "^1.0.4"

**Comment by timarney** [comment]
There was a PR not for this issue but,  if can you update to the latest and see if that fixes the problem react-app-rewire-less@2.0.8 that would be great.

**Comment by andriijas** [comment]
Might fix it but there is some other issue with new react-scripts version and react-app-rewire-less, the override config is not passed correctly to the less loader anymore

```
function createRewireLess(lessLoaderOptions = {}) {
  return function(config, env) {
  }
}
const rewireLess = createRewireLess();

rewireLess.withLoaderOptions = createRewireLess;

module.exports = rewireLess;
```

can be replaced with (or?)

```
function rewireLess(config, env, lessLoaderOptions = {}) {
}
module.exports = rewireLess;
```

**Comment by timarney** [comment]
@varHarrie FYI - version is now @ 2.1.0 is this still an issue or can we close it?

**Comment by varHarrie** [comment]
There was no error any more after upgraded to latest version, thanks.
