### ISSUE TITLE
Utility methods and loader vs. rule

### ISSUE THREAD

**Issue by lnhrdt** [timarney/react-app-rewired#127]
I recently wrote a couple rewires. Abstractly, it was really hard for me to decide if a given part of the configuration was a "rule" or a "loader". Based on Webpack's [module.loaders is now module.rules](https://webpack.js.org/guides/migrating/#module-loaders-is-now-module-rules), my understanding is that the dependency (e.g. css-loader) is a loader, but any part of the configuration object (e.g. `{test: /\.css$/, options: {}}`) is a rule. Maybe it would more conventional and easier for others to reason through if we considered renaming `getLoader` to `getRule`, `getRuleMatching`, or something else. Or am I missing something?

**Comment by timarney** [comment]
@osdevisnot @icopp any thoughts?

**Comment by lnhrdt** [comment]
If anyone wants to see the mess I made that prompted me to think about this, here's the spot:

https://github.com/codebandits/react-app-rewire-css-modules/blob/36f4a6e7e97bc774407af87dddad29236f98b06a/index.js

**Comment by icopp** [comment]
A forward-looking change to `getRule`would probably be a good in case Webpack starts doing other stuff with their rules.

An `insertBeforeRule` utility function would probably be useful too, even if it'd mainly just get used to inject things before `react-script`'s catch-all `file-loader` rule.

**Comment by andriijas** [comment]
What do you guys think about the way you can traverse webpack config in neutrino?  

https://neutrino.js.org/webpack-chain.html

```
  config
    // Interact with entry points
    .entry('index')
      .add('src/index.js')
      .end()
```

**Comment by timarney** [comment]
https://github.com/andywer/webpack-blocks is also nice.  Would be much nicer to go down that path.  Preact CLI also has a nice setup - https://github.com/developit/preact-cli/wiki/Config-Recipes#customising-babel-options-using-loader-helpers

**Comment by andriijas** [comment]
agreed. i like preact-cli.

**Comment by timarney** [comment]
@lnhrdt @icopp leaning towards adding getRule and insertBeforeRule.  I think we'll keep getLoader as in some cases you'll want to grab the babel-loader etc...

**Comment by timarney** [comment]
Going to close this - if someone wants to submit a PR with some additional util rules that would be great.

**Comment by andriijas** [comment]
@timarney @lnhrdt @icopp https://github.com/d4rky-pl/razzle-config-utils  works with react-app-rewired.

**Comment by timarney** [comment]
@andriijas - Oh nice forgot razzle has roughly the same config pattern.  If someone has a good test case to try this against I think it's a great idea to be able to use that repo.

**Comment by andriijas** [comment]
sure, i use it with one razzle project and in one react-app-rewired, the config pattern is very similar so im able to share configs pretty seamless between the projects.
