### ISSUE TITLE
MobX rewire

### ISSUE THREAD

**Issue by timarney** [timarney/react-app-rewired#13]
Plugin tries to resolve from src dir not react-app-rewire-mobx dir.

```
Error in ./src/index.js
Module build failed: ReferenceError: Unknown plugin "transform-decorators-legacy" specified in "base" at 0, attempted to resolve relative to "/mydir/src"
    at Array.map (native)
 @ multi main
```

@pasviegas any chance you could shed some light on this was thinking this would work like your relay rewire

**Comment by pasviegas** [comment]
Hey @timarney, have you tried setting transform-decorators-legacy as a dependency and not a devDependency?

**Comment by timarney** [comment]
hmmm @pasviegas just tried that based on your suggestion same error as before.

**Comment by pasviegas** [comment]
Do you have a example project? I can make a quick test locally

**Comment by timarney** [comment]
Just pushed to here https://github.com/timarney/mobx-rewire-testing I need to update the rewire dependency as it has a typo - I'll do that now.

**Comment by timarney** [comment]
Okay - I just published another alpha to NPM - react-app-rewire-mobx@0.0.1-alpha.4db00818 

I do know for that plugin the load order matters but I don't think that's the issue as it's not finding it.

https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy#note-order-of-plugins-matters

**Comment by timarney** [comment]
@pasviegas Just update the version to pull for the example.  

I just tested to see what happens if I install babel-plugin-transform-decorators-legacy into the project itself ... and that works so it's just not resolving when it's in the plugin as a dep.

**Comment by pasviegas** [comment]
Yeah, that is what I was gonna say. I tested the implementation installing the babel plugin directly in the project and it worked.

I don't know what is the difference here, because when I use the relay plugin it gets the right dependencies and works

**Comment by timarney** [comment]
Ya hence the ping - odd one would work and not the other.

**Comment by pasviegas** [comment]
Hmm, I use yarn, I think it flattens the dependencies, that may be the case why it works

**Comment by timarney** [comment]
Oh interesting - that does seems to be the case.  I just tested with Yarn and it works.  

Not sure but thinking I might spin up some standalone repos to use for testing the rewire packages - I've been thinking about it and I haven't thought up a good way to test each of them keeping them in this repo yet as per https://github.com/timarney/react-app-rewired/issues/9.

**Comment by pasviegas** [comment]
My initial idea was just to test the webpack config if the properties are set correctly. As long as the properties are there, the build should work properly.

**Comment by timarney** [comment]
Testing just the config should be fine - I'll likely do a couple of standalone as well for a sanity check as things come up :) thanks for the help.  Yarn!

**Comment by pasviegas** [comment]
We should actually add something to the Readme about this hehe :)

**Comment by timarney** [comment]
Ya good point.  Can update the Github Readme at least https://github.com/timarney/react-app-rewired/issues/15
