### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by nsreenath** [timarney/react-app-rewired#132]
`node_modules\react-app-rewire-less\index.js:14
    );
    ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\workspace\reactjs\ant-design\create-react-app-antd                                                                                                                                  \create-react-app-antd\config-overrides.js:2:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                                                                                                                  node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! create-react-app-antd@0.1.0 start: `react-app-rewired start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the create-react-app-antd@0.1.0 start script 'react-app-rewir                                                                                                                                  ed start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the create-react-app-antd                                                                                                                                   package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-app-rewired start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs create-react-app-antd
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls create-react-app-antd
npm ERR! There is likely additional logging output above.`

**It worked when the trailing comma is removed. Not sure if that is the correct solution.**

**Comment by likun7981** [comment]
Show me your `config-overrides.js`,  `react-app-rewired` version and `react-app-rewire-less` version

**Comment by Pyroboomka** [comment]
Same error basically.

From package-lock:
```
react-app-rewire-less: 2.0.7
react-app-rewired: 1.3.3
```

From package:
```
rewire-less: ^2.0.7
rewired: ^1.2.5
```

config-overrides.js:
```
const theme = require('./src/theme')`

const { injectBabelPlugin } = require('react-app-rewired');
const rewireLess = require('react-app-rewire-less');

module.exports = function override(config, env) {
  config = injectBabelPlugin(['import', {
    libraryName: 'antd',
    style: true
  }], config);

  config = rewireLess(config, env, { modifyVars: theme });

  return config;
};
```
theme.js if it matters:
```
module.exports = {
    "@primary-color": "#58C4D9"
}
```

Removing ^ from rewire-less in package.json fixes it anyway.

**Comment by likun7981** [comment]
Please update to 
```
react-app-rewire-less: 2.0.8
react-app-rewired: 1.3.5
```

The usage of  `react-app-rewire-less`  has changed, because we add a new api [compose](https://github.com/timarney/react-app-rewired#2-composeafter-v134), detail see [react-app-rewire-less](https://github.com/timarney/react-app-rewired/tree/master/packages/react-app-rewire-less#add-it-to-your-project) .

Now you can use `react-app-rewire-less`, like:
```javascript
// with loaderOptions
compose(
  rewireLess.withLoaderOptions(someOptions),
  ...// other rewires
)
// without loaderOptions
compose(
  rewireLess,
  ...// other rewires
)
```

**Comment by flasco** [comment]
the bug happened in this code :

const fileLoader = getLoader(
      config.module.rules,
      rule =>
        rule.loader &&
        typeof rule.loader === 'string' &&
        rule.loader.indexOf(`${path.sep}file-loader${path.sep}`) !== -1, // the , is unnecessary
    );

solution: remove  `,`;  just like this:

const fileLoader = getLoader(
      config.module.rules,
      rule =>
        rule.loader &&
        typeof rule.loader === 'string' &&
        rule.loader.indexOf(`${path.sep}file-loader${path.sep}`) !== -1   //this  ,  
    );

**Comment by nsreenath** [comment]
I was also telling the same. It worked when the trailing comma is removed. Not sure if that is the correct solution.

**Comment by timarney** [comment]
Please try - react-app-rewire-less: 2.0.9

**Comment by nsreenath** [comment]
react-app-rewire-less: 2.0.9 shows no syntax errors due to [this change](https://github.com/timarney/react-app-rewired/commit/e4bca47a2065e1251079f293d8c9bd74b507a930). Not sure if there are runtime errors. Since this issue is titled "syntax error" then we can close this issue, I guess.
