### ISSUE TITLE
react-scripts-dangerous

### ISSUE THREAD

**Issue by Ayc0** [timarney/react-app-rewired#149]
When I try to start a command with react-scripts-dangerous, I've got `Cannot find module 'react-scripts/package.json'`

**Comment by Ayc0** [comment]
The line responsible for this is [this one](https://github.com/timarney/react-app-rewired/blob/master/packages/react-app-rewired/scripts/utils/paths.js#L12)

**Comment by dawnmist** [comment]
Are you using the `--scripts-version` command line option to specify that you are using a different set of scripts? i.e.
```
react-app-rewired start --scripts-version react-scripts-dangerous
```

If you are using a replacement for react-scripts, you need to specify what that replacement is when you run the react-app-rewired command. There is an example for this in the Readme file now, in the "Additional Issues and Options - 2) Custom scripts versions" section.

**Comment by Ayc0** [comment]
oh okay, I didn't know this was available 👍
