### ISSUE TITLE
Lerna /NPM doesn't update README

### ISSUE THREAD

**Issue by timarney** [timarney/react-app-rewired#15]
Noting this as the Readme for the packages is not getting published.

I tried the setting up the lerna-npm-readme-hack but I'm running into an issue publishing saying I need to update the lerna version ... re-run lerna and than the warning about the the lerna version comes back.

https://github.com/lerna/lerna/issues/64
https://github.com/npm/registry/issues/42

**Comment by timarney** [comment]
Will keep an eye on this I added the lerna-npm-readme-hack and the Readme files appear to be working now https://www.npmjs.com/package/react-app-rewire-preact.

**Comment by hzoo** [comment]
Fixed!! https://github.com/lerna/lerna/issues/64 😍
