### ISSUE TITLE
Cannot find module 'D:\xx\xx\xx/config-overrides'

### ISSUE THREAD

**Issue by IEfucker** [timarney/react-app-rewired#156]
env
Node 7.5.0
os windows7 64
create-react-app 1.4.3
react-app-rewired 1.3.6

Even when I get into node_modules/react-app-rewired/index and fix path.configOverrides with '\\', still gets the same error.

**Comment by Guria** [comment]
Please try remove node_modules and install it again.
I tried 1.3.6 on Windows 10 x64 and it worked fine.
If it still not works, please try to provide more details:
which command was run, detailed stack trace, etc

**Comment by Vadorequest** [comment]
Same happened to me on MacOS X High Sierra with

    "react-app-rewire-yaml": "1.0.0",
    "react-app-rewired": "1.5.0",

Logs:
```
npm test

> student-loan-simulator@1.1.3 test /Users/vadorequest/dev/student-loan-simulator
> react-app-rewired test --env=jsdom

module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/vadorequest/dev/student-loan-simulator/config-overrides'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/vadorequest/dev/student-loan-simulator/node_modules/react-app-rewired/config-overrides.js:5:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! Test failed.  See above for more details.

```

Deleting/Reinstalling node modules didn't fix it.

**Comment by krav4enkodm** [comment]
@Vadorequest 

It helps form me

`https://github.com/timarney/react-app-rewired/blob/master/packages/react-app-rewired/config-overrides.js`

**Comment by robbiedh** [comment]
add this  `"config-overrides-path": "node_modules/react-app-rewire-micro-frontends", `
on package.json

**Comment by Zotri** [comment]
@robbiedh  thx for your approach. However I have it improved:
```
npm i react-app-rewired
```
then: 
on the top of your package.json add:

```
    "name": "my-app",
    "version": "0.1.0",
    "private": true,
    "config-overrides-path": "node_modules/react-app-rewired/config-overrides.js",
{...}
```

**Comment by gibron** [comment]
Adding the `config-overrides-path` worked for me. 

Does anyone know _why_ this solves it? 

And perhaps what conditions lead to this?

**Comment by dawnmist** [comment]
@gibron Usually it's because they're putting the config-overrides.js file in a different folder to the project's root folder. By default, react-app-rewired looks for config-overrides in your project's root folder (not in src, not in node_modules, etc).

**Comment by mabbas112** [comment]
`"config-overrides-path": "node_modules/react-app-rewired/config-overrides.js"`

This worked for me, Thanks u all above

**Comment by camillalo** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by tuseefahmed786** [comment]
> @gibron Usually it's because they're putting the config-overrides.js file in a different folder to the project's root folder. By default, react-app-rewired looks for config-overrides in your project's root folder (not in src, not in node_modules, etc).

@gibron hi i have little bit same this error when i run npm run start
![Capture2](https://github.com/timarney/react-app-rewired/assets/86749819/3f4d5b5b-8b0d-4962-9686-bf6a7d986597)
![Capture](https://github.com/timarney/react-app-rewired/assets/86749819/c95c73f6-3032-4aac-afe5-5d47869c0e93)
 please can you solve i attached screen shoot file and
