### ISSUE TITLE
Help, How to add webpack alias ?

### ISSUE THREAD

**Issue by 001123** [timarney/react-app-rewired#167]
I want to add custom alias , how i do it ?

**Comment by dawnmist** [comment]
If I've understood the [Webpack Config](https://webpack.js.org/configuration/) and [Webpack Resolve](https://webpack.js.org/configuration/resolve/) documentation correctly, you'd need to add a resolve section to the config in your config-overrides.js file:
```javascript
module.exports = function override(config, env) {
  config.resolve = {
    alias: {
      Utilities: path.resolve(__dirname, 'src/utilities/'),
      Templates: path.resolve(__dirname, 'src/templates/')
    }
  };
  return config; 
}
```

**Comment by Duobe** [comment]
how to add modules like this:
``` js
{
  test: /\.module\.less$/,
  loader: ExtractTextPlugin.extract(
    'css?sourceMap&modules&localIdentName=[local]___[hash:base64:5]!!' +
    'postcss!' +
    `less-loader?{"sourceMap":true,"modifyVars":${JSON.stringify(theme)}}`
  ),
}
```

I just want to use `less.modifyVars` to change my own theme color.

**Comment by timarney** [comment]
@Duobe have you tried using the react-app-rewire-less?  It does the Less setup for you.

I don't use less but I see other using modifyVars in this issue https://github.com/timarney/react-app-rewired/issues/132

**Comment by Duobe** [comment]
@timarney Thanks ! #132 is worked.
