### ISSUE TITLE
new config devServer override key not working

### ISSUE THREAD

**Issue by bdo** [timarney/react-app-rewired#171]
When overriding the config with an object using the keys (`webpack`, `jest`, `devServer`), the `devServer` key is not working. 

However using `devserver` works as intented.

I think `devServer` is probably better (as per README documentation), so it'd be good to rename the key in the code, right?

**Comment by likun7981** [comment]
see #157 #161

**Comment by bdo** [comment]
@likun7981 No sure why you are closing the issue this bug is still there. It was introduced by  in version 1.3.6 and broke our tests because the certificate did not work anymore.

To reproduce it, use the [extended configuration options example](https://github.com/timarney/react-app-rewired#extended-configuration-options) which uses the `devServer` key. The certificate is not added when serving the site.

In terms of the config key to use, `devServer` seems slightly better to use since the same word is used in the webpack config. See [webpack docs](https://webpack.github.io/docs/webpack-dev-server.html).

**Comment by likun7981** [comment]
This is a break change, so consider now is not to change the original usage. it will be changed in later versions, so you do not have to worry about. `the doc` is wrong , it is our fault, we will update it

**Comment by Guria** [comment]
@bdo 
the plan is:
* align readme with implementation in 1.x
* cleanup/rename in 2.x

PR for readme is welcomed

**Comment by Guria** [comment]
Hmm, sorry. It was originally called `devServer` in https://github.com/timarney/react-app-rewired/pull/157
So, let's fix it one more time. Sorry for the mess.

Tests in 2.x is high priority.

**Comment by bdo** [comment]
@guria Thanks for double checking !

PR is already available: #172 ;)

**Comment by bdo** [comment]
@likun7981 Thanks for reopening the issue.

Any chance of reopening and reviewing PR #172 please ?

If I can help on the project on something else please shout :wink:

**Comment by likun7981** [comment]
I think do not change, most people are sure to use `devserver`,even if it's not perfect, 
when the 2.0 update it. @Guria what do you think?

**Comment by likun7981** [comment]
Or we can add a warning for those who use `devserver` and then add the `devServer option` like #157

**Comment by dawnmist** [comment]
Anyone using the option prior to this mess would already have been using "devServer", so changing the case to "devserver" now will break their configuration. Their current config will need updating for the change (and the need to update how the devServer option was used was the reason why the original pull request making changes to the devServer option was reverted to be held back until version 2.0).

**Comment by likun7981** [comment]
I do not know why  keep this wrong configuration option `devserver`.

**Comment by Guria** [comment]
let's make both and add warning within `devserver`

**Comment by bdo** [comment]
@Guria I can update PR #172 to add a warning for those using `devserver`, accepting for now both `devServer` and `devserver`.

But could you please reopen it first?

**Comment by bdo** [comment]
@Guria @likun7981 PR #172 is now also allowing `devserver` but issues a warning when used.
