### ISSUE TITLE
How to pass argument to config-override?

### ISSUE THREAD

**Issue by huygn** [timarney/react-app-rewired#176]
Hi, I want to pass argument to rewire for `webpack-bundle-analyzer`, is it possible?

```
react-app-rewired build --bundle-report
```

```js
if (env === "production") { // && arg === "--bundle-report"?
   config.plugins.push(new BundleAnalyzerPlugin());
}
```

**Comment by dawnmist** [comment]
In the override:
```javascript
const bundleReportIndex = process.argv.indexOf('--bundle-report');
if (env === 'production' && bundleReportIndex) {
  config.plugins.push(new BundleAnalyzerPlugin());
}
```
Then when you actually do the command line: `npm run build --bundle-report` or `yarn build --bundle-report`.

If you want a script target in package.json:
```json
"scripts": {
  "build": "react-app-rewired build",
  "build:bundle": "react-app-rewired build --bundle-report"
}
```
and then run it with `npm run build:bundle` or `yarn build:bundle`.

**Comment by huygn** [comment]
Thanks! 👍

**Comment by Guria** [comment]
I would use just environment variables set directly in cli or with help of .env* files, if I were you. Then you just check it with `process.env.MY_VAR`
