### ISSUE TITLE
How long will it take to support 'SCSS'?

### ISSUE THREAD

**Issue by walkinMrwang** [timarney/react-app-rewired#179]
Many precompilers are supported, such as' less ', 'sass', etc..,How long will it take to support 'SCSS'?'react-app-rewire-scss'?

**Comment by dashed** [comment]
@walkinMrwang you can make it yourself. it should be pretty easy to write one to suit your needs.

**Comment by walkinMrwang** [comment]
@dashed I'm not familiar with webpack. Can you help me?

**Comment by walkinMrwang** [comment]
Oh, I have successfully configured SCSS according to the less configuration, and I need to introduce 'sass-loader'. thank you very much~
const path = require("path");
const { getLoader } = require("react-app-rewired");

function createRewireScss(lessLoaderOptions = {}) {
    return function(config, env) {
        const lessExtension = /\.scss$/;

        const fileLoader = getLoader(
            config.module.rules,
            rule =>
                rule.loader &&
                typeof rule.loader === 'string' &&
                rule.loader.indexOf(`${path.sep}file-loader${path.sep}`) !== -1
        );
        fileLoader.exclude.push(lessExtension);

        const cssRules = getLoader(
            config.module.rules,
            rule => String(rule.test) === String(/\.css$/)
        );

        let lessRules;
        if (env === "production") {
            lessRules = {
                test: lessExtension,
                loader: [
                    // TODO: originally this part is wrapper in extract-text-webpack-plugin
                    //       which we cannot do, so some things like relative publicPath
                    //       will not work.
                    //       https://github.com/timarney/react-app-rewired/issues/33
                    ...cssRules.loader,
                    { loader: "sass-loader", options: lessLoaderOptions }
                ]
            };
        } else {
            lessRules = {
                test: lessExtension,
                use: [
                    ...cssRules.use,
                    { loader: "sass-loader", options: lessLoaderOptions }
                ]
            };
        }

        const oneOfRule = config.module.rules.find((rule) => rule.oneOf !== undefined);
        if (oneOfRule) {
            oneOfRule.oneOf.unshift(lessRules);
        }
        else {
            // Fallback to previous behaviour of adding to the end of the rules list.
            config.module.rules.push(lessRules);
        }

        return config;
    };
}

const rewireScss = createRewireScss();

rewireScss.withLoaderOptions = createRewireScss;
