### ISSUE TITLE
MobX rewire config not picked up by Jest

### ISSUE THREAD

**Issue by mweststrate** [timarney/react-app-rewired#18]
Thanks for the create project!

I noticed that the MobX rewiring worked great for running the app. But running the tests breaks as soon as decorators are used. It seems the babelrc config used by webpack is not picked up by jest. Is this something that could be addressed?

Thanks!

**Comment by timarney** [comment]
Thanks for the interest @mweststrate 

I believe that can be done.  I started looking into it I just need to devote some time to it.

Roughly from what I see for the jest setup in CRA it uses this file
```
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/utils/createJestConfig.js

and 

https://github.com/facebookincubator/create-react-app/tree/master/packages/react-scripts/config/jest

This one in particular 

https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/config/jest/babelTransform.js
```

Essentially we should be able to mod the test script (as is done with the others) before it runs
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/scripts/test.js
```
// 
const createJestConfig = require('../utils/createJestConfig');
const path = require('path');
const paths = require('../config/paths');
argv.push('--config', JSON.stringify(createJestConfig(
  relativePath => path.resolve(__dirname, '..', relativePath),
  path.resolve(paths.appSrc, '..'),
  false
)));
// @remove-on-eject-end
jest.run(argv);
```

**Comment by timarney** [comment]
@mweststrate off chance do you have a public repo with your test rewired app and a Jest test with decorators?  I started a new branch https://github.com/timarney/react-app-rewired/tree/jest -- just need to test it out.

**Comment by timarney** [comment]
@mweststrate I think I have a version working now:

0.6.1 on NPM

![screen shot 2017-02-14 at 6 32 54 am](https://cloud.githubusercontent.com/assets/62242/22927618/5bb4c1f0-f280-11e6-89a0-8ccddfbc0c85.png)

Note: the Rewired using in the screenshot you should see that running the rewired test scripts 

Also the test script needs to point to the rewired version:

```
"scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test --env=jsdom"
  }
```

Sample Repo:

https://github.com/timarney/mobx-rewire-test

**Comment by timarney** [comment]
I think we're good on this.  I'll be tweaking further but that gives us Jest support.  Hopefully I can just pull in most of the scripts needed from the scripts package (copied them in for now to see if I could get a version working).

This also supports usage with a forked version of React Scripts https://github.com/timarney/react-app-rewired/pull/12#issuecomment-279730742

**Comment by mweststrate** [comment]
Awesome! Sorry I hadn't time to look in this yet, but great stuff!

Op di 14 feb. 2017 om 16:11 schreef Tim Arney <notifications@github.com>:

**Comment by timarney** [comment]
No worries and thanks for MobX.
