### ISSUE TITLE
[ask] Hi, how to use babel-plugin-transform-remove-console in config for production only

### ISSUE THREAD

**Issue by azulkipli** [timarney/react-app-rewired#180]
Hi, thanks for creating this great project.

how to use [babel-plugin-transform-remove-console](https://babeljs.io/docs/plugins/transform-remove-console/) in config-override.js for production only ?

**Comment by timarney** [comment]
With the current version you can use the env param

module.exports = function override(config, env) {
 
  if (env === "production") {
    console.log("⚡ Production");
    config = ...
  }
  
  return config;
}

**Comment by azulkipli** [comment]
Hi again, I manage to remove all console method with this code

```
const { injectBabelPlugin } = require("react-app-rewired");

module.exports = function override(config, env) {
  // remove console.log
  if (env === "production") {
    console.log("⚡ Console.log removed on Production");
    config = injectBabelPlugin("transform-remove-console", config);
  }

  return config;
};
```

But I want to exclude certain console method (console.error & console.warn) as sample config here
https://babeljs.io/docs/plugins/transform-remove-console/

How to add plugins option?
