### ISSUE TITLE
Invalid configuration object

### ISSUE THREAD

**Issue by sschenk** [timarney/react-app-rewired#181]
I'm trying to add the [following plugin](https://www.npmjs.com/package/babel-plugin-transform-imports)  but I get the error in subject. 
What am I missing?

```
config.resolve = {
    "plugins": [
        ["transform-imports", {
            "react-bootstrap": {
                "transform": "react-bootstrap/lib/Navbar",
                "preventFullImport": true
            }
        }]
    ]
  }
```

**Comment by unconfident** [comment]
I believe you're adding `plugins` property to webpack's configuration object when you should add it to the options of the appropriate rule/loader. 

Use `injectBabelPlugin` method from `react-app-rewired` package, it's explained in the readme.

**Comment by davidsonsns** [comment]
my code stayed like this
```js
config = injectBabelPlugin(
    [
      'transform-imports',
      {
        'redux-form': {
          transform: 'redux-form/es/${member}',
          preventFullImport: true
        }
      }
    ],
    config
  )
```
