### ISSUE TITLE
Supporting WebStorm's Test Runner UI

### ISSUE THREAD

**Issue by unconfident** [timarney/react-app-rewired#182]
I'm using WebStorm and I'd like to take advantage of the UI it provides for the testing frameworks. Normally it needs to be pointed at "Jest package" directory, containing runnable file which it expects to find at `<path-to-package>/bin/jest`

When it detects CRA project however it automatically selects `react-scripts` as Jest package and runs a different script - `<path-to-package>\scripts\test.js` with slightly different params

![image](https://user-images.githubusercontent.com/30427068/34475260-fbd70d86-ef92-11e7-8fa3-1e8613f255b6.png)

Here's what executed command looks like with `react-scripts`:

```cmd
"C:\Program Files\nodejs\node.exe" \
  C:\path\to\project\node_modules\react-scripts\scripts\test.js \
  --env=jsdom --colors \
  --setupTestFrameworkScriptFile "C:\path\\to\\WebStorm\plugins\JavaScriptLanguage\helpers\jest-intellij\lib\jest-intellij-jasmine.js"
```

Line breaks added for readability. 

And here with the `react-app-rewired` selected as Jest package:

```cmd
"C:\Program Files\nodejs\node.exe" \
  C:\path\to\project\node_modules\react-app-rewired\bin\jest \
  --config "{ \
    \"moduleNameMapper\":{ \
      \"^/(.*)\":\"<rootDir>/src/$1\" \
    }, \
    \"rootDir\":\"C:\\path\\to\\project\", \
    \"transformIgnorePatterns\":[ \
      \"/node_modules/\", \
      \"^C:\\path\\to\\WebStorm\\plugins\\JavaScriptLanguage\\helpers\" \
    ], \
    \"unmockedModulePathPatterns\":[ \
      \"^C:\\path\\to\\WebStorm\\plugins\\JavaScriptLanguage\\helpers\" \
    ] \
  }" \
  --env=jsdom --colors \
  --setupTestFrameworkScriptFile "C:\path\\to\\WebStorm\plugins\JavaScriptLanguage\helpers\jest-intellij\lib\jest-intellij-jasmine.js"
```

`moduleNameMapper` was added to the config here because of the `jest` section in my `package.json`, which is also the only entry I have there

Would it be okay to include `/bin/jest` file to `react-app-rewired` package without mentioning it in the `package.json` just to support WebStorm's testing UI? It feels like a hack but this way recomendation to replace `react-scritps` with `react-app-rewired` in every command would apply to this case too

**Comment by timarney** [comment]
Can you outline exactly changes would be needed in this repo to make this possible.  I'm not a WebStorm user so not familiar with the setup.

**Comment by unconfident** [comment]
Straight forward hack that I considered didn't work exactly right. `--watch` argument is getting added somewhere along the way and things go wrong because of this. Currently I'm trying to figure out where it happens, why and how to prevent it.

I'll try to investigate the issue and submit working pull request by the end of the week.

**Comment by unconfident** [comment]
So special treatment of `react-scripts` doesn't end on simply calling a different script with a different set of options (a subset to be more specific), it also adds `CI` environment variable that isn't passed normally.

Almost got it to work. For some reason now it's trying to resolve babel plugins mixed in by `react-app-rewired` relative to the wrong directory

**Comment by unconfident** [comment]
...which was caused by `react-app-rewired/scripts/utils/babelTransform.js`. 

Not entirely confident why, but it seems that when given `--setupTestFrameworkScriptFile` base dir somewhere deep inside `babel-jest` matched directory of that setup file and so plugin which is referenced only by it's name couldn't have been properly resolved.

I... I might have forgotten my github password for current account and my email provider conveniently blocked my email account too (for my safety!), so here, have a patch instead of a pull request.

```diff
Index: packages/react-app-rewired/bin/jest.js
===================================================================
--- packages/react-app-rewired/bin/jest.js	(date 1516584077000)
+++ packages/react-app-rewired/bin/jest.js	(date 1516584077000)
@@ -0,0 +1,26 @@
+#!/usr/bin/env node
+const spawn = require('cross-spawn');
+const args = process.argv.slice(2);
+
+// ignore --config param like it was never there
+// (react-scripts add it too and we override it anyway)
+const configIndex = args.findIndex(x => x === '--config');
+if (!!~configIndex) args.splice(configIndex, 2);
+
+// Alternatively could be detected by _INTELLIJ_JEST_CONFIG_ROOT_DIR env variable
+const setupScriptFileIndex = args.findIndex(x => x === '--setupTestFrameworkScriptFile') + 1;
+const isIntelliJ = !setupScriptFileIndex ? false :
+    args[setupScriptFileIndex].indexOf('jest-intellij-jasmine.js') !== -1;
+
+const result = spawn.sync(
+    process.argv[0],
+    [].concat(
+        require.resolve('../scripts/test'),
+        args
+    ), {
+        stdio: 'inherit',
+        env: Object.assign({}, process.env, isIntelliJ ? { CI: 1 } : null)
+    }
+);
+
+process.exit(result.signal ? 1 : result.status);
Index: packages/react-app-rewired/scripts/utils/babelTransform.js
===================================================================
--- packages/react-app-rewired/scripts/utils/babelTransform.js	(date 1516052118000)
+++ packages/react-app-rewired/scripts/utils/babelTransform.js	(date 1516584077000)
@@ -3,8 +3,8 @@
 
 const customPlugins = [];
 try {
-  require.resolve('babel-plugin-transform-decorators-legacy');
-  customPlugins.push('babel-plugin-transform-decorators-legacy');
+  const decoratorsPluginPath = require.resolve('babel-plugin-transform-decorators-legacy');
+  customPlugins.push(decoratorsPluginPath);
   console.log('⚡ Rewired added babel-plugin-transform-decorators-legacy');
 } catch (e) {
   //do nothing plugin not found
```

**Comment by timarney** [comment]
1.4.1
