### ISSUE TITLE
node version requirement?

### ISSUE THREAD

**Issue by faassen** [timarney/react-app-rewired#19]
I've been using version 0.53 with react-app-rewire-mobx 0.1.0 (thanks!) but when I upgraded to a newer version I get an error about "let" being used on the top level and that this isn't supported. I suspect this means my (operating system supplied) node is too old; I've been using 4.7.3.

So while it's probably just a matter of me having to upgrade Node, I haven't had issues with the rest of the toolchain, so if it isn't a large hassle it might be worthwhile to adjust things. If not, a minimal node version would be nice to specify. (if it's indeed node)

**Comment by timarney** [comment]
What does the error say?

//
Guessing it's coming from the let in this file which I can defiantly swap.

https://github.com/timarney/react-app-rewired/blob/master/packages/react-app-rewired/config/paths.js

**Comment by faassen** [comment]
Yes, I just realized the updates contain Jest support, so I just went and upgraded my Node, and then I saw you ask for the error, which I now don't have anymore. I can confirm after upgrading node to 6.9.5 it works.

**Comment by timarney** [comment]
Okay no worries.  I'll adjust that one variable for the next release - might fix for someone else.
