### ISSUE TITLE
Can't resolve [typeface].woff files

### ISSUE THREAD

**Issue by loganpowell** [timarney/react-app-rewired#194]
Hi! Thank you for creating this library! It's a god-send. However, I ran into a problem today using @kyleamathews [typefaces](https://github.com/KyleAMathews/typefaces) library. It was working before I switched over from CRA. Now I'm getting this:

```
Module not found: Can't resolve './files/lora-latin-400.woff' in 'C:\Users\surface\Projects\Bootcamp\census\graphql\RAATS\node_modules\typeface-lora'
```

I've put in an issue over there, but perhaps others might stumble upon this over here and I wanted to ask if you might have some insight:

https://github.com/KyleAMathews/typefaces/issues/48#issuecomment-360204558

Any thoughts?

**Comment by timarney** [comment]
So without any rewires it's working with CRA?  Possible to setup a test repo to narrow down the issue?

**Comment by loganpowell** [comment]
I can set up a test repo (or two). What would you need in it do run a test?

**Comment by timarney** [comment]
Just something as barebones as possible that recreates your issue.

CRA - Rewire Config + Typefaces installed.

**Comment by loganpowell** [comment]
will do!

**Comment by loganpowell** [comment]
My fault. By going through the test creation, I've found that it's an issue with a specific font from the `typeface` library. Namely, `typeface-lora` Closing!
