### ISSUE TITLE
Examples dir

### ISSUE THREAD

**Issue by geelen** [timarney/react-app-rewired#2]
The list of examples as gists is good but these should be Markdown files in an Examples directory IMO. That way they can have a bit of a preamble (like what dependencies to install) and then they end with a code block with the config to cut & paste. And people can more easily submit PRs to tweak them.

**Comment by timarney** [comment]
Just logging some sample configs that I think people would benefit from.

- CSS Modules
- SASS
- Preact
- Inferno
- Mobx with Decorators (maybe)
