### ISSUE TITLE
[react-app-rewire-eslint] Either remove default `extends` key from loader options or mention it in readme

### ISSUE THREAD

**Issue by unconfident** [timarney/react-app-rewired#202]
Currently documentation suggests using it like this 

```js
config = rewireEslint(config, env);
```

and then creating `.eslintrc` in the project root. This is basically what it says.

What it doesn't say is that because of loader's configuration object eslint config still extends [`eslint-config-react-app`][eslint-config-react-app] which adds loads of plugins and rules to the config. `root: true` doesn't help to prevent this from happening and even if you have no mention of `jsx-a11y` plugin in your config you're still going to get warnings.

One way to get rid of this is to delete said key manually in the callback

```js
config = rewireEslint(config, env, opts => {
  delete opts.baseConfig.extends;
});
```

Whether or not this should be default behavior of rewire is up to you, but I think it at least worth mentioning in the readme of the rewire.

[eslint-config-react-app]: https://www.npmjs.com/package/eslint-config-react-app

**Comment by timarney** [comment]
Feel free to add a note to the Readme I think that would make the most sense.

**Comment by unconfident** [comment]
@timarney backwards compatibility question aside, don't you think it would be more appropriate to remove this key during regular rewire-eslint operation?
