### ISSUE TITLE
Expand getLoader method to iterate over rule.loaders and rule.loader when applicable

### ISSUE THREAD

**Issue by unconfident** [timarney/react-app-rewired#204]
Why?

#### `rule.loaders`

From [documentation](https://webpack.js.org/configuration/module/#rule-loaders):

> This option is **deprecated** in favor of `Rule.use`.
> `Rule.loaders` is an alias to `Rule.use`.

#### `rule.loader`

For starters, it's still [supported by webpack](https://github.com/webpack/webpack/blob/798eaa834af5/lib/RuleSet.js#L200-L215) despite what documentation says.

And it's a common, widely present situation in projects depending on CRA. Because whoever [ported](https://github.com/facebook/create-react-app/commit/12288836e16c455#diff-d2bddbd3bfb7051f9381474c844674faL168) CRA's configuration to Webpack 2 didn't notice that `.extract()` method from `ExtractTextPlugin` returns an array. And so this array still being [passed under `loader` key](https://github.com/facebook/create-react-app/blob/aaf022c/packages/react-scripts/config/webpack.config.prod.js#L259-L285). 

As result `postcss-loader` cannot be found with `getLoader` utility method of `react-app-rewired` in production configuration.

One way to match with webpack's logic is to depend on Webpack's very own internal method `RuleSet#normalizeRules` and, well, normalize rule set before performing the search. But this has two obvious downsides:

- It's an internal API and may change in the future
- It will throw errors if invalid configuration object will be provided

**Comment by timarney** [comment]
Closing this will track under the 2.0 discussion
