### ISSUE TITLE
Use non-standard env files for environment variables?

### ISSUE THREAD

**Issue by hilary-L** [timarney/react-app-rewired#209]
Hi all. Is there a way to use react-app-env or get similar functionality with this package? For a project I'm on, we'd like to have our config files look like: configs/dev.env or configs/prod.env as opposed to configs/.env.dev and configs/.env.prod ...react-app-env allows us to use that kind of file instead of the standard .env file, but I'm not sure how to make it work with react-app-rewired, which we are using in order to use react-app-rewire-yarn-workspaces.

**Comment by timarney** [comment]
Not that I'm aware of.
