### ISSUE TITLE
Change Build CSS Output Path

### ISSUE THREAD

**Issue by tmirmota** [timarney/react-app-rewired#212]
How can I edit the filename for the CSS output in the build config? 

I am trying to remove the `[contenthash:8]`

Similar to issue #201

**Comment by dawnmist** [comment]
Try this (I've managed to modify other options for the ExtractTextPlugin which extracts the CSS).
```javascript
module.exports = {
  webpack: (config, env) => {
    if (env === 'production') {
      /**
       * ExtractTextPlugin is used in production mode to pull css into separate files.
       */
      const extractTextPlugin = config.plugins.find((plugin) => plugin.filename && /.*\.css/.test(plugin.filename));
      if (!extractTextPlugin) {
        console.log(
          `Could not find the existing ExtractTextPlugin: ${JSON.stringify(
             config.plugins,
             (key, value) => {
               if (value instanceof RegExp) {
                 return value.toString();
              }
              return value;
            },
            2
          )}`
        );
        throw new Error(`Could not find the existing ExtractText plugin - check search code`);
      }
      extractTextPlugin.options = { ...extractTextPlugin.options, filename: 'myChangedFilenamePattern' };
    }
    return config;
  }
}
```
Note that changing the name is only required in production builds - the dev builds usually put the css inside the index.html file.

**Comment by dawnmist** [comment]
The default value for the css filename is `'static/css/[name].[contenthash:8].css'`.

All that aside, the `[contenthash:8]` section is actually used for identifying to viewer's browser that the css for the page has changed, and that they need to retrieve the new version (cache-busting). Unless you have a good reason for removal, I'd recommend thinking carefully about actually removing the `[contenthash:8]` part from the filename - it can be potentially detrimental to your site to do so (e.g. the user's browser may not download the updated versions of the css files when they change, so the user sees outdated styles for some parts of the site and potentially no styles for new sections of the site).
