### ISSUE TITLE
[eslint] Rewired eslint is using wrong version of eslint and plugins

### ISSUE THREAD

**Issue by randycoulman** [timarney/react-app-rewired#215]
Thanks for this super-helpful project!  I really like how it's designed and how extensible it is.

I ran into an interesting issue.  I've found a work-around, but I'm opening this issue to see if this is something you'd like to have fixed here instead.

In my project, I want to use my own eslint configuration, which includes newer versions of some of the plugins that create-react-app uses.

When I run eslint directly, everything works fine.  But when CRA runs eslint as part of its webpack pipeline, it runs the version of eslint (and therefore its plugins) that are down in `node_modules/react-scripts/node_modules`.

My work-around is to use the undocumented `overrides` parameter from #122 to re-resolve the location of `eslint` being passed to `eslint-loader` relative to my project:

```js
const rewireEslint = require("react-app-rewire-eslint");

const overrideOptions = options => {
  options.eslintPath = require.resolve("eslint");
};

module.exports = function override(config, env) {
  config = rewireEslint(config, env, overrideOptions);
  return config;
}
```

Is this something that should be done in this package instead?  Maybe with some protection to only do the replacement if there is a version of eslint installed locally?

If so, I can try to find some time to work on a PR for it.  At the very least, the `override` option needs to be documented.  I'll try to work on a PR for that as well.

**Comment by randycoulman** [comment]
Update: documentation PR is up: https://github.com/timarney/react-app-rewired/pull/216

**Comment by timarney** [comment]
Merged the PR (for the docs) - will wait it see if anyone else comments.  I don't use this package myself so would rather get thoughts from people who do.

**Comment by timarney** [comment]
> Is this something that should be done in this package instead? Maybe with some protection to only do the replacement if there is a version of eslint installed locally?

@chrbala @dawnmist any thoughts?

**Comment by jlaustill** [comment]
I'm not sure if this is my issue or not.  I added this to overrides

` config = injectBabelPlugin('@babel/plugin-proposal-optional-chaining', config);`
and changed a line to 

`return formatName(borrower?.name);`
and I'm getting the compile error

`Failed to compile.

./src/application-summary/components/application-summary-sidebar.js
/Users/jaustill/git/mortgage-operator-ui/src/application-summary/components/application-summary-sidebar.js
  55:33  error  Unexpected use of 'name'  no-restricted-globals

✖ 1 problem (1 error, 0 warnings)`

Is this related to the eslint version being wrong?  I'm using react-app-rewired@next and react-scripts@2.0.0-alpha if that helps.

**Comment by timarney** [comment]
@jlaustill the next version of this package is stale at the moment while react-scripts does it's thing.  That is to say don't try using it yet.

@randycoulman seems this issue is also stale with no feedback from some folks who have been helping maintain that package.  Going to close and leave it at the documentation update that was merged.

**Comment by jlaustill** [comment]
@timarney Bummer, but thanks for taking the time to respond!
