### ISSUE TITLE
Potential react-app-rewired-mobx peer dependencies break change

### ISSUE THREAD

**Issue by cyan33** [timarney/react-app-rewired#217]
The latest mobx and mobx-react version have been updated to 4.1.0 and 5.0.0 recently, while `react-app-rewired-mobx` still requires lower versions of each:

```
npm WARN react-app-rewire-mobx@1.0.7 requires a peer of mobx@>=3.1.17 < 4 but none is installed. You must install peer dependencies yourself.
npm WARN react-app-rewire-mobx@1.0.7 requires a peer of mobx-react@>=4.2.2 < 5 but none is installed. You must install peer dependencies yourself.
```

Is it safe to update the package.json of react-app-rewired-mobx as well?

**Comment by timarney** [comment]
I'll try to test with my test package later this week.  Should be safe but I haven't looked at the MobX updates yet.

**Comment by timarney** [comment]
1.0.8 is up
