### ISSUE TITLE
interest in react-intl integration?

### ISSUE THREAD

**Issue by faassen** [timarney/react-app-rewired#22]
today I looked into react-intl. It offers a babel plugin for automatically extracting message ids from source code:

https://github.com/yahoo/babel-plugin-react-intl

I managed to use react-app-rewired to integrate it. Here's the code:

```
const babelLoader = function(conf) {
  return conf.loader === "babel";
};

//webpack2
function rewireIntl(config, env) {
  const babelrc = config.module.loaders.find(babelLoader).query;
  babelrc.plugins = [
    [
      "react-intl",
      {
        messagesDir: "./messages/"
      }
    ]
  ].concat(babelrc.plugins || []);
  return config;
}

module.exports = rewireIntl;
```

If you're interested I could create a pull request so you can maintain it as part of this project. One question is how to configure it. I've hardcoded "messagesDir" into it for now, and the configuration options aren't that broad, but perhaps people want something more.

**Comment by timarney** [comment]
@faassen very nice.  

I'm slightly mixed feelings on including in this repo.  

Personally I would like to see people adding 'rewires' to npm and I can link / point people to them from this repo.  The reason for that being if I don't personally use all the rewires i.e. which is currently the case with the relay rewire in this repo. I can't really at least not without tests for each in place if they will continue working. For instance when Webpack 2 hits CRA (soon) I won't know if the Relay one still works unless @pasviegas tells me it does. 

I like the path of the rewires vs everyone needing to roll a config for MobX etc... but need some community around that idea to make it go further.

Note: I started down the testing path here but I'm really not sure what the best strategy is for the tests https://github.com/timarney/react-app-rewired/issues/9

**Comment by pasviegas** [comment]
My view is that right now would be better to have as many rewires as possible in the same repo so it can get some traction and release more people from the strict rules in create-react-app. 😄

**Comment by timarney** [comment]
Alright - let's add it to this repo.  @faassen if you want to create a PR at some point please do.  Might want to wait until 0.10.0 of CRA (that will be the Webpack2 release ... expecting to rejig some of the configs for that - I already prepped the MobX one).

@pasviegas thoughts on the note about: 

>  I've hardcoded "messagesDir" into it for now, and the configuration options aren't that broad, but perhaps people want something more.

Probably not the best place but maybe could be added to the .env file.

**Comment by timarney** [comment]
@faassen going to close this issue.  Feel free to create a PR.  Thinking just hardcode the ./messages/ path for now and see if anyone has an issue with that ;)

**Comment by timarney** [comment]
@faassen just so your aware - https://github.com/timarney/react-app-rewired/issues/26 if you have any interest in adding a PR for the upcoming version.
