### ISSUE TITLE
[Relay modern] Can't get react-app-rewire-relay to work.

### ISSUE THREAD

**Issue by Togrias** [timarney/react-app-rewired#223]
const babelrc = config.module.loaders.find(babelLoader).query;
                                        ^
TypeError: Cannot read property 'find' of undefined

**Comment by timarney** [comment]
Hi @Togrias 

I don't use relay modern so can't really offer any assistance.  You might try looking at some of the utility methods

```
const getBabelLoader = function(rules) {
  return getLoader(rules, babelLoaderMatcher);
};
```
