### ISSUE TITLE
Error lost ')' !!!!!! when run npm install to build project

### ISSUE THREAD

**Issue by yaolei** [timarney/react-app-rewired#229]
Error message : getLoader(rule.use || rule.oneOf || (Array.isArray(rule.loader) && rule.loader) || [], matcher);

This PR
https://github.com/timarney/react-app-rewired/commit/262495e321f81313a53078758db9f55d43354c57

lost a ')'
please fix this defect or roll-back code

**Comment by muhilvarnan** [comment]
Can you guys fix this asap? our application is breaking because of it.

**Comment by CraigCarpenter** [comment]
We are also experiencing this issue.

**Comment by timarney** [comment]
react-app-rewired@1.5.2
