### ISSUE TITLE
SASS rewire deprecatiation

### ISSUE THREAD

**Issue by Hurtak** [timarney/react-app-rewired#23]
Hi,

I saw that you deprecated the SASS rewire because Create React App added official guide about how to add SASS support. I looked at the guide and it is compiling SASS on the side without using Webpack, so you do not have the benefits of the single dependency tree, and other Webpack stuff. Are we really sure we want to deprecate this rewire for what seems like inferior solution?

Also thanks for creating react-app-rewired, it is really useful addition to the Create React App.

**Comment by timarney** [comment]
Happy to keep it going if people (yourself included) feel it's still needed.  I no longer use SASS in my own projects and your the first to express concern about the deprecation. 

Have you looked at SASS support with Webpack2?  That will be needed for the 0.10 release of CRA.

Also would be great to get more maintainers on board who are actually using the rewires if you interested.

**Comment by Hurtak** [comment]
I have briefly played with Less and Webpack2 and plugging it in (along with extract-text-webpack-plugin) seemed similarly straightforward as it was in Webpack1 so I would not expect any problems.

I will try to make pull request, when CRA updates to Webpack2, to update SASS - at the moment I am actually using Less with react app rewired, I just took your SASS rewire and switched SASS loader for Less loader.

Also, I would like to see Less rewire in this 'official' repository of rewires. Would you be interested in pull request adding Less rewire? Since I am using it on one project I might be able to maintain it reasonably (along with SASS since they are almost the same).

**Comment by timarney** [comment]
Okay sounds good yes please create a pull request and we'll include the updated SASS (when it's time) and a LESS loader package in this repo.

Going to close this issue.  Can re-open as needed.

**Comment by timarney** [comment]
@Hurtak this repo now uses Webpack2 - feel free to submit a PR.
