### ISSUE TITLE
Debugging tests in vscode -  No breakpoints being hit

### ISSUE THREAD

**Issue by thejuan** [timarney/react-app-rewired#232]
I'm trying to setup vscode to debug tests, I haven't been able to find any guidance.
The tests run fine, but breakpoints are not hit. Any one have a working setup for debugging tests in vs-code?

node: 9.5.0
jest: 21.2.1
react-app-rewired: 1.4.1

My vs-code launch.json
`{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Jest Tests",
      "type": "node",
      "request": "launch",
      "program": "${workspaceFolder}/node_modules/.bin/react-app-rewired",
      "env": {},
      "args": [
        "test",
        "--env=jsdom",
        "--testPathPattern",
        "ActionButton.test.js"
        //"--testNamePattern",
        //"renders the loading state",
      ],
      "protocol": "inspector",
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen"
    }
  ]
}
`

**Comment by pyyding** [comment]
Hey, @thejuan!

Do you remember, what was the solution for you?

**Comment by thejuan** [comment]
Sorry no, we did get it working. We’ve since moved to cra2 and no longer using this project.

**Comment by telekommander** [comment]
This post is quite old, but i run in the same issue.
Below some lines of the `config-overide.js` that should work to force the Debug-Mode in VSCode:

```
const paths = require('react-scripts/config/paths');
module.exports = {
    webpack: (config) => {
        config.output = {
            path: paths.appBuild,
            pathinfo: true,
            filename: 'static/js/[name].[hash].js',
            chunkFilename: 'static/js/[name].[hash].chunk.js',
        };
        return config;
    },
};
```
