### ISSUE TITLE
Scripts should hardcode NODE_ENV

### ISSUE THREAD

**Issue by bringel** [timarney/react-app-rewired#235]
The regular react-scripts verisons of start and build hardcode NODE_ENV to be 'development' and 'production'. Trying to run any of these scripts from inside atom (using atom-build and atom-build-yarn) will fail if your are doing specific rewires for production vs development, because atom sets NODE_ENV to production

**Comment by timarney** [comment]
Outside of the production config in the CRA repo do you know other spots where the env is hardcoded?
