### ISSUE TITLE
How to override checkRequiredFiles?

### ISSUE THREAD

**Issue by mhuggins** [timarney/react-app-rewired#244]
When wanting to set the entry point, there are three options.  The third option, which is seemingly the most ideal, appears below.

> Override the react-dev-utils/checkRequiredFiles function to always return true (causing create-react-app to no longer try to enforce that the entry file must exist).

It's unclear from the description how to go about doing this.  Is the only way to fork the repo and point the project to that fork?

**Comment by mhuggins** [comment]
I figured it out with a little help from [this comment](https://github.com/timarney/react-app-rewired/issues/189#issuecomment-358298647).  Here's my final solution in case anyone can use it:

```js
const merge = require('webpack-merge');
const { paths } = require('react-app-rewired');

function updateReactScriptPath(filename) {
  const originalPaths = require.cache[
    require.resolve(`${paths.scriptVersion}/config/paths.js`)
  ];

  Object.assign(originalPaths.exports, {
    appIndexJs: filename
  });
}

module.exports = function rewireEntry(filename) {
  return (config, _env) => {
    updateReactScriptPath(filename);

    const entry = [
      ...config.entry.slice(0, config.entry.length - 1),
      filename
    ];

    return merge({ ...config, entry }, {
      output: {
        filename: 'static/js/[name].bundle.js'
      }
    });
  };
};
```

Then to use it:

```js
module.exports = compose(
  rewireEntry(path.resolve(__dirname, 'src/main/index.js')),
  // ...
)
```

**Comment by mhuggins** [comment]
I actually ended up circling back on this and needed more to answer my original question.  I introduced my own `build.js`, `start.js`, and `test.js` scripts that I run instead of react-app-rewired from my `package.json`.  Those files basically look like this with the last line representing the appropriate script, and `NODE_ENV` set accordingly:

```js
/* eslint-disable import/no-dynamic-require */

process.env.NODE_ENV = process.env.NODE_ENV || 'development';

// prevent `react-scripts` from checking for the existence of `public/index.html`
const checkRequiredFilesPath = 'react-dev-utils/checkRequiredFiles';
require(checkRequiredFilesPath);
require.cache[require.resolve(checkRequiredFilesPath)].exports = () => true;

// run original script
require('react-app-rewired/scripts/start');
```

**Comment by frozzen10** [comment]
I was able to achieve what you wanted.
Here is the code I used:
```javascript
module.exports = {
  webpack: (config, env) => {
    // your logic here
  },

  devServer: (configFunction) => (proxy, allowedHost) => {
    const config = configFunction(proxy, allowedHost);

    const checkRequiredFilesPath = "react-dev-utils/checkRequiredFiles";
    require(checkRequiredFilesPath);
    require.cache[require.resolve(checkRequiredFilesPath)].exports = () => true;

    return config;
  },

  paths: (paths, env) => {
    const checkRequiredFilesPath = "react-dev-utils/checkRequiredFiles";
    require(checkRequiredFilesPath);
    require.cache[require.resolve(checkRequiredFilesPath)].exports = () => true;

    return paths;
  },
};
```
With this there is no need to write custom build.js and start.js (like with ejecting) and just use power of react-app-rewired.
Hope it helps!
