### ISSUE TITLE
Creating separate builds for production and staging

### ISSUE THREAD

**Issue by ForumT** [timarney/react-app-rewired#247]
Hi,

I am trying to use react-app-rewired with my app. I need separate builds for prod and dev. My code is like so:

Package.json:
"build:staging": "cross-env NODE_ENV=staging react-app-rewired build",
"build": "cross-env NODE_ENV=production react-app-rewired build",

But even when i do build:staging, NODE_ENV is set to production and it creates production build. How can i create a staging build?

I am using react version 16.3.1 and react-app-rewired version 1.5.2

**Comment by timarney** [comment]
You can find some thoughts on this in the CRA repo - https://github.com/facebook/create-react-app/issues/790 (looks like people have done it)

This comment specifically notes why it's been setup the way it has https://github.com/facebook/create-react-app/issues/790#issuecomment-281984190
