### ISSUE TITLE
Can't get plugin 'transform-object-rest-spread' working

### ISSUE THREAD

**Issue by c-goettert** [timarney/react-app-rewired#254]
I am trying to get babel plugin [transform-object-rest-spread](https://babeljs.io/docs/plugins/transform-object-rest-spread/) to work, to be able to use syntax like: 
`let b = {...a, test2: 'test2'}`.

I can get it working on an ejected project with the following webpack-config:
```
{
  test: /\.(js|jsx|mjs)$/,
  include: paths.appSrc,
  loader: require.resolve('babel-loader'),
  options: {
    cacheDirectory: true,
    babelrc: false,
    presets: ['react', 'es2015'],
    plugins: ['babel-plugin-transform-es2015-destructuring', 'transform-object-rest-spread']
  }
}
```

I tried to archive the same goal using `react-app-rewired`. I created a `config-overrides.js` and used `injectBabelPlugin` as stated in the documentation:

```
const {injectBabelPlugin} = require('react-app-rewired')

module.exports = function override (config, env) {
  config = injectBabelPlugin(['babel-plugin-transform-es2015-destructuring', 'transform-object-rest-spread'], config)
  return config
}
```

Still I get an error that babel doesn't recognize this syntax:
![bildschirmfoto 2018-06-07 um 15 53 07](https://user-images.githubusercontent.com/7591624/41104121-fa4c0108-6a6a-11e8-98b3-de423b5c26b4.png)

Does anyone have a clue what I'm doing wrong?

**Comment by timarney** [comment]
transform-object-rest-spread is built in to Create React App.

https://www.npmjs.com/package/babel-preset-react-app
<img width="745" alt="screen shot 2018-06-11 at 6 58 17 am" src="https://user-images.githubusercontent.com/62242/41228012-dd99f6c8-6d44-11e8-8b28-d3e37f6194c6.png">

**Comment by c-goettert** [comment]
Thanks for this hint  @timarney, I could now figure out that it's caused by a node-module using object spread. If i'm right, `node_modules` folder is not included for babel-compilation as default (only source-path is included using `include: paths.appSrc` property in webpack.config).
Anyway, can I use `react-app-rewired` to include specific node-modules so that they will also be compiled by babel?

**Comment by timarney** [comment]
Personally I would see if an issue should be raised with that module...

Outside of that you should be able to do something with either the include or exclude path (for the webpack config)

<img width="594" alt="screen shot 2018-06-12 at 10 21 11 am" src="https://user-images.githubusercontent.com/62242/41296218-75bcdf2a-6e2a-11e8-8bbb-051618001a4b.png">


https://github.com/facebook/create-react-app/blob/next/packages/react-scripts/config/webpack.config.dev.js

Going to close this as there isn't an issue with this repo.
