### ISSUE TITLE
Deprecate or update react-app-rewire-relay?

### ISSUE THREAD

**Issue by orta** [timarney/react-app-rewired#255]
Hey there, it might be worth either deprecating [this package](https://github.com/timarney/react-app-rewired/blob/master/packages/react-app-rewire-relay/index.js) or bringing it up to date by making it use `injectBabelPlugin`?

In my app, I replaced it with the usage of `injectBabelPlugin` to look like this in the config:

```js
const {
  rewireWebpack: rewireTypescript,
  rewireJest: rewireTypescriptJest,
} = require("react-app-rewire-typescript-babel-preset")
const { injectBabelPlugin } = require("react-app-rewired")

module.exports = {
  webpack: function(config, env) {
    let webpack = rewireTypescript(config)
    webpack = injectBabelPlugin("relay", webpack)
    return webpack
  },
  jest: function(config) {
    let jest = rewireTypescriptJest(config)
    jest = injectBabelPlugin("relay", webpack)
    return jest
  },
}
```

If you have opinions either way, I'm happy to take a look at doing that.

**Comment by timarney** [comment]
I would be for deprecating and maintaining outside of the main repo. To me continuing down the path of community maintained rewires makes the most sense. 

https://github.com/timarney/react-app-rewired#community-maintained-rewires

**Comment by timarney** [comment]
Closing this feel free to make an external repo and we'll like to it + likely deprecate the other (when it makes sense to do so)
