### ISSUE TITLE
Using with third party tools and different scripts-versions

### ISSUE THREAD

**Issue by city41** [timarney/react-app-rewired#256]
[This section](https://github.com/timarney/react-app-rewired#4-provide-rewired-webpack-config-for-3rd-party-tools) of the README nicely got me up and running with third party tools (in my case, react-cosmos).

However I am also using `react-scripts-ts`. In order to get cosmos working I launch it with `cosmos --scripts-version react-scripts-ts`. This does work because everything is in the same process so rewired is able to find the process argument. But it seems a little on the lucky side.

Does it make sense for react-app-rewired to also support getting scripts-version from an env variable, to make this interaction a little more robust?

**Comment by timarney** [comment]
@Guria thoughts on this given your original PR - https://github.com/timarney/react-app-rewired/pull/152

**Comment by timarney** [comment]
Going to leave as is for now something we can explore in a 2.x release
