### ISSUE TITLE
CRA 0.10.0 - prep

### ISSUE THREAD

**Issue by timarney** [timarney/react-app-rewired#26]
@pasviegas @Hurtak just FYI

CRA - pushed up a canary version to NPM so you can now test rewires against the 0.10.0 (webpack2 version of that repo)

I setup a Webpack2 branch of this repo and also pushed up alphas.

I have this repo running to test the MobX rewire - https://github.com/timarney/mobx-rewire-test with CI.

==============================

```bash
npm info react-scripts

npm info react-app-rewired
```

```
{ name: 'react-scripts',
 ...
     canary: '0.10.0-alpha.328cb32e' },
```

**Comment by pasviegas** [comment]
Nice! This is pretty cool!

**Comment by Hurtak** [comment]
Looking good, I managed to get React-App-Rewired working with CRA 0.10.0 from the "canary" tags. Also I updated Less rewire to Webpack2 so that should be ready when CRA 0.10 comes out.

**Comment by timarney** [comment]
Thanks @Hurtak just merged that.

**Comment by timarney** [comment]
1.0.1 is up - uses react-scripts 1.0.0
