### ISSUE TITLE
Contribution request on deprecated react-app-rewire-sass

### ISSUE THREAD

**Issue by aze3ma** [timarney/react-app-rewired#263]
I am asking if I can contribute to ```react-app-rewire-sass``` so I know that CRA has they own approach now to include (Sass, less, etc.) but in case some people like me doesn't like this approach to locally watch files on the fly using ```node-sass-chokidar``` so I've already created one [here](https://github.com/aze3ma/react-app-rewire-scss) that works fine, so I was search here for any contribution guide or something but It my first contribution so I didn't catch anything similar.

**Comment by timarney** [comment]
Happy to link out to your package / point to it from deprecated one in the Readme - feel free to file a PR.

Trying to move away from having everything under this repo (to help keep the issues focused on the core code)

Should also be listed here https://github.com/timarney/react-app-rewired#community-maintained-rewires

**Comment by aze3ma** [comment]
@timarney Thank you, so now you need it to be listed here so creating a PR to update the readme and functionality for the packages directory or just you will list mine here to reduce the issues amount.

**Comment by timarney** [comment]
The Readme here can be updated - Thinking add a note under the Deprecated notice that can link to your repo.  That should pick up some traffic from NPM if people come in that way.

Maybe we can just change current read old instructions or something.

https://github.com/timarney/react-app-rewired/tree/master/packages/react-app-rewire-sass


I haven't looked into it as I'm not really using SASS anymore but what are your thoughts on the 2.0 SASS support in CRA.

**Comment by aze3ma** [comment]
Okay so I will make a PR for the README linking the new one, the ```create-react-app``` support for ```SASS``` just watching the files and compiling it on the fly so they duplicate the files for example ```App.scss``` and ```App.css``` at the same directory but in my opinion the ```react-app-rewired``` approach is much better from a dev experience perspective also it adds a layer of consistency across your application without the hassle of ejection configuration, so that's why I loved your idea about rewiring the configuration.

**Comment by aze3ma** [comment]
@timarney please could you check #266

**Comment by timarney** [comment]
That works thanks.

**Comment by aze3ma** [comment]
@timarney I am with approach of splitting all packages from the root package ```react-app-rewired``` so could you listed [here](https://github.com/timarney/react-app-rewired#community-maintained-rewires).

**Comment by timarney** [comment]
Yes feel free to list it there.

**Comment by aze3ma** [comment]
@timarney Thank you, #266
