### ISSUE TITLE
react-app-rewired: Permission denied

### ISSUE THREAD

**Issue by ankit7878** [timarney/react-app-rewired#264]
**Problem:**
Getting permission denied, looks like could not able to run the script? what should i do ? i couldn't able to find the solution related to react-app-rewired. any help would be appropriated ?

root@ankit-desktop:/media/ankit/DATA-D/data/isomorphic-react-redux-admin/isomorphic# npm start

> isomorphic@2.6.0 start /media/ankit/DATA-D/data/isomorphic-react-redux-admin/isomorphic
> react-app-rewired start

sh: 1: react-app-rewired: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! isomorphic@2.6.0 start: `react-app-rewired start`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the isomorphic@2.6.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-30T04_02_41_656Z-debug.log

PC configuration:
OS: ubuntu 14.04

Error log in detail:

Problem:
Getting permission denied, looks like could not able to run the script? what should i do ? i couldn't able to find the solution related to react-app-rewired. any help would be appropriated ?

**Comment by timarney** [comment]
Hi not familiar with isomorphic-react-redux-admin and I can't offer support for config issues simply not enough time.
