### ISSUE TITLE
react-app-rewire-preact blows away default resolve configuration

### ISSUE THREAD

**Issue by stevenmirabito** [timarney/react-app-rewired#269]
In the [Preact rewire](https://github.com/timarney/react-app-rewired/blob/master/packages/react-app-rewire-preact/index.js), the entire `config.resolve` object in the CRA Webpack config is blown away and replaced with the object provided in the rewire. The Preact aliases should be added to the existing `config.resolve.alias` object instead.

**Comment by timarney** [comment]
PR Merged
