### ISSUE TITLE
Breaks under jest

### ISSUE THREAD

**Issue by jozsi** [timarney/react-app-rewired#272]
I am using `react-app-wired` with `react-cosmos`. When I run my tests via `react-app-wired test`, it breaks:
```
 FAIL  src/Routes/login.test.js
  ● Test suite failed to run

    SyntaxError: Identifier 'jest' has already been declared

    > 1 | const overrides = require('react-app-rewired/config-overrides');
```

`jest` is already defined globally when [react-app-rewired/config-overrides#L23](https://github.com/timarney/react-app-rewired/blob/master/packages/react-app-rewired/config-overrides.js#L23) attempts to redefine it.

**Comment by timarney** [comment]
@Guria or @dawnmist any thoughts on this?

**Comment by jozsi** [comment]
Sure, @dawnmist! Here you go: https://github.com/jozsi/rewired-jest-bug

I am trying to make snapshots of Cosmos Fixtures (https://github.com/react-cosmos/react-cosmos#global-jest-snapshot). The configuration is the one described in the Cosmos README: https://github.com/react-cosmos/react-cosmos#with-react-app-rewired

The repo is a monorepo using yarn workspaces: https://github.com/viewstools/yarn-workspaces-cra-crna

**Comment by dawnmist** [comment]
![test result](https://user-images.githubusercontent.com/5810277/43047246-b44081e0-8e17-11e8-96e9-9d7a27cece26.png)
In the example repo, I'm getting the initial App test to run successfully, and the cosmo test to show no tests defined. It doesn't seem to be picking up the HelloWorld component & fixture. Is it missing a config option for Component paths or something?

**Comment by jozsi** [comment]
This is interesting, I checked out the repo and received the same error as you (which sounds better, could be my user error).
Then I removed `yarn.lock` and `node_modules` from the root folder, then `node_modules` from the `web` folder, ran `yarn` from root and getting the `SyntaxError: Identifier 'jest' has already been declared` error again. The yarn.lock file hasn't even changed... can you try re-running the tests?

**Comment by dawnmist** [comment]
I tested removing the yarn.lock file and the node_modules directories in both the top level and web directories, and was able to get a 'jest has already been declared' error, but it didn't actually refer to react-app-rewired anywhere in the stack trace. I did note that some babel-loader cache files were removed as a result of removing the node_modules directory - were those supposed to be checked in?
![image](https://user-images.githubusercontent.com/5810277/43051578-56e2cc7c-8e5f-11e8-8875-84bbd9dab400.png)

As a test, I tried resetting the test target to use react-scripts directly (i.e. setting `"test": "react-scripts test --env=jsdom",`) and received the identical error and stacktrace to what I'd received when it used react-app-rewired.

I would suggest checking with react-cosmos/react-cosmos-telescope whether this is an issue they've seen previously. It may be something to do with how its been configured. The stack trace shows it trying to create the cosmos config twice (top 7 lines), with the second attempt triggering the duplicate jest error.

**Comment by jozsi** [comment]
Thanks for investigating time!

Apparently, on first run it works, on second run it does not.

Removing the `react-app-rewired/config-overrides` require from `cosmos.config.js` and reverting to `"test": "react-scripts test --env=jsdom"` results in pass:
```
 PASS  src/App.test.js
 PASS  src/cosmos.test.js

Snapshot Summary
 › 1 snapshot written in 1 test suite.

Test Suites: 2 passed, 2 total
Tests:       2 passed, 2 total
Snapshots:   1 added, 1 total
Time:        2.079s
Ran all test suites.
```

I've updated the repo, removed `react-cosmos` from it. The following fails with the same redeclaration error:
```
const overrides = require("react-app-rewired/config-overrides");

it("is an empty test", () => {});
```

**Comment by skidding** [comment]
I think the problem is that you're importing `react-app-rewired/config-overrides` in a test file, which can run more than once in the same session. It's a mutative import, and should only be imported once. You issue seems to go away if we do the import in the Jest's setup file https://github.com/jozsi/rewired-jest-bug/pull/1/files.

---

❤️ the react-cosmos mention in `react-app-rewired`! @Guria

![image](https://user-images.githubusercontent.com/250750/43100986-b625d9f2-8ecf-11e8-94ba-c1c5b2638c6b.png)

**Comment by jozsi** [comment]
Thanks @skidding! We should revise the [react-cosmos docs](https://github.com/react-cosmos/react-cosmos#with-react-app-rewired) cause the way described there breaks (or I'm missing something; check out the repo, added `react-cosmos` and `react-cosmos-telescope` back).

**Comment by skidding** [comment]
> We should revise the react-cosmos docs cause the way described there breaks (or I'm missing something; check out the repo, added react-cosmos and react-cosmos-telescope back).

Ouch! Didn't realize that. Yes, config file should definitely be _pure_.
