### ISSUE TITLE
Monorepo Compatibility 

### ISSUE THREAD

**Issue by DavidHooper** [timarney/react-app-rewired#274]
The following line of code assumes that the react-scripts or react-scripts-ts modules are going to be in the same node_modules folder. This breaks in monorepos like yarn workspaces or lerna when there's the ability to have non-hoisted modules.

https://github.com/timarney/react-app-rewired/blob/10891d8d5879ff0bfe6e26ad64e9630bbdcbec17/packages/react-app-rewired/scripts/utils/paths.js#L24

**Comment by timarney** [comment]
Feel free to file a PR if you might have a fix.

**Comment by bdryl-softserve** [comment]
What would be desired solution in that case?

**Comment by benedyktdryl** [comment]
What would be desired solution in that case?

**Comment by rjbergerud** [comment]
Also came up against this issue.  Did you find a way around it @DavidHooper ?
