### ISSUE TITLE
Reverse Proxy issue

### ISSUE THREAD

**Issue by jlaustill** [timarney/react-app-rewired#279]
I'm using the following config-overrides.js to get devServer to A. load the bundle link dynamically without a beginning /, and B. expect a path of /xxx.  This works when I load from localhost/xxx.  However, when I reverse proxy this from an AWS host via ssh, it is serving the index.html file without compiling it, so the %PUBLIC_URL% is still there, and the bundle script isn't inserted.  I'm confused why localhost serves up the compiles html, but the reverse proxied host doesn't.  I'm sure this isn't an issue with reacp-app-rewired, but I'm hoping someone here can help me figure out what is going wrong.  If there's a better place to ask even that would be helpul, and if I can provide any further details just let me know.  I'm stuck on something that seems like it should be so easy.  I've tried configuring port= and public='my.domain' and neither seem to make a difference.

```
  /* eslint-disable no-param-reassign */
  const rewireReactHotLoader = require('react-app-rewire-hot-loader');

  module.exports = {
    webpack: function override(config, env) {
      config = rewireReactHotLoader(config, env);
      if (!process.env.HTTPS) {
        config.output.publicPath = '';
        console.log('webpack', config);
      }
      return config;
    },
    devServer: function (configFunction) {
      return function (proxy, allowedHost) {
        // Create the default config by calling configFunction with the proxy/allowedHost parameters
        const config = configFunction(proxy, allowedHost);

      if (!process.env.HTTPS) {
        config.publicPath = '/xxx';
        config.disableHostCheck = true;
        config.open = false;
        console.log('debug', config);
      }
      return config;
    };
  },
};
```

**Comment by timarney** [comment]
Closing this.  Left it open til now to see if anyone could lend a hand.
```
"I'm hoping someone here can help me figure out what is going wrong"
```
