### ISSUE TITLE
How to pass options to babel plugins?

### ISSUE THREAD

**Issue by xueqingxiao** [timarney/react-app-rewired#281]
version: next

```js
injectBabelPlugin('@babel/plugin-proposal-decorators', config)
```

**Comment by vogelino** [comment]
@xueqingxiao How did you solve your problem?

**Comment by xueqingxiao** [comment]
@vogelino eject it！😂😂😂

**Comment by xueqingxiao** [comment]
@vogelino I've digged into source code, there is no way to pass args into babel plugin. So, I eject it.

**Comment by vogelino** [comment]
You‘re Right then @xueqingxiao. The only viable option seems to be ejecting. Giving the circumstances, I am then pretty skeptical about the benefit of rewire then. Maybe I missed the point?

**Comment by xueqingxiao** [comment]
@vogelino No silver bullet, We must make some trade-offs between flexibility and convenience.
