### ISSUE TITLE
How to read process.env in app?

### ISSUE THREAD

**Issue by oknoorap** [timarney/react-app-rewired#282]
I only got these variable, when I console log `process.env`

```javascript
NODE_ENV: "development"
PUBLIC_URL: ""
```

how to access process environment variable (defined via `.env`) in app?

**Comment by timarney** [comment]
Core Create React App outlines that here https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-custom-environment-variables

**Comment by oknoorap** [comment]
apparently, we can add env variable by adding it in `.env` file with `REACT_APP_` prefix. e.g
```bash
REACT_APP_MY_VARIABLE=value
````
thanks.
