### ISSUE TITLE
react-app-rewire-mobx peer dependencies warning

### ISSUE THREAD

**Issue by Plortinus** [timarney/react-app-rewired#283]
Mobx's current version is `5.0.3`.Install `react-app-rewire-mobx` throw a warning:
```js
npm WARN react-app-rewire-mobx@1.0.8 requires a peer of mobx@>=3.1.17 < 5 but none is installed. You must install peer dependencies yourself.
```

**Comment by timarney** [comment]
This is by design so you can use the latest version see https://github.com/timarney/react-app-rewired/issues/51#issuecomment-313404062
