### ISSUE TITLE
Error during npm install, git checkout rewired-entry-support

### ISSUE THREAD

**Issue by roborourke** [timarney/react-app-rewired#284]
I'm getting the following error during an npm install with version `^1.5.2`

```
Command failed: /usr/local/bin/git checkout rewired-entry-support
```

I've tried reinstalling, verifying & cleaning the npm cache but nothing seems to be working. Any ideas? Does the package need to be republished since the security breach?

**Comment by timarney** [comment]
What's rewired-entry-support?

**Comment by roborourke** [comment]
@timarney I just realised as I responding to this, I had a dependency pointing to an unrelated repo at a branch called `rewired-entry-support` which was since merged & deleted. I'm having a stupid day and clearly need more coffee. Sorry!

**Comment by roborourke** [comment]
Repo was https://github.com/humanmade/react-wp-scripts, I added support for `react-app-rewired` a while back. Thanks for this project!

**Comment by timarney** [comment]
Sure thing - enjoy the coffee :)
