### ISSUE TITLE
Is it possible to fetch an endpoint which has a set of colors and then use them in *config-overrides.js*

### ISSUE THREAD

**Issue by ghoshnirmalya** [timarney/react-app-rewired#287]
I've an API endpoint which returns a set of colors. Now, consider my config in *config-overrides.js*:

```
config = rewireLess.withLoaderOptions({
    modifyVars: { "@primary-color": "#1DA57A" }
  })(config, env);
```

Is it possible to fetch an API and use that data to update the *@primary-color* attribute's value?

**Comment by timarney** [comment]
I haven't seen anything like that done before.
