### ISSUE TITLE
autoprefixer no effect！please give me help

### ISSUE THREAD

**Issue by chengwangping** [timarney/react-app-rewired#289]
![image](https://user-images.githubusercontent.com/5220595/43623440-ca6fc886-9713-11e8-8331-3ee7904d838e.png)

![3814](https://user-images.githubusercontent.com/5220595/43623086-052847ac-9712-11e8-9fb7-340d31a31e88.png)

**Comment by chengwangping** [comment]
![image](https://user-images.githubusercontent.com/5220595/43623299-1964bbd2-9713-11e8-8f5f-ebf710ec0837.png)

**Comment by dawnmist** [comment]
Are you intending to replace all the existing options, or to add the importLoaders variable into the options field - because at the moment you are completely replacing them? If you're trying to add it to the existing list of options, you need to include the existing options too.
```javascript
loader.options = {
  ...loader.options,
  importLoaders: 2
}
```

**Comment by chengwangping** [comment]
@dawnmist  Sorry,  I still have the same problem after I am modified.
![image](https://user-images.githubusercontent.com/5220595/43623758-7771e0cc-9715-11e8-891f-54b905550e17.png)

![image](https://user-images.githubusercontent.com/5220595/43623865-321272f2-9716-11e8-8719-cbd2795b55e5.png)

![image](https://user-images.githubusercontent.com/5220595/43623790-a284ea8e-9715-11e8-94f8-65e6d0725e4c.png)

**Comment by chengwangping** [comment]
@dawnmist   hank you very much for your patience and help me.
