### ISSUE TITLE
Commons chunk plugin

### ISSUE THREAD

**Issue by chemitaxis** [timarney/react-app-rewired#29]
Hi, how can achieve use CommonsChunkPlugin? I have try that with no success:

**config-overrides.js:**

```
module.exports = function override(config, env) {


const webpack = require('webpack');

const { CommonsChunkPlugin } = webpack.optimize;

  var commonsChunkPluginCommon = new CommonsChunkPlugin({
    children: true,
    async: 'common',
    minChunks: 2,
  });
  var commonsChunkPluginVendor =  new CommonsChunkPlugin({
    children: true,
    async: 'vendor',
    minChunks: function(module) {
      // this assumes your vendor imports exist in the node_modules directory
      return module.context && module.context.indexOf('node_modules') !== -1;
    },
  });

  config.plugins.push(commonsChunkPluginCommon);
  config.plugins.push(commonsChunkPluginVendor);
  return config;
}
```

Thanks!

**Comment by timarney** [comment]
It's been a while since I've used that plugin.  Wondering if this could be a Webpack "1" vs Webpack 2 issue.  

The current CRA is still on Webpack "1".

Looking at a manual webpack config I did quite a while ago the setup this quite different to me.

Webpack "1"
https://github.com/timarney/react-setup/blob/master/webpack.config.js

**Comment by chemitaxis** [comment]
Wow... CRA is using webpack 1? Interesting... 🤔

**Comment by timarney** [comment]
0.10.0 which is in the master branch is on Webpack 2 but it hasn't release yet.

https://github.com/facebookincubator/create-react-app/milestone/23

**Comment by chemitaxis** [comment]
Ok!! Thanks ;) Have a nice day ;)

On Wed, 12 Apr 2017 at 19:11, Tim Arney <notifications@github.com> wrote:

0.10.0 which is in the master branch is on Webpack 2 but it hasn't release
yet.

https://github.com/facebookincubator/create-react-app/milestone/23

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/timarney/react-app-rewired/issues/29#issuecomment-293646150>,
or mute the thread
