### ISSUE TITLE
Support mobx-state-tree

### ISSUE THREAD

**Issue by assafb81** [timarney/react-app-rewired#292]
Do you plan to support `mobx-state-tree` package?

**Comment by timarney** [comment]
Can you outline what mobx-state-tree needs to be supported?

I haven't used it.

**Comment by timarney** [comment]
I believe you should be able to use it with no rewires.  The rewire for MobX was for using decorators which I think isn't needed these days i.e. https://twitter.com/mweststrate/status/966966306070323200?lang=en
