### ISSUE TITLE
Resolving aliases and paths

### ISSUE THREAD

**Issue by hundsim** [timarney/react-app-rewired#293]
I'm trying to integrate a [React Native UI](https://docs.nativebase.io/docs/GetStarted.html) kit for a CRA, and that requires doing these changes to webpack config:

`alias: {
  "react-native/Libraries/Renderer/shims/ReactNativePropRegistry": "react-native-web/dist/modules/ReactNativePropRegistry",
  "react-native": "react-native-web"
},
`

`{ test: /\.(js|jsx|mjs)$/, include: [ paths.appSrc, path.resolve(paths.appNodeModules, "native-base-shoutem-theme"), path.resolve(paths.appNodeModules, "react-navigation"), path.resolve(paths.appNodeModules, "react-native-easy-grid"), path.resolve(paths.appNodeModules, "react-native-drawer"), path.resolve(paths.appNodeModules, "react-native-safe-area-view"), path.resolve(paths.appNodeModules, "react-native-vector-icons"), path.resolve( paths.appNodeModules, "react-native-keyboard-aware-scroll-view" ), path.resolve(paths.appNodeModules, "react-native-web"), path.resolve(paths.appNodeModules, "react-native-tab-view"), path.resolve(paths.appNodeModules, "static-container") ], loader: require.resolve("babel-loader"), options: { cacheDirectory: true } }, `

I found [this suggestion](https://github.com/timarney/react-app-rewired/issues/167#issuecomment-350999274) for resolving aliases, but don't know how to add resolvers for the second code section. 

I'm sorry if this is super obvious but my shallow knowledge on the subject has gotten me stranded on this for a while now...

**Comment by timarney** [comment]
Not sure - first time I've heard of that lib.

Closing this as trying to keep only bugs / issues here vs config support.
