### ISSUE TITLE
Changing the default paths

### ISSUE THREAD

**Issue by ariofrio** [timarney/react-app-rewired#296]
I did this in my project's config-overrides.js:

```
const path = require('path');
const paths = require('react-scripts-ts/config/paths');

paths.appBuild = path.join(path.dirname(paths.appBuild), 'custombuilddir');
```

Seems to work well so far.

Do you see any caveats to doing this? Could modifying the create-react-app paths be a documented use case for react-app-rewired?

**Comment by timarney** [comment]
I've never tried if it works 👍 

Feel free to add a PR if that's something you would like to see documented.
