### ISSUE TITLE
How do I run my express server with react-app-rewired start?

### ISSUE THREAD

**Issue by tychovbh** [timarney/react-app-rewired#298]
I used the following tutorial to create workspaces:
https://medium.com/viewstools/how-to-use-yarn-workspaces-with-create-react-app-and-create-react-native-app-expo-to-share-common-ea27bc4bad62

The tutorial uses a combination of react-app-rewired and react-app-rewire-yarn-workspaces.

It was very easy to set this up. But now I want my react app to be rendered on server-side and make use of an express server.js file. Normally I would get this to work by changing my package.json:
```json
"start": "react-scripts start",
//to 
"start": "node server.js",
```

But since i already have to use:
```json
"start": "react-app-rewired start",
```
I have no idea to let `react-app-rewired start` trigger `node server.js` instead of `react-scripts start`.

Do you have an example of how to do this, if this is even possible?

**Comment by robchristian** [comment]
@timarney he didn't ask about SSR.

@tychovbh there is probably a way to run `server.js` as part of webpack `devServer`. For me I just used bash in my start command in `package.json`, like this:
```
  "scripts": {
    "start": "(cd backend; npm start &) && react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test",
    "eject": "react-app-rewired eject"
  },
```

**Comment by robchristian** [comment]
@tychovbh, actually, don't do that, you'll get a lot of rogue background processes you have to find and kill. Instead, do this in your `config-overrides.js`:
```
const { exec } = require('child_process');
exec(`node ${__dirname}/backend/server.js`);
```
