### ISSUE TITLE
Flow + babel-plugin-flow-react-proptypes does not work with Jest

### ISSUE THREAD

**Issue by comerc** [timarney/react-app-rewired#30]
```javascript
// config-overrides.js

const babelLoader = function (conf) {
  return conf.loader === 'babel'
}

function rewire(config, env) {
  const babelrc = config.module.loaders.find(babelLoader).query
  babelrc.plugins = [
    'flow-react-proptypes',
  ].concat(babelrc.plugins || [])
  return config
}

module.exports = rewire
```
I assume that the type conversion from Flow to PropTypes occurs after Jest.

**Comment by comerc** [comment]
babel-plugin-tcomb - the same problem

**Comment by jihchi** [comment]
Did you have example project for this issue?

**Comment by comerc** [comment]
how to reproduce:
```
$ git clone https://github.com/comerc/yobr/tree/Jest
$ yarn install
$ yarn test
```
![2017-04-20 20 01 59](https://cloud.githubusercontent.com/assets/1025241/25243004/3ec80cc0-2604-11e7-865d-fac8be770d49.png)

second terminal:
```
$ yarn start
```

http://localhost:3000/post/add
![2017-04-20 20 03 52](https://cloud.githubusercontent.com/assets/1025241/25243088/804e2d8c-2604-11e7-9a7d-1926efbf16b4.png)

Place of example error:
```jsx
// @flow
// src/components/PostForm/PostForm.js
type Props = {
  id: number, // instead of id?
}
```

**Comment by jihchi** [comment]
Warning came from your code.
Change [this line](https://github.com/comerc/yobr/blob/Jest/src/ducks/postForm.js#L138) from `id: null` to `id: 0` then your warning will disappear.

**Comment by comerc** [comment]
I know. It is special for you. I want to see this error in test.

**Comment by jihchi** [comment]
Oh, I see. Sorry, I didn't saw it.

**Comment by comerc** [comment]
Addition: `rewire` from `config-overrides.js` does not execute for command `yarn test` (i.e. `react-app-rewired test`).

**Comment by timarney** [comment]
Might be worth setting up a branch - eject see if you can get things working without any rewires (mod the webpack config, .babelrc direct).  This would narrow things down to an issue with this lib vs and issue with CRA or one of the plugins or webpack etc....

I haven't used babel-plugin-tcomb or flow-react-proptypes so can't assist much.

For the tests are you saying that it's not hitting the config-overrides or that it's not applying your modifications?

**Comment by comerc** [comment]
Pease see reconstruction.

#### Eject true case
```
$ git clone git@github.com:comerc/yobr.git
$ cd yobr
$ git checkout eject_Jest+Flow
$ yarn
$ yarn test
```
.babelrc
```json
{
  "presets": ["react-app"],
  "plugins": [
    "styled-jsx-postcss/babel",
    "flow-react-proptypes"
  ]
}
```
![2017-04-28 23 27 45](https://cloud.githubusercontent.com/assets/1025241/25546472/eab7f2e4-2c6b-11e7-9738-69a6ebb22a73.png)

#### Rewired wrong case
```
$ git checkout rewired_Jest+Flow
$ rm -rf node_modules/
$ yarn
$ yarn test
```
config-overrides.js
```javascript
const babelLoader = function (conf) {
  return conf.loader === 'babel'
}
function rewire(config, env) {
  const babelrc = config.module.loaders.find(babelLoader).query
  babelrc.plugins = [
    'styled-jsx-postcss/babel',
    'flow-react-proptypes',
  ].concat(babelrc.plugins || [])
  return config
}
module.exports = rewire
```
![2017-04-28 23 23 37](https://cloud.githubusercontent.com/assets/1025241/25546496/0376dd9a-2c6c-11e7-946d-a57937906a4e.png)

**Comment by timarney** [comment]
Okay from what I see the issue is in this file - 

https://github.com/timarney/react-app-rewired/blob/master/packages/react-app-rewired/config/jest/babelTransform.js

We currently don't expose a way push plugins into the Jest Babel config.

```
module.exports = babelJest.createTransformer({
  presets: [require.resolve('babel-preset-react-app')],
  plugins: customPlugins,
  babelrc: false
});
```
I think ideally we could allow for a .babelrc file.

I don't have much time right now, I will dig into this as time allows.  That said open to a PR as always.
