### ISSUE TITLE
update peer dependencies of react-app-rewire-mobx

### ISSUE THREAD

**Issue by leantide** [timarney/react-app-rewired#302]
npm gives following warning when using react-app-rewire-mobx:

npm WARN react-app-rewire-mobx@1.0.8 requires a peer of mobx@>=3.1.17 < 5 but none is installed. You must install peer dependencies yourself.

Can the peer dependencies in its [package.json](https://github.com/timarney/react-app-rewired/blob/master/packages/react-app-rewire-mobx/package.json) be updated to reflect compatibility with mobx@^5.0.0?

**Comment by timarney** [comment]
Feel free a submit a PR
