### ISSUE TITLE
Relay Modern

### ISSUE THREAD

**Issue by chris-guidry** [timarney/react-app-rewired#31]
Any plans to upgrade the Relay package to use the new Babel plugin "babel-plugin-relay" which supports Relay Modern?

**Comment by timarney** [comment]
@pasviegas thoughts?

**Comment by pasviegas** [comment]
As far as I understand we just need to update the babel-plugin. Can you send a PR?

**Comment by chris-guidry** [comment]
It might be worth creating a separate "react-app-rewire-relay-modern" package so that people can use the appropriate plugin depending on their version of Relay.

I decided to hold off on Relay Modern for now because react-router doesn't support it yet.

**Comment by timarney** [comment]
Sounds good - feel free to send a PR (just add under the packages dir following the format of the others).
