### ISSUE TITLE
Support for create-react-app v2?

### ISSUE THREAD

**Issue by milesrichardson** [timarney/react-app-rewired#315]
Re: https://github.com/facebook/create-react-app/issues/5103

Tomorrow `create-react-app` is releasing `v2`. 

Does react-app-rewired have a plan for supporting this? Has anyone tested it with the beta of v2?

**Comment by timarney** [comment]
See: https://github.com/timarney/react-app-rewired/issues/162#issuecomment-417872507

**Comment by milesrichardson** [comment]
Oops, somehow missed that. My bad. Sorry to hear you won't be working on this anymore. Thanks for all your work, you replaced my mess of patch.sh scripts. :)

**Comment by igauravsehrawat** [comment]
I have been using it with CRA 2.0, so far nothing broke.  I hope I am not missing anything.

**Comment by timarney** [comment]
The "core" seems to be fine - it's the plugins and utilities that break (if not updated).

For now it's still used behind the scenes here https://github.com/arackaf/customize-cra
