### ISSUE TITLE
Injecting typescript into CRA 2

### ISSUE THREAD

**Issue by jadbox** [timarney/react-app-rewired#317]
Hey folks, the TS community has been working with the forked version of CRA to add TS support, and it takes some work to keep it close to upstream. Any thoughts how Rewired could be used to add TS support to the regular CRA/2.0... is it possible? I haven't used Rewired myself yet.

Babel 7 does support TS now, so another option might be injecting a Babel config to CRA so that Babel is configured for Typescript. Is this possible to do with injectBabelPlugin? I don't see a way to just set a config option rather than adding a plugin.

**Comment by timarney** [comment]
This repo won't be supporting 2.0 but you can check out https://github.com/arackaf/customize-cra not sure what the TS plan will be.
