### ISSUE TITLE
How do I inline the style in React Component develement?

### ISSUE THREAD

**Issue by ycjcl868** [timarney/react-app-rewired#318]
I want to develop a react component, but it has two problems.
1. how to inline the style in js file?
2. how to remove the hash in build assets?

**Comment by timarney** [comment]
I would recommend you look at https://github.com/emotion-js/emotion for the CSS.

For the hash see:
https://github.com/timarney/react-app-rewired/issues/301

**Comment by ycjcl868** [comment]
`hash` problem I understand.
css , I mean, the less styles don't extract css files, just build styles in js file, not `css in js`

**Comment by timarney** [comment]
Try https://github.com/webpack-contrib/mini-css-extract-plugin maybe.

**Comment by ycjcl868** [comment]
@timarney 😅
