### ISSUE TITLE
react-scripts 1.0

### ISSUE THREAD

**Issue by subk** [timarney/react-app-rewired#32]
react-scripts 1.0 is coming with some great improvements. See [#2171](https://github.com/facebookincubator/create-react-app/issues/2172)
As it is moving to webpack 2,
is there any plan to support it in react-app-rewired ?

**Comment by jihchi** [comment]
Maybe we could use `react-script@rc` to develop next version of `react-app-rewired@1.0`?

**Comment by timarney** [comment]
Yes - when it gets released this repo will be updated to support.
Prep work is already in motion:
See - https://github.com/timarney/react-app-rewired/issues/26

**Comment by timarney** [comment]
1.0.1 is released and uses react-scripts 1.0.0
