### ISSUE TITLE
react-app-rewire-mobx does not work with latest babel 7.x

### ISSUE THREAD

**Issue by kamalnayankumar** [timarney/react-app-rewired#323]
react-app-rewire-mobx pluging is not working with the latest react-app-rewired. 
I need to use the below code in `config-overrides` to make it work.
```
module.exports = function override(config, env) {
    config = injectBabelPlugin( [
        "@babel/plugin-proposal-decorators",
        {
            "legacy": true
        }
    ],config);

    return config;
  };
```

**Comment by timarney** [comment]
See notes on the homepage.

Not supporting 2.0 directly.  Also see https://github.com/arackaf/customize-cra

**Comment by zibaandy** [comment]
Hi! I have this problem and do you change package.jason or create tsconfig.json?
