### ISSUE TITLE
react-scripts version leads to 'incorrect'

### ISSUE THREAD

**Issue by gmars** [timarney/react-app-rewired#327]
`"peerDependencies": {
    "react-scripts": "^1.0.14"
  },`
the react-app-rewired dependency react-scripts ^1.0.14 But the latest react-scripts is 2.0.5 so there will be a warning
`warning " > react-app-rewired@1.6.2" has incorrect peer dependency "react-scripts@^1.0.14".`

**Comment by dawnmist** [comment]
First paragraph in the react-app-rewired readme:

⚠️ ⚠️This repo doesn't support CRA 2.0 see: [2.0 Discussion](https://github.com/timarney/react-app-rewired/issues/162#issuecomment-417872507)

You can try [customize-cra](https://github.com/arackaf/customize-cra)

or you can try [react-scripts-rewired](https://github.com/marcopeg/create-react-app/blob/master/packages/react-scripts/README.md)
