### ISSUE TITLE
Tweaking the webpack config is not possible in certain cases.

### ISSUE THREAD

**Issue by Hurtak** [timarney/react-app-rewired#33]
I was taking a look at updating the LESS loaded for CRA 1.0 with Webpack 2 and I am starting to hit dead ends with the solution react-app-rewired provides

Take a look at the following line 
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/config/webpack.config.prod.js#L210

Or this line
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/config/webpack.config.prod.js#L231-L234

There are parts of the webpack config, that I would like to modify but can't because they are wrapper in functions that are evaluated.

I am not sure what the proper solution for this is, maybe have a way to replace exact lines of the config before running it? Maybe something like:

```js
reactAppRewired.replaceLine({
  start: 231,
  end: 234,
  newContent: `
    '>1%',
    4 versions',
    android >= 4
    ESR',
    ie < 9',
  `
})
```

But that seems fragile. Not sure what the correct solution is.

**Comment by timarney** [comment]
Ya way too fragile going down that road.  What do you need to do with that section of code?

**Comment by Hurtak** [comment]
Take the css loader and reuse it in less loader so when we import less files they have the same threatment as css (like autoprefixer and other stuff). This is currently posible as the ExtractTextPlugin.extract returns the loaders passed into it, but it breaks if we use relative publicPath because these loader options are not passed throu ExtractTextPlugin with this configuration https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/config/webpack.config.prod.js#L52-L55

**Comment by timarney** [comment]
Closing this - it's referenced in the less rewire.  We can resurface as needed.
