### ISSUE TITLE
用最新的create-react-app创建项目后，再使用react-app-rewire-mobx报错

### ISSUE THREAD

**Issue by tgy3300** [timarney/react-app-rewired#332]
我的环境信息：
node  v10.13.0
npm  v6.4.1
create-react-app  v2.1.1

安装流程：
1、create-react-app antd-demo
2、cd antd-demo
3、npm i -s react-app-rewire-less react-app-rewire-mobx react-app-rewired mobx mobx-react antd
4、package.json中相关依赖信息如下
`"dependencies": {
    "antd": "^3.10.3",
    "babel-plugin-import": "^1.11.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "mobx": "^5.5.2",
    "mobx-react": "^5.3.6",
    "react": "^16.6.0",
    "react-app-rewire-less": "^2.1.3",
    "react-app-rewire-mobx": "^1.0.9",
    "react-app-rewired": "^1.6.2",
    "react-dom": "^16.6.0",
    "react-scripts": "2.1.1"
  },
"scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test --env=jsdom",
    "eject": "react-app-rewired eject"
  }`
5、config-overrides.js文件代码如下
`const { injectBabelPlugin } = require('react-app-rewired');
const rewireLess = require('react-app-rewire-less');
const rewireMobX = require('react-app-rewire-mobx');

module.exports = function override(config, env) {
	config = injectBabelPlugin(
		[
			'import', {
				libraryName: 'antd', 
				libraryDirectory: 'es', 
				style: true 
			}
		],
		config,
	);

	// 主题配置
	let theme = {
		"@primary-color": "#ff5000",                         // 全局主色
		"@link-color": "#ff5000",                            // 链接色
		"@success-color": "#52c41a",                         // 成功色
		"@warning-color": "#faad14",                          // 警告色
		"@error-color": "#f5222d",                           // 错误色
		"@font-size-base": "14px",                            // 主字号
		"@heading-color": "rgba(0, 0, 0, .85)",               // 标题色
		"@text-color": "rgba(0, 0, 0, .65)",                 // 主文本色
		"@text-color-secondary": "rgba(0, 0, 0, .45)",       // 次文本色
		"@disabled-color": "rgba(0, 0, 0, .25)",            // 失效色
		"@border-radius-base": "4px",                       // 组件/浮层圆角
		"@border-color-base": "#d9d9d9",                    // 边框色
		"@box-shadow-base": "0 2px 8px rgba(0, 0, 0, .15)"  // 浮层阴影
	};

	config = rewireLess.withLoaderOptions({
		modifyVars: theme,
		javascriptEnabled: true
	})(config, env);

	config = rewireMobX(config, env);

	return config;
};`
6、运行项目：npm start

错误提示如下：
`./src/index.js
Error: The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean. If you are migrating from Babylon/Babel 6 or want to use the old decorators proposal, you should use the 'decorators-legacy' plugin instead of 'decorators'.`

求助，这是什么原因呢？如何才能解决呢，我不想使用 npm run eject 来释放 create-react-app 脚手架配置，只想用 react-app-rewire-mobx 工具让react项目能识别mobx的装饰器.

**Comment by baian1** [comment]
试试在config-overrides中加入
config = injectBabelPlugin(["@babel/plugin-proposal-decorators",{legacy:true}],config);
babel7.0后修饰符转换改用@babel/plugin-proposal-decorators

**Comment by tgy3300** [comment]
> 试试在config-overrides中加入
> config = injectBabelPlugin(["@babel/plugin-proposal-decorators",{legacy:true}],config);
> babel7.0后修饰符转换改用@babel/plugin-proposal-decorators

使用了你的方法，但现在提示另一个错误
`./src/index.js
Error: Cannot use the decorators and decorators-legacy plugin together`

现在的 config-overrides 代码如下
`const { injectBabelPlugin } = require('react-app-rewired');
const rewireLess = require('react-app-rewire-less');
const rewireMobX = require('react-app-rewire-mobx');

module.exports = function override(config, env) {

	config = injectBabelPlugin(["@babel/plugin-proposal-decorators", { legacy: true }], config);

	config = injectBabelPlugin(
		[
			'import',
			{
				libraryName: 'antd',
				libraryDirectory: 'es',
				style: true
			}
		],
		config,
	);

	// 主题配置
	let theme = {
		"@primary-color": "#ff5000",                         // 全局主色
		"@link-color": "#ff5000",                            // 链接色
		"@success-color": "#52c41a",                         // 成功色
		"@warning-color": "#faad14",                          // 警告色
		"@error-color": "#f5222d",                           // 错误色
		"@font-size-base": "14px",                            // 主字号
		"@heading-color": "rgba(0, 0, 0, .85)",               // 标题色
		"@text-color": "rgba(0, 0, 0, .65)",                 // 主文本色
		"@text-color-secondary": "rgba(0, 0, 0, .45)",       // 次文本色
		"@disabled-color": "rgba(0, 0, 0, .25)",            // 失效色
		"@border-radius-base": "4px",                       // 组件/浮层圆角
		"@border-color-base": "#d9d9d9",                    // 边框色
		"@box-shadow-base": "0 2px 8px rgba(0, 0, 0, .15)"  // 浮层阴影
	};

	config = rewireLess.withLoaderOptions({
		modifyVars: theme,
		javascriptEnabled: true
	})(config, env);

	config = rewireMobX(config, env);

	return config;
};`

**Comment by baian1** [comment]
const rewireMobX = require('react-app-rewire-mobx');这个也是导入修饰符，不过是老版的，你看看他的文件就知道了

**Comment by tgy3300** [comment]
> const rewireMobX = require('react-app-rewire-mobx');这个也是导入修饰符，不过是老版的，你看看他的文件就知道了，删掉他

可以了，非常感谢

**Comment by giggioz** [comment]
Had the same issue, and i had to figure out what was going on because i do not speak chinese :)

As far as i know the react-app-rewired does not work anymore with babel, so you need to inject manually the plugin you need. Like this

```
const { injectBabelPlugin } = require('react-app-rewired')

/* config-overrides.js */
module.exports = function override(config) {
  config = injectBabelPlugin(["@babel/plugin-proposal-decorators", {legacy:true}], config);
  return config
}
```

**Comment by tgy3300** [comment]
> Had the same issue, and i had to figure out what was going on because i do not speak chinese :)
> 
> As far as i know the react-app-rewired does not work anymore with babel, so you need to inject manually the plugin you need. Like this
> 
> ```
> const { injectBabelPlugin } = require('react-app-rewired')
> 
> /* config-overrides.js */
> module.exports = function override(config) {
>   config = injectBabelPlugin(["@babel/plugin-proposal-decorators", {legacy:true}], config);
>   return config
> }
> ```

非常感谢，已经解决
