### ISSUE TITLE
react-app-rewired breaks w/ react-scripts 2.1.2

### ISSUE THREAD

**Issue by bugzpodder** [timarney/react-app-rewired#343]
react-scripts 2.1.2+ has only one webpack.config.js now (prod + dev are configs are combined into one).  This breaks react-app-rewired because it looks for webpack.config.prod.js

I know this module is no longer maintained, but up to this point (react-scripts 2.1.1 or earlier) it still allows you to manually modify parts of the config without issues.  Just a heads up for anymore who may ran into this issue.

**Comment by bugzpodder** [comment]
https://github.com/arackaf/customize-cra seems to rely on this package as well

**Comment by xuanhoa88** [comment]
I can resolve this issue with update source code for 2 files as below:

`start.js`
```process.env.NODE_ENV = process.env.NODE_ENV || "development";

const paths = require("./utils/paths");
const overrides = require('../config-overrides');
const webpackConfigPath = paths.scriptVersion + "/config/webpack.config";
const devServerConfigPath = paths.scriptVersion + "/config/webpackDevServer.config.js";

// load original configs
const configFactory = require(webpackConfigPath);
const devServerConfig = require(devServerConfigPath);

// override config in memory
require.cache[require.resolve(webpackConfigPath)].exports =
  (NODE_ENV) => overrides.webpack(configFactory(NODE_ENV), process.env.NODE_ENV || NODE_ENV);

require.cache[require.resolve(devServerConfigPath)].exports =
  overrides.devServer(devServerConfig, process.env.NODE_ENV);

// run original script
require(paths.scriptVersion + "/scripts/start");```

`build.js`
```process.env.NODE_ENV = 'production';

const paths = require('./utils/paths');
const overrides = require('../config-overrides');
const webpackConfigPath = paths.scriptVersion + "/config/webpack.config";

// load original config
const configFactory = require(webpackConfigPath);

// override config in memory
require.cache[require.resolve(webpackConfigPath)].exports =
  (NODE_ENV) => overrides.webpack(configFactory(NODE_ENV), process.env.NODE_ENV || NODE_ENV);

// run original script
require(paths.scriptVersion + '/scripts/build');```

**Comment by vdfor** [comment]
https://github.com/timarney/react-app-rewired/pull/344

**Comment by AndyOGo** [comment]
@bugzpodder
Just switch to craco JS (it's crafted for CRA V2)
https://github.com/sharegate/craco

**Comment by hsz** [comment]
@AndyOGo Currently also broken with CRA v2.1.2: https://github.com/sharegate/craco/issues/61

**Comment by alexchen1875** [comment]
> @AndyOGo Currently also broken with CRA v2.1.2: [sharegate/craco#61](https://github.com/sharegate/craco/issues/61)

yep, i got it  in CRA V2.1.2 .

is there some solutions?



![image](https://user-images.githubusercontent.com/3668637/50537474-06986d80-0b9b-11e9-8e25-636dd595e7bf.png)

**Comment by hsz** [comment]
@alejandronanez simply stick to the `v2.1.1` and wait for fix. There is no other workaround possible here.

**Comment by alexchen1875** [comment]
oh...god.
in CRA 2.1.3  also got this problem .:(

**Comment by AndyOGo** [comment]
seems rescripts is working:
https://github.com/rescripts/rescripts

**Comment by timarney** [comment]
#346 is now merged.  

You can test using yarn add react-app-rewired@2.0.2-next.0

Next steps:
- Remove the built in rewires i.e. getLoader 
- Update the docs 
- Release a major version with the changes

**Comment by timarney** [comment]
Just pushed 2.0.1 to npm thanks @tiffon for the PR + testing.
