### ISSUE TITLE
injectBabelPlugin is broken in react-app-rewired 2.0.1

### ISSUE THREAD

**Issue by alexchen1875** [timarney/react-app-rewired#348]
i update react-app-rewired 2.0.1  to fixed #343 
but  `injectBabelPlugin ` cannot work.

env:
```
"react-app-rewired": "^2.0.1",
"react-scripts": "^2.1.3"
"react": "^16.7.0",
```

config-overrides.js 

```
/** @format */

const {injectBabelPlugin} = require('react-app-rewired');
const rewireLess = require('react-app-rewire-less');
const rewireEslint = require('react-app-rewire-eslint');

module.exports = function override(config, env) {
    config = injectBabelPlugin(
        ['import', {libraryName: 'antd', libraryDirectory: 'es', style: true}],
        config,
    );
    config = rewireLess.withLoaderOptions({
        modifyVars: {
            '@table-padding-vertical': '10px',
            '@table-padding-horizontal': '10px',
            '@form-item-margin-bottom': '10px',
        },
        javascriptEnabled: true,
    })(config, env);
    config = rewireEslint(config, env);
    return config;
};


```

i got this  error 

```

injectBabelPlugin is not a function
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! retail-platform@0.1.0 start-js: `react-app-rewired start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the retail-platform@0.1.0 start-js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AlexChen\AppData\Roaming\npm-cache\_logs\2019-01-07T04_44_08_739Z-debug.log
ERROR: "start-js" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! retail-platform@0.1.0 start: `npm-run-all -p watch-css start-js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the retail-platform@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AlexChen\AppData\Roaming\npm-cache\_logs\2019-01-07T04_44_08_970Z-debug.log
```

well.
how to fixed this ?

**Comment by luotingv1** [comment]
我也遇到这个问题 mark一下

**Comment by hsz** [comment]
From README:

> Version 2.0 removes the rewire helper functions

All helper functions:

- `injectBabelPlugin`
- `compose`
- `getBabelLoader`
- `getLoader`
- `babelLoaderMatcher`
- `loaderNameMatches`

 have been removed with commit https://github.com/timarney/react-app-rewired/commit/08486022685a5429ff3224367d89ba5acd79bde9

**Comment by timarney** [comment]
Checkout something like customize-cra for helpers which uses this repo as a dependancy https://github.com/arackaf/customize-cra#addbabelpluginsplugins .

**Comment by qxchen6** [comment]
# HERE IS THE SOLUTION !

## WHY IT HAPPENED ? 
the new version of `react-app-rewired` removed all the methods like `injectBabelPlugin` .
these methods are move into a new package called 'customize-cra' , which depends on `react-app-rewired@2.x` .

## what should i do in and-design ?
make sure u installed  'customize-cra' and `react-app-rewired@2.x`
make sure u installed 'less' and 'less-loader'

and then here is the `config-overrides.js`

`
const {
  override,
  fixBabelImports,
  addLessLoader,
} = require("customize-cra");


module.exports = override(
  fixBabelImports("import", {
    libraryName: "antd", libraryDirectory: "es", style: true // change importing css to less
  }),
  addLessLoader({
    javascriptEnabled: true,
    modifyVars: { "@primary-color": "#1DA57A" }
  })
);
`

**Comment by sdli** [comment]
> # HERE IS THE SOLUTION !
> ## WHY IT HAPPENED ?
> the new version of `react-app-rewired` removed all the methods like `injectBabelPlugin` .
> these methods are moved into a new package called 'customize-cra' , which depends on `react-app-rewired@2.x` .
> 
> ## what should i do in and-design ?
> make sure u installed 'customize-cra' and `react-app-rewired@2.x`
> make sure u installed 'less' and 'less-loader'
> 
> and then here is the `config-overrides.js`
> 
> ```
> const {
>   override,
>   fixBabelImports,
>   addLessLoader,
> } = require("customize-cra");
> 
> 
> module.exports = override(
>   fixBabelImports("import", {
>     libraryName: "antd", libraryDirectory: "es", style: true // change importing css to less
>   }),
>   addLessLoader({
>     javascriptEnabled: true,
>     modifyVars: { "@primary-color": "#1DA57A" }
>   })
> );
> ```

Does your cssModules  work?

**Comment by phungrk** [comment]
My config-overrides.js (I'm using antd-mobile-samples/create-react-app/ boilerplate)

```
const {
  override,
  fixBabelImports,
  addLessLoader,
} = require("customize-cra");


module.exports = override( 
  fixBabelImports("babel-plugin-import", {
    libraryName: "antd-mobile",
    style: true
  }),
  addLessLoader({
    ident: 'postcss'
  })
);
```

**Comment by dance2die** [comment]
> # HERE IS THE SOLUTION !
> ## WHY IT HAPPENED ?
> the new version of `react-app-rewired` removed all the methods like `injectBabelPlugin` .
> these methods are moved into a new package called 'customize-cra' , which depends on `react-app-rewired@2.x` .
> 
> ## what should i do in and-design ?
> make sure u installed 'customize-cra' and `react-app-rewired@2.x`
> make sure u installed 'less' and 'less-loader'
> 
> and then here is the `config-overrides.js`
> 
> ```
> const {
>   override,
>   fixBabelImports,
>   addLessLoader,
> } = require("customize-cra");
> 
> 
> module.exports = override(
>   fixBabelImports("import", {
>     libraryName: "antd", libraryDirectory: "es", style: true // change importing css to less
>   }),
>   addLessLoader({
>     javascriptEnabled: true,
>     modifyVars: { "@primary-color": "#1DA57A" }
>   })
> );
> ```

If you have a failing build/deployment, make sure that you install `less` & `less-loader`.

https://github.com/arackaf/customize-cra#addlessloaderloaderoptions

**Comment by crazySadSoul** [comment]
i want to use viewport ,how to config it . react-app-rewire-postcss.

**Comment by nutrimax1987** [comment]
what about less modules and typescript ?

**Comment by nutrimax1987** [comment]
Figured it Out . if some needs 'create-react-app' with support less modules and typescript 
https://github.com/nutrimax1987/create-react-app-ts-antd-less

**Comment by jimmyromanticdevil** [comment]
> # HERE IS THE SOLUTION !
> ## WHY IT HAPPENED ?
> the new version of `react-app-rewired` removed all the methods like `injectBabelPlugin` .
> these methods are moved into a new package called 'customize-cra' , which depends on `react-app-rewired@2.x` .
> 
> ## what should i do in and-design ?
> make sure u installed 'customize-cra' and `react-app-rewired@2.x`
> make sure u installed 'less' and 'less-loader'
> 
> and then here is the `config-overrides.js`
> 
> ```
> const {
>   override,
>   fixBabelImports,
>   addLessLoader,
> } = require("customize-cra");
> 
> 
> module.exports = override(
>   fixBabelImports("import", {
>     libraryName: "antd", libraryDirectory: "es", style: true // change importing css to less
>   }),
>   addLessLoader({
>     javascriptEnabled: true,
>     modifyVars: { "@primary-color": "#1DA57A" }
>   })
> );
> ```

Thank you it works like a charm.

**Comment by packetstracer** [comment]
> # HERE IS THE SOLUTION !
> ## WHY IT HAPPENED ?
> the new version of `react-app-rewired` removed all the methods like `injectBabelPlugin` .
> these methods are moved into a new package called 'customize-cra' , which depends on `react-app-rewired@2.x` .
> 
> ## what should i do in and-design ?
> make sure u installed 'customize-cra' and `react-app-rewired@2.x`
> make sure u installed 'less' and 'less-loader'
> 
> and then here is the `config-overrides.js`
> 
> ```
> const {
>   override,
>   fixBabelImports,
>   addLessLoader,
> } = require("customize-cra");
> 
> 
> module.exports = override(
>   fixBabelImports("import", {
>     libraryName: "antd", libraryDirectory: "es", style: true // change importing css to less
>   }),
>   addLessLoader({
>     javascriptEnabled: true,
>     modifyVars: { "@primary-color": "#1DA57A" }
>   })
> );
> ```

Thanks for the solution, but I'm not getting it to work. Anyone can help or give me a hint about how to solve the issue?

- Create React App 4.0.0
- React App Rewired 2.1.8
- Customize CRA 1.0.0
- Postcss 8.2.10
- Less 4.1.1
- Less Loader 8.1.1
- Ant Design
- Tailwind CSS

When running yarn start, I get the following error:

```bash
Failed to compile.

./src/entities/scratchpad/theme/antd/custom-theme.less (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-8-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-8-3!./node_modules/less-loader/dist/cjs.js??ref--5-oneOf-8-4!./src/entities/scratchpad/theme/antd/custom-theme.less)
TypeError: this.getOptions is not a function
```

I have Tailwind installed and running so I guess that de postcss-loader is not the problem. I've read that the problem maybe with less-loader version, but cannot get ant version of it working.

Anyone knows why may be this happening and how to solve it?

**Comment by instantlinux** [comment]
This is clear as mud to us backend engineers just starting out with React, iterating on 3 or 4 years' worth of hackish workarounds to fundamental problems with `create-react-app`. I've been googling for hours. How do I replace this configuration with a similarly-brief one that actually works, with the goal of publishing my jsx-format component classes to npmjs.com?
```
module.exports = {
  webpack: function(config, env) {
      if (env !== 'production') {
	  return config;
      }
      config = injectBabelPlugin(['@babel/plugin-transform-react-jsx'])
      return config;
  }
};
```

**Comment by instantlinux** [comment]
A solution -- all the above is clear as mud to us backend engineers just starting out with React, iterating on 3 or 4 years' worth of hackish workarounds to fundamental problems with `create-react-app`. I've been googling for hours. How do I replace this configuration with a similarly-brief one that actually works, with the goal of publishing my jsx-format component classes to npmjs.com?
```
module.exports = {
  webpack: function(config, env) {
      if (env !== 'production') {
	  return config;
      }
      config = injectBabelPlugin(['@babel/plugin-transform-react-jsx'])
      return config;
  }
};
```
Here's my answer (hopefully helps others who follow the same google rabbit-hole):
```
const { override, addExternalBabelPlugins } = require('customize-cra')

module.exports = override(...addExternalBabelPlugins(
    '@babel/plugin-transform-react-jsx'
  )
);
```
You'll need these two items in your package.json `devDependencies`:
```
  "devDependencies": {
    "@babel/plugin-transform-react-jsx": "^7.14.3",
    "customize-cra": "^1.0.0",
    ...
  }
```
