### ISSUE TITLE
The NODE_ENV environment variable is required but was not specified

### ISSUE THREAD

**Issue by themre** [timarney/react-app-rewired#35]
I tried latest release of app-rewired and CRA and when starting I get 
`The NODE_ENV environment variable is required but was not specified`. I used Mobx rewire. Anyone else having trouble?

**Comment by themre** [comment]
ok, I found out that I need to specify .env file and add NODE_ENV=development or whatever I like.

**Comment by themre** [comment]
but this should be somehow handled within app-rewired, right? because normal CRA works without it.

**Comment by timarney** [comment]
Just merged a PR from @haydnhkim which should fix this issue if not we'll re-open.
