### ISSUE TITLE
config-override.js is not under rootdDir src

### ISSUE THREAD

**Issue by lidaof** [timarney/react-app-rewired#354]
Hi,

my tsconfig.json tells this error, is there any fix for this?
Thanks.

**Comment by timarney** [comment]
https://github.com/timarney/react-app-rewired#2-create-a-config-overridesjs-file-in-the-root-directory

**Comment by lidaof** [comment]
Hi @timarney , thanks for your reply...sorry I didn't get what do you mean by the link?
I meant the error from my tsconfig.json file:

![image](https://user-images.githubusercontent.com/102806/51415383-44a20500-1b3b-11e9-9118-69b44898b438.png)
