### ISSUE TITLE
How to run test only once?

### ISSUE THREAD

**Issue by Vadorequest** [timarney/react-app-rewired#364]
I'm wondering how can I run the equivalent of

        "test": "react-app-rewired test --env=jsdom"

But only once, this enters watch mode, and I want to run it once for automated deployment. Any hint would be appreciated! :)

**Comment by dawnmist** [comment]
Try setting CI to true (stands for "continuous integration", used to state that the code is being tested by the server due to a new commit so should only run all tests once).

See https://facebook.github.io/create-react-app/docs/running-tests#on-your-own-environment

**Comment by dawnmist** [comment]
Or try using the `--no-watch` flag as mentioned in the section immediately before the one I linked to:
```
"test": "react-app-rewired test --env=jsdom --no-watch"
```
(Note: if you are using CRA 2.x, the default jest environment is jsdom now, so the `--env=jsdom` is no longer required).

**Comment by Vadorequest** [comment]
Thanks @dawnmist , I tried but it didn't work as expected:

    react-app-rewired test --env=jsdom --no-watch

This runs in watch mode regardless. Maybe my version is too old? I think it's one year old, haven't changed it since the initial project setup.

**Comment by leifdejong** [comment]
@Vadorequest please use `--ci`.

**Comment by Vadorequest** [comment]
Thanks @leifdejong !

`CI=true react-app-rewired test --env=jsdom` **worked**, while `react-app-rewired test --env=jsdom --ci` _did not_.

**Comment by andrewjboyd** [comment]
On Windows, I had to use
`"ci-test": "set CI=true && react-app-rewired test --env=jsdom --testResultsProcessor=\"./node_modules/jest-junit-reporter\"",`
