### ISSUE TITLE
Async compatibility

### ISSUE THREAD

**Issue by tonai** [timarney/react-app-rewired#365]
I need to inject a plugin in the react config, but the module returns me a promise that resolve to the plugin.

I try to use `async` / `await` but it crashes when I start the app.

Here is my `config-overrides.js` file:
```js
module.exports = {
  webpack: async function (config, env) {
    config.plugins.push(await someAsyncPlugin());
    return config;
  }
}
```

Is there currently a way to achieve that ?

Thanks.

**Comment by leifdejong** [comment]
@tonai can you wait for the promise to resolve and then return? IE:

```
someAsyncPlugin().then((plugin) => {
   config.plugins.push(plugin);
    return config;
});
```

**Comment by tonai** [comment]
Thanks for your reply @leifdejong .
The following seems to work fine:
```js
module.exports = (async function() {
  const plugin = await someAsyncPlugin();
  return {
    webpack: function (config, env) {
      config.plugins.push(plugin);
      return config;
    }
  }
})();
```

**Comment by tonai** [comment]
In fact it does not solve the issue...
It do not crash, but my config is not taken into account.

**Comment by timarney** [comment]
If there's any more activity here we can re-open as need be but this isn't really a repo issue so closing.

**Comment by jordanrigo** [comment]
@tonai  Hello there,

Could you manage to solve this issue?

Thank you!
