### ISSUE TITLE
Combining react-app-rewire-hot-loader and customize-cra

### ISSUE THREAD

**Issue by gshen92** [timarney/react-app-rewired#366]
Hi, recently just switched over to v2.0.1 in order to resolve some issues I was encountering with "react-app-rewired build" and the webpack.config.js file. However, I realized this was now causing some issues with the "injectBabelPlugin" helper. 

Is there a way on combining 'customize-cra' and 'react-app-rewire-hot-loader' in the config-overrrides.js?

Here is the code for react-app-rewire-hot-loader:

**module.exports = function override(config, env) {
  config = rewireReactHotLoader(config, env);
  return config;
}**

and here is what I have for customize-cra:

**module.exports = override(
  fixBabelImports("import", {
    libraryName: "antd", libraryDirectory: "es", style: true // change importing css to less
  }),
  addLessLoader({
    javascriptEnabled: true,
    modifyVars: { "@primary-color": "#1DA57A" }
  })
);**

I am having some trouble combining the two to work together.

**Comment by youngauto** [comment]
try this:
const path = require('path');
const { override, fixBabelImports, addLessLoader, addWebpackAlias } = require('customize-cra');
const rewireReactHotLoader = require('react-app-rewire-hot-loader')
const fixedHot = () => config => {
  config = rewireReactHotLoader(config, process.env);
  return config;
};
module.exports = {
  webpack: override(
    fixBabelImports('import', {
      libraryName: 'antd',
      libraryDirectory: 'es',
      style: true,
    }),
    addLessLoader({
      javascriptEnabled: true,
      modifyVars: { 
        // '@primary-color': '#1DA57A' 
      },
    }),
    addWebpackAlias({
      '@': path.resolve(__dirname, 'src/')
    }),
    fixedHot(),
  )
};

**Comment by steenole** [comment]
I have the same issue. Any solutions?

**Comment by timarney** [comment]
Closing this - as it doesn't sound like a code bug with this repo.

**Comment by esc-rtn** [comment]
If anyone lands here, and needs a solution.. https://github.com/arackaf/customize-cra/issues/54
