### ISSUE TITLE
Can i use a custom host name?

### ISSUE THREAD

**Issue by hscspring** [timarney/react-app-rewired#368]
for example:

`HOST=myproj.com react-app-rewired start`

**Comment by mcacek** [comment]
It sounds like you're talking about customizing the webpack dev server.  If thats the case then you can just tap into the configuration using `config-overrides.js`. 

```
module.exports = {
	devServer: configFn => {
		return (proxy, allowedHost) => {
			const config = configFn(proxy, allowedHost);
			config.host = 'myhost.com';

			return config;
		}
	}
};
```

**Comment by hscspring** [comment]
many thanks, i'll try.
