### ISSUE TITLE
build.js not respecting NODE_PATH

### ISSUE THREAD

**Issue by hassanbazzi** [timarney/react-app-rewired#37]
in `scripts/build.js`

```
const webpackConfig = paths.scriptVersionDir + '/config/webpack.config.prod';
```

`paths.scriptVersionDir` assumes that node_modules is in that directory which breaks everything. :( 

This should respect `NODE_PATH` just like everything else.

**Comment by timarney** [comment]
I'm not familiar with the usage of NODE_PATH can you suggest what updates would be needed for this file https://github.com/timarney/react-app-rewired/blob/master/packages/react-app-rewired/config/paths.js while maintaining the ability to use custom scripts?  

Happy to accept a PR.

**Comment by hassanbazzi** [comment]
https://github.com/timarney/react-app-rewired/pull/40

**Comment by timarney** [comment]
Thanks - Published as 1.0.3.

**Comment by hassanbazzi** [comment]
Thank you so much!

**Comment by timarney** [comment]
1.0.4
