### ISSUE TITLE
rewired1.x时可直接修改路径，升级为2.x后请问该用什么函数去修改路径呢？

### ISSUE THREAD

**Issue by wang5909912** [timarney/react-app-rewired#377]
![image](https://user-images.githubusercontent.com/26141772/54893975-6761e880-4ef3-11e9-81ee-2e236af929d0.png)
  
![image](https://user-images.githubusercontent.com/26141772/54893991-75176e00-4ef3-11e9-9ea8-5e27254765c6.png)

rewired1.x时可直接获取path修改路径，升级为2.x后请问该用什么函数去修改路径呢？

"
When rewired1.x can directly modify the path, after upgrading to 2.x, what function should I use to modify the path?"

**Comment by timarney** [comment]
Closing this as no one has picked it up.
