### ISSUE TITLE
ServiceWorker is not updating, goes to skipwaiting in react app

### ISSUE THREAD

**Issue by usmanhafeez147** [timarney/react-app-rewired#379]
Please help me out in a very serious issue. When I make a new production build of react app, new services worker installs but goes to skipwaiting state. So I have to hard reset cache on every build that is not good on live site. I can't tell to every client, "please clear your cache to see latest". If i remove registerServiceWorker() from index file then build production do not detect my routes so its redirect to 404. issue in react revired app build

**Comment by dawnmist** [comment]
1. Does the same issue occur if built using react-scripts instead of building with react-app-rewired?
2. What is the content of your config-overrides.js?
3. Are you able to provide a sample repository that demonstrates/reproduces the issue?

It's not an issue we've seen/heard of before, so without some detail on what you're doing or preferably something to use to reproduce/test the issue with it's not possible to investigate it further.

**Comment by usmanhafeez147** [comment]
I tried with react-scripts it destroyed my overall dependencies. I installed dependencies again. 
I m posting my config-overrides.js code here
`const path = require('path');
const AntDesignThemePlugin = require('antd-theme-webpack-plugin');
const {override, fixBabelImports, addLessLoader} = require('customize-cra')


const options = {
  stylesDir: path.join(__dirname, './src/styles'),
  antDir: path.join(__dirname, './node_modules/antd'),
  varFile: path.join(__dirname, './src/styles/variables.less'),
  mainLessFile: path.join(__dirname, './src/styles/wieldy.less'),
  themeVariables: [
    '@primary-color',
    '@secondary-color',
    '@text-color',
    '@heading-color',
    '@nav-dark-bg',
    '@header-text-color',
    '@layout-header-background',
    '@layout-footer-background',
    '@nav-dark-text-color',
    '@hor-nav-text-color',
    '@nav-header-selected-text-color'
  ],
  indexFileName: 'index.html',
  generateOnce: false // generate color.less on each compilation
};


const overrideProcessEnv = value => config => {
  config.resolve.modules = [
    path.join(__dirname, 'src')
  ].concat(config.resolve.modules);
  config.plugins.push(new AntDesignThemePlugin(options));
  return config;
};

module.exports = override(
  addLessLoader({
    javascriptEnabled: true,
    modifyVars: {
      '@primary-color': '#038fde',
      '@secondary-color': '#fa8c16',
      '@text-color': '#545454',
      '@heading-color': '#535353',
      '@nav-dark-bg': '#003366',
      '@header-text-color': '#262626',
      '@layout-header-background': '#fefefe',
      '@layout-footer-background': '#fffffd',
      '@nav-dark-text-color': '#038fdd',
      '@hor-nav-text-color': '#fffffd',
      '@nav-header-selected-text-color': '#fdbe33'
    }
  }),
  overrideProcessEnv({
    VERSION: JSON.stringify(require('./package.json').version),
  })
);
`

**Comment by usmanhafeez147** [comment]
let me also push my service-worker.js file also
`// In production, we register a service worker to serve assets from local cache.

// This lets the app load faster on subsequent visits in production, and gives
// it offline capabilities. However, it also means that developers (and users)
// will only see deployed updates on the "N+1" visit to a page, since previously
// cached resources are updated in the background.

// To learn more about the benefits of this model, read https://goo.gl/KwvDNy.
// This link also includes instructions on opting out of this behavior.

const isLocalhost = Boolean(
  window.location.hostname === 'localhost' ||
  // [::1] is the IPv6 localhost address.
  window.location.hostname === '[::1]' ||
  // 127.0.0.1/8 is considered localhost for IPv4.
  window.location.hostname.match(
    /^127(?:\.(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}$/
  )
);

export default function register() {
  // console.log("navigator", navigator);
  if (process.env.NODE_ENV === 'production' && 'serviceWorker' in navigator) {
    // The URL constructor is available in all browsers that support SW.
    const publicUrl = new URL(process.env.PUBLIC_URL, window.location);
    console.log("publicUrl",publicUrl);
    console.log("window origin", window.location.origin);
    if (publicUrl.origin !== window.location.origin) {
      // Our service worker won't work if PUBLIC_URL is on a different origin
      // from what our page is served on. This might happen if a CDN is used to
      // serve assets; see https://github.com/facebookincubator/create-react-app/issues/2374
      return;
    }

    window.addEventListener('load', () => {
      const swUrl = `${process.env.PUBLIC_URL}/service-worker.js`;

      if (isLocalhost) {
        // This is running on localhost. Lets check if a service worker still exists or not.
        checkValidServiceWorker(swUrl);

        // Add some additional logging to localhost, pointing developers to the
        // service worker/PWA documentation.
        navigator.serviceWorker.ready.then(() => {
          console.log(
            'This web app is being served cache-first by a service ' +
            'worker. To learn more, visit https://goo.gl/SC7cgQ'
          );
        });
      } else {
        // Is not local host. Just register service worker
        registerValidSW(swUrl);
      }
    });
  } else {
    // alert("local env")
  }
}

function registerValidSW(swUrl) {
  navigator.serviceWorker
    .register(swUrl)
    .then(registration => {
      registration.onupdatefound = () => {
        const installingWorker = registration.installing;
        installingWorker.onstatechange = () => {
          if (installingWorker.state === 'installed') {
            if (navigator.serviceWorker.controller) {
              // At this point, the old content will have been purged and
              // the fresh content will have been added to the cache.
              // It's the perfect time to display a "New content is
              // available; please refresh." message in your web app.
              console.log('New content is available; please refresh.');
              // alert('New content is available; please refresh.');
              // navigator.serviceWorker.ready.then(registration => {
              //   registration.unregister().then(() => {
              //     window.location.reload();
              //   });
              // });
            } else {
              // At this point, everything has been precached.
              // It's the perfect time to display a
              // "Content is cached for offline use." message.
              console.log('Content is cached for offline use.');
              // alert("hello content is cached for offline use");
              // navigator.serviceWorker.ready.then(registration => {
              //   registration.unregister().then(() => {
              //     window.location.reload();
              //   });
              // });
            }
          }
        };
      };
    })
    .catch(error => {
      console.error('Error during service worker registration:', error);
    });
}

function checkValidServiceWorker(swUrl) {
  // Check if the service worker can be found. If it can't reload the page.
  fetch(swUrl)
    .then(response => {
      // Ensure service worker exists, and that we really are getting a JS file.
      if (
        response.status === 404 ||
        response.headers.get('content-type').indexOf('javascript') === -1
      ) {
        // No service worker found. Probably a different app. Reload the page.
        navigator.serviceWorker.ready.then(registration => {
          registration.unregister().then(() => {
            window.location.reload();
          });
        });
      } else {
        // Service worker found. Proceed as normal.
        registerValidSW(swUrl);
      }
    })
    .catch(() => {
      console.log(
        'No internet connection found. App is running in offline mode.'
      );
    });
}

export function unregister() {
  if ('serviceWorker' in navigator) {
    navigator.serviceWorker.ready.then(registration => {
      registration.unregister();
    });
  }
}
`

**Comment by usmanhafeez147** [comment]
here is my index.js file

`
   import React from "react";
import ReactDOM from "react-dom";

import NextApp from './NextApp';
// import {registerServiceWorker, unregister} from './registerServiceWorker';
import registerServiceWorker from './registerServiceWorker';
// Add this import:
import {AppContainer} from 'react-hot-loader';

// Wrap the rendering in a function:
const render = Component => {
  ReactDOM.render(
    // Wrap App inside AppContainer
    <AppContainer>
      <NextApp/>
    </AppContainer>,
    document.getElementById('root')
  );
};

// Do this once
registerServiceWorker();
// unregister();
// Render once
render(NextApp);

// Webpack Hot Module Replacement API
if (module.hot) {
  module.hot.accept('./NextApp', () => {
    render(NextApp);
  });
}
`

**Comment by dawnmist** [comment]
I've just updated the comments to turn the views into code rendering rather than normal text as per https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown because it's easier to read.

Having a look at what you have, it's almost the same as current create-react-app (minor changes in CRA to allow a few callbacks to be passed into the register function). One of the things that they say is that to activate the new service worker, you need to _close all open tabs for the site in the browser_ instead of simply reloading them. I suspect that this is the state you're getting into (not having had to debug this yet).

There is a way to tell a new service worker to automatically replace the existing one on install instead of waiting for all tabs to be closed then reopened. Google has some documentation here to get started with: https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#skip_the_waiting_phase

I don't believe that this is actually due to the use of react-app-rewired itself, but actually part of how the service worker is set up. Give the `worker.skipWaiting()` stuff in the google docs a try, and let us know if that sorts out the issue.

**Comment by proactive-dev** [comment]
@timarney Is it solved?
How did you solve?
