### ISSUE TITLE
[Question] What about code splitting in vendors? 

### ISSUE THREAD

**Issue by chemitaxis** [timarney/react-app-rewired#38]
Hi, I'm using this in my projects, but I want to use create-react-app. 
```

// optimizations
    new CommonsChunkPlugin({
      children: true,
      async: 'common',
      minChunks: 2,
    }),
    new CommonsChunkPlugin({
      children: true,
      async: 'vendor',
      minChunks(module) {
        // this assumes your vendor imports exist in the node_modules directory
        return isVendor(module);
      },
    }),
```

Where isVendor is like this:

```
function isVendor (module) {
  return module.context && module.context.indexOf('node_modules') !== -1;
}
```

Can I use react-app-rewired for this? Thanks ;)

**Comment by timarney** [comment]
To date I haven't heard of anyone who has tried splitting out vendors using this repo.  

I would suggest looking at these issues in the CRA repo first:
https://github.com/facebookincubator/create-react-app/issues/2206
https://github.com/facebookincubator/create-react-app/pull/2310

**Comment by chemitaxis** [comment]
Perfect, thanks!
