### ISSUE TITLE
can't config host or port in devServer???

### ISSUE THREAD

**Issue by yanqiangsjz** [timarney/react-app-rewired#383]
module.exports = {
    webpack: function(config, env) {
        config.resolve.alias = {
            '@': resolve('src')
        }
        return config;
    },
    paths: function(paths, env) {
        return paths;
    },
    devServer: function(configFunction) {
        return function(proxy, allowedHost) {
            const config = configFunction(proxy, allowedHost);
           	config.host = 'user.test.com'
            return config;
        };
    },
}

**Comment by dawnmist** [comment]
You don't need to use react-app-rewired to set host & port of the devServer.

From the [Create-React-App documentation](https://facebook.github.io/create-react-app/docs/advanced-configuration), just set the `HOST` and `PORT` variables in your `.env` file.

**Comment by yanqiangsjz** [comment]
> You don't need to use react-app-rewired to set host & port of the devServer.
> 
> From the [Create-React-App documentation](https://facebook.github.io/create-react-app/docs/advanced-configuration), just set the `HOST` and `PORT` variables in your `.env` file.

thx~~~
