### ISSUE TITLE
Update Peer Dependencies to support react-scripts ^3.0.0

### ISSUE THREAD

**Issue by leantide** [timarney/react-app-rewired#384]
Update Peer Dependencies to support react-scripts ^3.0.0

package.json
"peerDependencies": {"react-scripts": "^2.1.3"}

**Comment by leantide** [comment]
https://github.com/timarney/react-app-rewired/pull/385

**Comment by msikma** [comment]
Has anyone tried this yet? Any issues arising from CRA being updated to [3.0](https://github.com/facebook/create-react-app/releases/tag/v3.0.0)?

**Comment by timarney** [comment]
react-app-rewired@2.1.2

**Comment by leantide** [comment]
Sorry. I mistakenly updated devDependencies instead of peerDependencies. See PR https://github.com/timarney/react-app-rewired/pull/387
