### ISSUE TITLE
How to package html js css separately in different directories, how should I configure？

### ISSUE THREAD

**Issue by wiiler** [timarney/react-app-rewired#390]
How to package html js css separately in different directories, how should I configure？

**Comment by dawnmist** [comment]
Separately how?

Currently CRA packages things as:
* build/
  * index.html
  * favicon.ico
  * asset-manifest.json
  * manifest.json
  * preload.js
  * service-worker.js
  * static/
    * css/
      * css bundles for your javascript bundles (often just a main.xyz.chunk.css)
    * js/
      * your various javascript bundles
    * media/
      * your linked images

What did you want to change?

**Comment by timarney** [comment]
Closing this.  

Not a bug.
