### ISSUE TITLE
Support CRA 3

### ISSUE THREAD

**Issue by DeadManPoe** [timarney/react-app-rewired#394]

**Comment by crobinson42** [comment]
@timarney would you accept a PR for this or is someone already working on it?

**Comment by timarney** [comment]
@crobinson42 for sure

**Comment by mads-thines** [comment]
I just updated, and got it working with CRA 3

**Comment by erikhansen** [comment]
@mads-thines I'm using CRA 3 and would like to use this `react-app-rewired` package. Did you have to do anything special to get it working?

**Comment by mads-thines** [comment]
@erikhansen I'm the maintainer of my companies React Boilerplate.
The update is currently still in review, but you can checkout the [WIP branch here](https://github.com/adaptdk/react_boilerplate/blob/maintenance/ts/base/package.json)

Hope it helps :)

**Comment by italoiz** [comment]
I needed to use a custom configuration for Jest, and for me it worked very well. It was a simple thing, but the CRA would not let me do it.

My version of CRA is **3.0.1**

<details>
<summary>config-overrides.js</summary>

```js
// Override `create-react-app` default configs for Jest.
const jestConfig = require('./jest.config');

module.exports = {
  jest(config) {
    return { ...config, ...jestConfig };
  },
};
```
</details>

**Comment by timarney** [comment]
Closing this.

Did a quick test seems to be working fine with CRA 3.
