### ISSUE TITLE
npm run build:test doesn't work

### ISSUE THREAD

**Issue by matteokjh** [timarney/react-app-rewired#395]
I want to set different urls for production:
```
"scripts": {
  "start": "react-app-rewired start",
  "build": " react-app-rewired build",
  "build:test" "cross-env NODE_ENV=test react-app-rewired build"
}
```
so that when I `npm run build:test`  I could use urls in  ./.env.test 
but I found that in ' ./node_modules/react-app-rewired/scripts/build.js'：
```
process.env.NODE_ENV =  'production';
```
which means it won't work no matter how I change NODE_ENV, so I change this file like 'start.js'
```
process.env.NODE_ENV = process.env.NODE_ENV || 'production';
```
and things work well.
but I want to ask why build.js 's NODE_ENV is absolutely 'production' and not allow to accept other NODE_ENV like 'test' or anyothers I set?

or is there any way to change NODE_ENV outside such as in ./config-override.js ?

**Comment by dawnmist** [comment]
There are optimisations that react-scripts (create-react-app's build scripts) do during build that are _only_ applied if NODE_ENV is 'production'. The NODE_ENV is not supposed to reflect what server you are building for - it's for whether you're working in a development mode (with webpack dev server showing current code and recompiling each time you make changes), a production mode (actual site release code), or using something like jest for automated tests outside of the browser. Overloading it by setting it to a different value than 'production' will mean that you will _not_ get a proper production build (with dead code removal, optimisation, etc).

Further, create-react-app used to have specific code within their system that applies any time the project is built without using NODE_ENV='production' that explicitly warns the user that you are not using a production version of the code/have compiled the site incorrectly. I'm not sure if that bit is still there, but as it was a guard against people accidentally releasing a development build I'm assuming it still is.

As `.env.test` is used for jest testing, using that as the name of the env file for a production build on a test server will cause issues as it will also get automatically used anytime `yarn test` is run.

How many options change between the different servers? Are they all being built on the same machine? If it's one option, you could possibly set the env variable that is changing inline, something like `REACT_AP_SERVER_URL='https://my-test.server.com' yarn build`. The value in the `.env` files will not overwrite the value given on the command line (check out [cross-env]() for a cross-platform way to define the environment variable). If it was several variables that are changing, keep them in different `.env.servername` files (do not use 'prod', 'dev' or 'test' for servername) and copy that file to `.env` or `.env.local` as a pre-build step.

Changing NODE_ENV is not the right solution to the problem.

**Comment by matteokjh** [comment]
> There are optimisations that react-scripts (create-react-app's build scripts) do during build that are _only_ applied if NODE_ENV is 'production'. The NODE_ENV is not supposed to reflect what server you are building for - it's for whether you're working in a development mode (with webpack dev server showing current code and recompiling each time you make changes), a production mode (actual site release code), or using something like jest for automated tests outside of the browser. Overloading it by setting it to a different value than 'production' will mean that you will _not_ get a proper production build (with dead code removal, optimisation, etc).
> 
> Further, create-react-app used to have specific code within their system that applies any time the project is built without using NODE_ENV='production' that explicitly warns the user that you are not using a production version of the code/have compiled the site incorrectly. I'm not sure if that bit is still there, but as it was a guard against people accidentally releasing a development build I'm assuming it still is.
> 
> As `.env.test` is used for jest testing, using that as the name of the env file for a production build on a test server will cause issues as it will also get automatically used anytime `yarn test` is run.
> 
> How many options change between the different servers? Are they all being built on the same machine? If it's one option, you could possibly set the env variable that is changing inline, something like `REACT_AP_SERVER_URL='https://my-test.server.com' yarn build`. The value in the `.env` files will not overwrite the value given on the command line (check out [cross-env](https://github.com/kentcdodds/cross-env) for a cross-platform way to define the environment variable). If it was several variables that are changing, keep them in different `.env.servername` files (do not use 'production', 'development' or 'test' for servername - these all have special meaning to create-react-app) and copy that file to `.env` or `.env.local` as a pre-build step.
> 
> Changing NODE_ENV is not the right solution to the problem.
> 
> Edit: even better - try following the documentation from [create-react-app](https://facebook.github.io/create-react-app/docs/deployment#customizing-environment-variables-for-arbitrary-build-environments) where they document how to do this without needing to make any external changes to the build.

thank you! env-cmd works well.
