### ISSUE TITLE
cant get react-app-rewired to run, instead get an 'Unexpected token' for using the spread operator

### ISSUE THREAD

**Issue by royair** [timarney/react-app-rewired#398]
trying to start a freshly cloned project with the following  config-override:

```
const { injectBabelPlugin } = require('react-app-rewired');
const rewireLess            = require('react-app-rewire-less');
const webpack               = require('webpack');
const rewireReactHotLoader  = require('react-app-rewire-hot-loader');


module.exports = function override(config, env) {
  // Here we are handeling the Less rewriting to allow us to override antd default variables
  config = injectBabelPlugin(['import', {
    libraryName: 'antd',
    style: true,
  }], config); // change importing css to less
  config = rewireLess(config, env, {
    modifyVars: { '@primary-color': '#047fff' },
  });
  config.resolve.modules.unshift(`${__dirname}/lib`);
  config.plugins = config.plugins.map(
    (plugin) => {
      if (plugin instanceof webpack.optimize.UglifyJsPlugin) {
        plugin.options.mangle = {
          except: ['BigInteger', 'ECPair', 'Point'],
        };
      }
      return plugin;
    },
  );
  config.module.rules[1].oneOf.push(
    {
      ...config.module.rules[1].oneOf[1],
      include: `${__dirname}/lib`,
    },
    {
      ...config.module.rules[1].oneOf[1],
      include: `${__dirname}/node_modules/@somePrivateModule`,
    },
  );
  return rewireReactHotLoader(config, env);
};
```

but i get an error stating that a spread operator in one of our internal modules is an "unexpected token" : (..state)

```
 return {
        ...state,
        activeModal: (payload && payload.name) || '',
        data: (payload && payload.data) || {},
      };
```

here is the error:

> ./node_modules/@somePrivateModule/web-components/src/components/ReduxModal/reducer.js
> Module parse failed: C:\projects\my-project-web-client\node_modules\@somePrivateModule\web-components\src\components\ReduxModal\reducer.js Unexpecte
> d token (19:8)
> You may need an appropriate loader to handle this file type.

i'm using windows 10 (this does not happen on mac nor linux)

**Comment by mads-thines** [comment]
Is it the first spread operator in your code?
It could be the babel setup not working correctly.

**Comment by royair** [comment]
Not sure, but I've managed to overcome this issue by upgrading my cra and cra-rewired with it. Still have some issues with the build failing though

**Comment by timarney** [comment]
injectBabelPlugin 
https://github.com/timarney/react-app-rewired/blob/master/index.js#L17
