### ISSUE TITLE
Better npm scripts

### ISSUE THREAD

**Issue by geelen** [timarney/react-app-rewired#4]
So it _should_ be possible, instead of having the following in the package.json

```
    "rewire:start": "node ./node_modules/react-app-rewired/scripts/start",
    "rewire:build": "node ./node_modules/react-app-rewired/scripts/build"
```

to have this:

```
    "rewire:start": "react-app-rewired start",
    "rewire:build": "react-app-rewired build"
```

Also means that you could just replace the package names of the default entry points if you prefer (I do! 😄 )

```diff
-    "start": "react-scripts start",
-    "build": "react-scripts build",
+    "start": "react-app-rewired start",
+    "build": "react-app-rewired build",
```

**Comment by timarney** [comment]
That's better for sure.  What's the best way to get those `run` scripts to hit the `scripts` dir where start.js and build.js sit?  Feel free to make the update if you have time.  This is the first package I've published to NPM so I'm fairly new to proper setup / best practices.

**Comment by timarney** [comment]
WIP on this branch - https://github.com/timarney/react-app-rewired/tree/scripts

**Comment by timarney** [comment]
@geelen got this up and running 😄 .

**Comment by geelen** [comment]
Looking good!
