### ISSUE TITLE
Compatibility with dynamic-cdn-webpack-plugin

### ISSUE THREAD

**Issue by mbrucher** [timarney/react-app-rewired#402]
I'm trying to move some of my app dependencies, like React, to be downloaded with a CDN with the `dynamic-cdn-webpack-plugin` plugin.

If I use the following configuration, tried by merging what is advocated as webpack parameters and the rewired tutorial:

```
const HtmlWebpackPlugin = require("html-webpack-plugin");
const DynamicCdnWebpackPlugin = require("dynamic-cdn-webpack-plugin");
const ManifestPlugin = require('webpack-manifest-plugin');

module.exports = function override(config) {
  if (!config.entry) {
    config.entry = {};
  }

  config.entry["index.js"] = "./src/index.js";
  
  if (!config.output) {
    config.output = {};
  }

  //config.output["path"] = path.resolve(__dirname, "./build");

  if (!config.plugins) {
    config.plugins = [];
  }

  config.plugins.push(new ManifestPlugin({
            fileName: 'manifest.json'
        }));//new HtmlWebpackPlugin());
  config.plugins.push(new DynamicCdnWebpackPlugin());

  return config;
};
```

The manifest.json file doesn't mention react, actually none of my dependencies are tehre, and the html file doesn't have them either.

Are the two plugins compatible or perhaps did I miss something obvious? (still very new to all the JS world!)

**Comment by timarney** [comment]
Hi I've never used that plugin so can't offer any advice.

I would recommended using create react app as close to out of the box as possible if your new to Javascript.

**Comment by brysgo** [comment]
@mbrucher - in case you still need to scratch that itch: https://github.com/brysgo/unpkg-experiment
