### ISSUE TITLE
Cant follow component import ( Ctrl + Click | F12 ) when using alias

### ISSUE THREAD

**Issue by dattebayorob** [timarney/react-app-rewired#405]
The imports works great, but i cant follow the imported component. (Lib impots works normal)

```
//config-override.js
const { override, addDecoratorsLegacy, addWebpackAlias } = require('customize-cra')
const path = require('path')

module.exports = override(
    addDecoratorsLegacy(), 
    addWebpackAlias({
        ['@']: path.resolve(__dirname, 'src')
     })
)
```

```
//jsconfig.json
 {
    "compilerOptions": {
        "experimentalDecorators": true,
        "target": "ES6",
        "module": "commonjs",
        "allowSyntheticDefaultImports": true,
        "baseUrl": ".",
        "paths": {
            "@/*": ["src/*"]
        }
    },
    "exclude": [
        "build",
        "node_modules"
    ]
}
```

**Comment by with-heart** [comment]
Hi @dattebayorob, I think the problem might be that you have `'@'` surrounded by brackets. Can you try removing those and see if it works for you?

```ts
addWebpackAlias({
  '@': path.resolve(__dirname, 'src')
})
```

If that doesn't work, please [open an issue](https://github.com/arackaf/customize-cra/issues/new) in the [`customize-cra` repo](https://github.com/arackaf/customize-cra) as this is not a problem with `react-app-rewired`.

**Comment by michielmetcake** [comment]
What editor do you use?

**Comment by dattebayorob** [comment]
I'm using Vscode, I will try the with-heart Suggestion

**Comment by timarney** [comment]
Closing as this isn't a bug with this repo.
