### ISSUE TITLE
config-overrides.js 引入后stylus就失效了？

### ISSUE THREAD

**Issue by MaySept** [timarney/react-app-rewired#406]
请问为什么我 yarn add react-app-rewired customize-cra
修改package.json文件中“script”
自定义config-overrides.js文件后，原来的外联样式就失效了？

**Comment by michielmetcake** [comment]
Could you write the issue in English please? So more people can help you with the issue.

**Comment by minosss** [comment]
@MaySept `react-app-rewired` `customize-cra` 是两个方案选一个就行。带上代码片段，有操作步骤最好

**Comment by fengxinming** [comment]
@MaySept [https://github.com/fengxinming/chain-css-loader](https://github.com/fengxinming/chain-css-loader) 我这里有个方案，可以参考一下
