### ISSUE TITLE
Exporting multiple configurations

### ISSUE THREAD

**Issue by mwanago** [timarney/react-app-rewired#413]
I would like to [export multiple webpack configurations](https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations).
Every time I try to return an array from the override function it results in an error:

```
module.exports = function override(config) {
  return [config, {
    ...config,
    entry: './serviceWorker.js',
    output: {
      filename: 'serviceWorker.js',
      path: __dirname
    }
  }];
};
```

> Cannot read property 'tap' of undefined

Is there any way to achieve this?

Basically, I would like to create a custom service worker file in the **public** directory, but with transpiling involved (ideally with TypeScript - my CRA project uses it). Maybe you could suggest another way to do that without multiple configurations.

**Comment by timarney** [comment]
Closing as this isn't an issue with this repo and no one has picked this up to discuss.
