### ISSUE TITLE
prepack.io?

### ISSUE THREAD

**Issue by websocket98765** [timarney/react-app-rewired#429]
Sorry for the question. Important plugin.

Have you had any luck getting [prepack.io](https://prepack.io/) to work as a plugin? Is a special plugin format required? (I see a list of react-app-rewire-x plugins in the readme, but no explanation of why, or if, they are required instead of regular webpack plugins.)

I've tried various prepack-webpack-plugins and none work with react-app-rewired. I haven't been able to figure out if it's due to react-app-rewired, the webpackage prepack plugins I've tried, or prepack itself, or my use of Preact. Too many variables.

Thanks

**Comment by dawnmist** [comment]
The various react-app-rewire-x plugins were to make it easier to add specific webpack plugins to the config. There is no requirement to use them - and most of them were for version 2 or 3 of webpack and thus won't work anymore (too much changed in webpack version 4).

In terms of getting plugins to work, how have you been trying to use them? Can you post the content of your `config-overrides.js` file?

Looking at https://www.npmjs.com/package/prepack-webpack-plugin - it should be very simple to add.

```js
const PrepackWebpackPlugin = require('prepack-webpack-plugin');

// Note: this can optionally contain two fields:
// - test: A regex used to match the files, defaults to: /\.js($\\|\?)/i
// - prepack: An object containing the prepack configuration.
const prepackPluginConfig = {};

module.exports = function override(config, env) {
  config.plugins.push(new PrepackWebpackPlugin(prepackPluginConfig));
  return config;
};
```

**Comment by websocket98765** [comment]
I used that config (except adding `.default` on the require statement as it needs) + ran `npm i --save-dev prepack`. I also disabled my Preact alias to simplify my config.

```js
const PrepackWebpackPlugin = require('prepack-webpack-plugin').default;

// Note: this can optionally contain two fields:
// - test: A regex used to match the files, defaults to: /\.js($\\|\?)/i
// - prepack: An object containing the prepack configuration.
const prepackPluginConfig = {};

module.exports = function override(config, env) {

  // // Alias react to preact-compat
  // config['resolve']['alias'] = {
  //   "react": "preact/compat",
  //   "react-dom/test-utils": "preact/test-utils",
  //   "react-dom": "preact/compat",
  // };

  // // Disable source maps for production.
  // if (env === 'production') {
  //   config.devtool = false;
  // }

  config.plugins.push(new PrepackWebpackPlugin(prepackPluginConfig));

  return config;
}
```

Then I ran it using `npm run start` (which runs `react-app-rewired start`) and also tried `npm run build && serve -s build`. For both, the result is a white page (using web inspector, the HTML looks proper for my react app). (same results I had in the past). If I comment out the plugin line and run `npm run start`, my app loads like normal. So I ruled out preact--it's either `prepack`, `prepack-webpack-plugin`, or `react-app-rewired`. 

Deps:
"react": "^16.10.2",
"react-dom": "^16.10.2",
"react-app-rewired": "^2.1.3",
"prepack": "^0.2.54",
"prepack-webpack-plugin": "^1.1.2",

If you don't think it's react-app-rewired, feel free to close. Though I'd love to get it working if you have any ideas.

**Comment by dawnmist** [comment]
Do you have an example project I can look at? I do not believe that react-app-rewired is the cause (except in allowing you to add the prepack plugin). I believe it'll be a webpack/prepack issue, but would like to be able to see what is going on.

It may simply be a case of the plugin needing to be defined before other plugins instead of at the end, or an incompatibility between prepack and one of the standard plugins that react-scripts sets up.

**Comment by websocket98765** [comment]
Thanks @dawnmist. I created a new Create React App example which demonstrate the issue: <https://github.com/websocket98765/demo>

Steps used to create it:
```
npx create-react-app demo
npm i --save-dev react-app-rewired
npm i --save-dev prepack-webpack-plugin
npm i --save-dev prepack
// Add config-overrides.js
```

Running `npm run start` will start the server but will show a white page at localhost:3000. Then comment out `config.plugins.push(new PrepackWebpackPlugin(prepackPluginConfig));` in `config-overrides.js` and it will load like normal and you'll see the React logo.

**Comment by dawnmist** [comment]
Thank you for the example.

As near as I can tell, prepack _is_ being run on the code when using the Prepack Webpack Plugin - but the code being produced then isn't running on the website. The app's code all seems to be there when looking with Chrome dev tools, though all functions got put into variables. I _think_ what is happening is the `ReactDOM.render(...)` call from src/index.js simply isn't being run/executed on the page when the page loads, so the react dom (and thus the App component) never get mounted, and therefore the page remains blank. Checking side-by-side for the compiled main.xxxx.js file (and bundle & 0.xxx chunks) shows that the application code is there (just in a modified fashion when it comes to functions, etc).

Left hand side is normal compiled code, right hand side is the prepack compiled code:
![image](https://user-images.githubusercontent.com/5810277/70393519-f5104480-1a3e-11ea-9888-aafb57e63e84.png)

That being the case, I think this may actually be an upstream issue in prepack itself. I must admit to being a little surprised that code from Facebook doesn't work against React itself (even if React-Native was the original 'target' environment). All I can say is that I guess they have good reasons for labelling Prepack as "not ready for production use". :frowning_face:

**Comment by websocket98765** [comment]
Thanks for looking at this and confirming it's not `react-app-rewired`. It's helpful to have eliminated that variable! 

I also tried a prepack config of the below with the same broken result:
```
new PrepackPlugin({
        reactEnabled: true,
        compatibility: 'node-react',
})
```
I think it's possible the issue is with the plugin too. There is an old, related issue: <https://github.com/gajus/prepack-webpack-plugin/issues/53>. Hope facebook re-starts work on prepack again soon.
