### ISSUE TITLE
fix: override defaults when merging Jest config

### ISSUE THREAD

**Issue by r0ughnex** [timarney/react-app-rewired#430]
This **does not work for all config options!** In the below snippet the rules from _transformIgnorePatterns_ is not upheld when using `react-scripts-rewired test`, but it works with `react-scripts test`.

```
"jest": {
    "collectCoverageFrom": [
      "src/**/*.{js,jsx,ts,tsx}",
      "!src/**/*.d.ts"
    ],
    "coveragePathIgnorePatterns": [
      ".story.{js,jsx,ts,tsx}"
    ],
    "transformIgnorePatterns": [
      "node_modules/?!(hashids)"
    ]
  }
```

_Originally posted by @r0ughnex in https://github.com/timarney/react-app-rewired/pull/420#issuecomment-563050902_

**Comment by guscost** [comment]
Compare: 

https://github.com/facebook/create-react-app/blob/9750738cce89a967cc71f28390daf5d4311b193c/packages/react-scripts/scripts/utils/createJestConfig.js#L93-L105 **replaces** arrays in **supported** parts of the existing config, and extends objects.

https://github.com/timarney/react-app-rewired/blob/1cc9a41b12be773004c0ee6550ef2d778f174cfd/scripts/utils/rewireJestConfig.js#L18-L29 **appends** to **any** arrays in the existing config.

Since it looks like CRA now supports your overrides, try ditching `react-app-rewired` for your tests and just run `react-scripts test`.

**Comment by r0ughnex** [comment]
I suppose you could also add those keys into `config-overrides.js`

**Comment by r0ughnex** [comment]
> Compare:
> 
> [react-scripts](https://github.com/facebook/create-react-app/blob/9750738cce89a967cc71f28390daf5d4311b193c/packages/react-scripts/scripts/utils/createJestConfig.js#L93-L105) **replaces** supported arrays in the existing config.
> 
> [react-app-rewired](https://github.com/timarney/react-app-rewired/blob/1cc9a41b12be773004c0ee6550ef2d778f174cfd/scripts/utils/rewireJestConfig.js#L18-L29) **appends** to **any** arrays in the existing config.
> 
> Since it looks like CRA now supports all of your overrided keys, try ditching `react-app-rewired` for your tests and just run `react-scripts test`.

I suppose you could also add those keys into `config-overrides.js`

**Comment by r0ughnex** [comment]
@guscost: I suppose I could also add those keys into `config-overrides.js`.

**Comment by r0ughnex** [comment]
> Compare:
> 
> [react-scripts](https://github.com/facebook/create-react-app/blob/9750738cce89a967cc71f28390daf5d4311b193c/packages/react-scripts/scripts/utils/createJestConfig.js#L93-L105) **replaces** supported arrays in the existing config.
> 
> [react-app-rewired](https://github.com/timarney/react-app-rewired/blob/1cc9a41b12be773004c0ee6550ef2d778f174cfd/scripts/utils/rewireJestConfig.js#L18-L29) **appends** to **any** arrays in the existing config.
> 
> Since it looks like CRA now supports all of your overrided keys, try ditching `react-app-rewired` for your tests and just run `react-scripts test`.

I suppose you could also add those keys into `config-overrides.js`
