### ISSUE TITLE
Jest config is recognized in config-overrides.js but not package.json

### ISSUE THREAD

**Issue by nickmccurdy** [timarney/react-app-rewired#438]
I had to set `transformIgnorePatterns` in my rewired app to fix build issues with Jest, but for some reason I could not get it to honor my config when putting it in `package.json` in the `jest` field (which seems to be supported according to the readme). This caused me a bit of confusion until I realized the same config worked in `config-overrides.js` with the `jest` config function.

Oddly enough, I do get validation errors when the Jest config in `package.json` is in the wrong format, even though Jest still ignores transforming this module as if I never configured it and errors with `SyntaxError: Cannot use import statement outside a module`.

Working with `config-overrides.js`: https://github.com/nickmccurdy/type-explorer/tree/c710a2bd65d1c565662781cb81c8c2b00d878ca1
Broken with `package.json`: https://github.com/nickmccurdy/type-explorer/tree/1dc167e4139c5ded037b7e5dfc60ed15e67bdeca

**Comment by timarney** [comment]
Closing this as no one has picked it up. 

If you believe this is a bug please like to a sample repo ... better chance of someone looking at it.

**Comment by tangdw** [comment]
@nickmccurdy 
写在 package.json 里面：新加的规则与 cra 默认规则 or 操作 new RegExp(config.transformIgnorePatterns.join('|')), cra 默认匹配node_modules 所有，因此你写的 ?!monaco-editor/ 无效

写在 config-overrides.js 里面：覆盖 cra 默认规则

**Comment by victorAttar** [comment]
Is there any resolution?
I`m facing the same error

**Comment by nickserv** [comment]
If you want to customize your build tool, use Vite
