### ISSUE TITLE
Jest failing on Imports

### ISSUE THREAD

**Issue by nicmyers** [timarney/react-app-rewired#44]
Hi, 
Sorry if this is related to the other open issues related to Jest, but we are running into an issue and are not sure if it's caused by a misconfiguration on our side or if it's a known issue. If it is related to the other ones, let me know and I can close this and move it there.

We using react-app-rewired for decorator support with Mobx (react-app-rewire-mobx 1.0.3). We are on the latest version of react-app-rewired (1.0.5) and the latest version of Create React App (1.0.6)

Our application runs without issues and decorator support is working great. However, when running tests, we get the following errors

`Test suite failed to run
import 'example-module';
    ^^^^^^
    SyntaxError: Unexpected token import`

I assume it's related to the configuration of Jest, where maybe Babel is not transpiling the tests correctly. We are not doing anything special with running the tests, and our package.json is as recommended in the readme `"test": "react-app-rewired test --env=jsdom"`

I'm happy to provide any additional information.

**Comment by timarney** [comment]
I use https://github.com/timarney/mobx-rewire-test as a test repo and it seems to be working.  Can you see if you can replicate the issue using that repo?

**Comment by nicmyers** [comment]
The config and versions we are using the same as in the link you sent, minus the Preact addition. The issue seems to come from the fact that the imports that are failing are in a dependency within the node_modules folder. Is there anything that might be blocking those from transpiling correctly?

**Comment by timarney** [comment]
> Is there anything that might be blocking those from transpiling correctly?

Not that I'm aware of.

**Comment by nicmyers** [comment]
FYI, the issue comes down to lines 39-41 of createJestConfig.js.  Jest is it not transforming anything in node_modules which explains why we are having issues. 
I will close this issue and leave a comment on another issue regarding the setting of Jest configuration options. 
```
transformIgnorePatterns: [
    '[/\\\\]node_modules[/\\\\].+\\.(js|jsx)$'
 ],
```
