### ISSUE TITLE
Using 'npm link' local project, out of memory

### ISSUE THREAD

**Issue by mjlan** [timarney/react-app-rewired#440]
build [] 70%
<--- Last few GCs --->

[55253:0x103800000]    56777 ms: Scavenge 1386.8 (1421.2) -> 1386.0 (1421.7) MB, 8.4 / 0.0 ms  (average mu = 0.230, current mu = 0.173) allocation failure 
[55253:0x103800000]    56793 ms: Scavenge 1387.0 (1421.7) -> 1386.1 (1422.2) MB, 9.9 / 0.0 ms  (average mu = 0.230, current mu = 0.173) allocation failure 
[55253:0x103800000]    56806 ms: Scavenge 1387.0 (1422.2) -> 1386.0 (1422.7) MB, 10.2 / 0.0 ms  (average mu = 0.230, current mu = 0.173) allocation failure 

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x28054e1dbe3d]
Security context: 0x2baade09e6e9 <JSObject>
    1: /* anonymous */ [0x2baa1e175d89] [0x2baaaeb826f1 <undefined>:~1] [pc=0x28054ec7d57d](this=0x2baa1e172681 <Hook map = 0x2baa3fe72619>,request=0x2baacca881c9 <Object map = 0x2baaa3f269b1>,resolveContext=0x2baacca886c1 <Object map = 0x2baa3fe72511>,_callback=0x2baacca886f1 <JSFunction hook.callAsync (sfi = 0x2baadf2f2d79)>)
    2: doResolve [0x2baa08403e...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10003cf99 node::Abort() [/usr/local/bin/node]
 2: 0x10003d1a3 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x1001b7835 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x100585682 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 5: 0x100588155 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/usr/local/bin/node]
 6: 0x100583fff v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 7: 0x1005821d4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0x10058ea6c v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 9: 0x10058eaef v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
10: 0x10055e434 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/usr/local/bin/node]
11: 0x1007e6714 v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
12: 0x28054e1dbe3d 
13: 0x28054ec7d57d 
14: 0x28054edaa915 
15: 0x28054e1918d5

**Comment by dawnmist** [comment]
Not related to react-app-rewired at all.

Node.js has a max memory of around 1.5Gb by default, and your build looks like it is hitting the max memory limits.

When building create-react-app projects, react-scripts has an option `--max-old-space-size` to change that default max memory. I use it to set the build memory to 8Gb for my own production builds.

Try (for 8Gb limit):
```
react-app-rewired --max-old-space-size=8192 start
react-app-rewired --max-old-space-size=8192 build
```
(react-app-rewired will pass the setting through to react-scripts).

When doing other processes like npm link, you can pass that option to node.js as an environment variable `NODE_OPTIONS="--max-old-space-size=8192"`. The [create-react-app page on environment variables](https://create-react-app.dev/docs/adding-custom-environment-variables#adding-temporary-environment-variables-in-your-shell) shows how to set an environment variable in your terminal for windows/linux/mac.
