### ISSUE TITLE
Changing the build path to lib doesnt work

### ISSUE THREAD

**Issue by brendonco** [timarney/react-app-rewired#441]
Changing the target build path to lib is throwing an exception. Below is the config-overrides.js:

```
const path = require('path');

config.output = {
    path: path.resolve(__dirname, 'lib'),
    libraryTarget: 'umd',
  };
```

package.json

```
"build": "react-app-rewired build",
```

lib folder created but is throwing an exception, and is looking for main.js at build folder, rather than looking at lib folder:

no such file or directory build\main.js'

**Comment by ooooevan** [comment]
the same, Is there any solution?

**Comment by dawnmist** [comment]
Try using the paths config [as documented in the readme](https://github.com/timarney/react-app-rewired#4-paths-configuration---development--production).

```js
module.exports = {
  webpack: function(config, env) {
    // your normal config-overrides.js overrides
    return config;
  },
  // The paths config to use when compiling your react app
  //  for development or production.
  paths: function(paths, env) {
    // ...add your paths config
    path.appBuild = path.resolve(__dirname, 'lib');
    return paths;
  }
}
```
See [create-react-app config/paths](https://github.com/facebook/create-react-app/blob/edc671eeea6b7d26ac3f1eb2050e50f75cf9ad5d/packages/react-scripts/config/paths.js#L60-L76) for the list of path variables - the one you would want to change is the paths.appBuild path.

If that doesn't work, try the [alternative method documented here](https://github.com/timarney/react-app-rewired/issues/201#issuecomment-488573268).

**Comment by kafkahw** [comment]
@dawnmist thank you so much! lifesaver!
