### ISSUE TITLE
Aliases

### ISSUE THREAD

**Issue by llmdev** [timarney/react-app-rewired#448]
Hi, have a problem running the tests, I am receiving this message

```
The following changes are being made to your tsconfig.json file:
 - compilerOptions.paths must not be set (aliased imports are not supported)
```

I created the base-tsconfig.json file to create my aliases that I use in my project.

```
#base-tsconfig.json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "utils/*": ["./src/utils/*"],
      "types/*": ["./src/types/*"],
      "components/*": ["./src/components/*"],
      "containers/*": ["./src/containers/*"],
      "services/*": ["./src/services/*"]
    }
  }
}
```

I need to remove this error because it is locking my pipeline in azure devops

**Comment by dawnmist** [comment]
See: https://github.com/timarney/react-app-rewired/issues/400 - setting the aliases for tests
To stop CRA from thinking paths should not be set, see this comment: https://github.com/timarney/react-app-rewired/issues/375#issuecomment-474806096
