### ISSUE TITLE
How to customize babel with react-scripts v1 (webpack v2)

### ISSUE THREAD

**Issue by comerc** [timarney/react-app-rewired#46]
before:

```javascript
// config-overrides.js

function rewire(config, env) {
  const babelrc = config.module.loaders.find(conf => {
    return conf.loader === 'babel'
  }).query
  babelrc.plugins = [
    'styled-jsx-postcss/babel',
  ].concat(babelrc.plugins || [])
  return config
}

module.exports = rewire
```

after:

```javascript
// config-overrides.js

function rewire(config, env) {
  const babelOptions = config.module.rules.find(conf => {
    return conf.loader && conf.loader.includes('babel-loader')
  }).options
  const babelrc = require(babelOptions.presets[0])
  babelrc.plugins = [
    'styled-jsx-postcss/babel',
  ].concat(babelrc.plugins || [])
  babelOptions.presets = babelrc
  return config
}

module.exports = rewire
```

happy coding!

**Comment by mauriciosoares** [comment]
![images-1](https://user-images.githubusercontent.com/2321259/27685684-940c5464-5ccf-11e7-8f43-c494433d5842.jpg)

**Comment by timarney** [comment]
@comerc @mauriciosoares 

You should be able to use injectBabelPlugin(pluginName, config) now. 

See the config here https://github.com/timarney/mobx-rewire-test/blob/master/config-overrides.js

Will add to the Readme at some point.

**Comment by comerc** [comment]
@timarney how about array of plugins? :)

**Comment by timarney** [comment]
@comerc Feel free to give it a try you can find the code here https://github.com/timarney/react-app-rewired/blob/master/packages/react-app-rewired/index.js
