### ISSUE TITLE
Windows Environment

### ISSUE THREAD

**Issue by alexvcasillas** [timarney/react-app-rewired#47]
Hi. @timarney 
I'm opening this Issue because I'm experiencing an error when using **react-app-rewired** under windows environment, the error is the following:

```
webpack.validateSchema is not a function
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! new-panel-genially@0.1.0 start: `react-app-rewired start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the new-panel-genially@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

There's a problem with the [node-gyp](https://github.com/nodejs/node-gyp) package that you use for some internal stuff or some dependency you need but, **node-gyp** has problem with Window's environment so I can't use **react-app-rewired** at work (yes, I use windows at work, at the moment).

It's not working even installing the "required stuff" that node-gyp package says it's mandatory for windows:

_Install all the required tools and configurations using Microsoft's windows-build-tools using npm install --global --production windows-build-tools from an elevated PowerShell or CMD.exe (run as Administrator)._

If you could replace this dependency for something a little more "universal" so, windows users (like me at work) could use this, would be awesome!

Thanks for you time!

**Comment by timarney** [comment]
Any chance you can spit in a sample repo to do some testing against?  Perhaps try installing this https://github.com/timarney/mobx-rewire-test and see it you run into the same issue.

**Comment by timarney** [comment]
@alexvcasillas Can you try installing https://github.com/timarney/mobx-rewire-test and see if it runs for Windows?

**Comment by alexvcasillas** [comment]
Works smooth @timarney !!
It seemed that this issue was not concerning react-app-rewired because I was able to made it run long ago but forgot to post and tell you.
But this `mobx-rewire-test` works smooth 👌 

Thanks for the help !
