### ISSUE TITLE
react-app-rewired: command not found

### ISSUE THREAD

**Issue by camillalo** [timarney/react-app-rewired#470]
I install this package in 'devDependencies'，
```
  "devDependencies": {
    "customize-cra": "^1.0.0",
    "react-app-rewired": "^2.1.6",
    "typescript": "^3.7.5"
  }
```
then config everything as readme.md said, 
then 'npm start',
```
  "scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test",
    "eject": "react-scripts eject"
  },
```
i got this **error**:
```
> react-app-rewired start

sh: react-app-rewired: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
```

**Comment by dawnmist** [comment]
Did you run `npm install` after adding react-app-rewired to your dev dependencies?

**Comment by camillalo** [comment]
yes

**Comment by dawnmist** [comment]
* Are you able to share a repository that duplicates your issue?
* Are you using a normal project, or some form of monorepo?
* Does the directory "`<root_dir>/node_modules/react-app-rewired`" exist? If not - react-app-rewired is not installed.
* Does the file "`<root_dir>/node_modules/.bin/react-app-rewired`" exist? If not - something odd has happened, as this should be a link to the file "`<root_dir>/node_modules/react-app-rewired/bin/index.js`"

**Comment by smallzZz8** [comment]
Was the issue ever solved? I am having this exact issue.

**Comment by dawnmist** [comment]
@smallzZz8 - The original poster didn't come back with any information, so I hadn't been able to duplicate the issue in order to debug it. 

If those files are there in your installation, npm should be able to find `react-app-rewired` in the `node_modules/.bin` directory. From: https://docs.npmjs.com/cli/run-script

> In addition to the shell’s pre-existing PATH, npm run adds node_modules/.bin to the PATH provided to scripts. Any binaries provided by locally-installed dependencies can be used without the node_modules/.bin prefix. For example, if there is a devDependency on tap in your package, you should write:
>`"scripts": {"test": "tap test/\*.js"}`
>instead of
>`"scripts": {"test": "node_modules/.bin/tap test/\*.js"}`
>to run your tests.

If you can share a repo that duplicates the issue, can I please request a link to the repo (assuming that was part of what you were saying 'yes' to)?

One other thing to double-check is that you haven't accidentally made a typo in your package.json file (e.g. typed `react-app-rewire start` instead of `react-app-rewired start`) - I have seen that happen before.

**Comment by meirkl** [comment]
I'm having the same issue.
I cloned this repo [https://github.com/uncodead/BrewUNO.git](https://github.com/uncodead/BrewUNO.gitl).
In the interface directory there's a react project that uses `react-app-rewired`.
I ran 
```
npm install 
npm start
```
 and I got this error:

```
'react-app-rewired' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! BrewUNO@0.1.0 start: `react-app-rewired start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the BrewUNO@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2020-09-03T06_48_41_084Z-debug.log
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command npm run start" terminated with exit code: 1.
```

**Comment by dawnmist** [comment]
@meirkl 
I have tried checking out that repository and tried running the above commands and everything worked correctly, but as my test machine is linux I am suspicious that the issue may be related to the difference in path handling between linux & windows.

The BrewUNO project mentions that you will need to use `Git Bash if you are under windows` in their readme documentation. Your log error messages appear to indicate that you are running with PowerShell instead. If that is true, can I suggest that you try running with the git bash shell to check that it's not simply an incompatibility with PowerShell?

**Comment by meirkl** [comment]
@dawnmist
You are right. Thanks!
Works fine with Windows WSL

**Comment by ddennis** [comment]
I just had the same issue on windows. 
Project was using yarn. I deleted node_modules and yarn.lock.
Ran `npm i` - got `'react-app-rewired' is not recognized as an internal or external command`
Ran `npm i react-app-rewired` and everything worked again.

Also had to to reinstall node-sass manually, so something properly broke.

Had this in the log.
```
9 verbose lifecycle playground@0.0.9~start: CWD: C:\***
10 silly lifecycle playground@0.0.9~start: Args: [ '/d /s /c', 'react-app-rewired start' ]
11 silly lifecycle playground@0.0.9~start: Returned: code: 1  signal: null
12 info lifecycle playground@0.0.9~start: Failed to exec start script
13 verbose stack Error:playground@0.0.9 start: `react-app-rewired start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (**\AppData\Roaming\nvm\v12.16.1\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (C:**\AppData\Roaming\nvm\v12.16.1\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid playground@0.0.9
15 verbose cwd C:\****playground
16 verbose Windows_NT 6.3.9600
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
```

**Comment by PaulPCIO** [comment]
I seem to have the same problem on a windows environment using wsl ubuntu.

Replacing yarn with npm as @ddennis mentioned is not really a solution as you can't just swap the packaging of a project. Anyone else found a solution using yarn? 

@ddennis 
> Also had to to reinstall node-sass manually, so something properly broke.

Have you tried to do `yarn rebuild node-sass` or `npm rebuild node-sass`?

**Comment by ddennis** [comment]
@PaulPCIO no, did not try to rebuild. I usually always just try to uninstall and then install again to fix issues. Will try to remember the **rebuild** command.

**Comment by PaulPCIO** [comment]
Anyone else that is having the same problem with a wsl setup, make sure you install in the same subsystem 🤦‍♂️ In my case I initially ran `yarn` from my PowerShell and then I moved over to the ubuntu wsl, which caused the incoherence.

**Comment by stevematdavies** [comment]
Still have this issue

**Comment by PaulPCIO** [comment]
@stevematdavies what system are you running?

**Comment by timarney** [comment]
Can re-open if this is indeed a bug for this repo

**Comment by nimeshkavinda** [comment]
Turns out to be an issue with windows. try npm i react-app-rewired without installing it as a dev dependency

**Comment by mikebridge** [comment]
I was able to get this to work under powershell+yarn using `"react-app-rewired.cmd start"`.

**Comment by TiagoDiass** [comment]
I've gone through this problem today, I got it working fine again just by deleting the `node_modules` folder and installing the dependencies again

```
# Delete node_modules
$ rm -rf node_modules

# install deps
$ npm install
```

**Comment by ramiware** [comment]
If running on a mac, may need to use sudo npm install.
Look at the results of that.

**Comment by dawnmist** [comment]
@ramiware - you should _never_ need to use sudo for npm install for a project. The installation is happening in the user's project folder, so user permissions are all that are needed. Using sudo means that your user files end up being owned by root/admin instead of yourself, and can cause security issues on the PC/Mac. All it would take is _one_ malicious package who has a script that runs on installation of the package to cause substantial damage to your PC/Mac - you've already given it permission to run & access system files by using sudo.

**Comment by apauzies** [comment]
Problem is documentation mention:
npm install react-app-rewired --save-dev
When you build in prod react-app-rewired would be missing
npm install react-app-rewired --save-prod => to fix it

**Comment by dawnmist** [comment]
@apauzies - usually you've already compiled the project for prod, at which time the tools to compile are no longer required. That includes `react-app-rewired`, as that is only used to modify how the project is compiled, it is not used at runtime. This is the same as using webpack, eslint, etc - they're dev dependencies because they're used for development and compiling, but you should not be needing the compile time dependencies in prod because you should be using the already-built site at that point (the output from `yarn build` rather than your source code).

**Comment by paulsimongb** [comment]
I had the same issue. No problems at all until I installed env-cmd. This is when I got the problem. The only solution seemed to be to move all three 
    "react-app-rewired": "^2.2.1",
    "react-app-alias": "^2.2.2",
    "react-app-alias-ex": "^2.1.0"
from devDependencies to Dependencies.
Not entirely sure that emv-cmd is entirely to blame as npm is doing something weird where it is deciding to remove all test related items eg @testing-library/react from node_modules. I can see it install them and then remove them. Something odd is going on. Was all working fine until I started reading articles on the web.

**Comment by paulsimongb** [comment]
Hi - I think I found an answer on this. I had set NODE_ENV=production in System Environment Variables. Despite changing it back to development, npm was still thinking it was running in production. Consequently it was not installing any of the devDependencies. The solution was an npm install -only=dev which installs the devDependencies regardless of the setting of NODE_ENV. I would guess a re-boot of my laptop is going to be needed before NPM acknowledges the new setting of NODE_ENV to development.

**Comment by Yumiorders** [comment]
eveythign work good localy but when i deploy it to heroku i got this error log: 2023-10-04T08:46:05.726425+00:00 app[web.1]: sh: 1: react-app-rewired: not found
2023-10-04T08:46:05.736268+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2023-10-04T08:46:05.736273+00:00 app[web.1]: npm ERR! syscall spawn
2023-10-04T08:46:05.736273+00:00 app[web.1]: npm ERR! file sh
2023-10-04T08:46:05.736273+00:00 app[web.1]: npm ERR! errno ENOENT
2023-10-04T08:46:05.737888+00:00 app[web.1]: npm ERR! Hotellom-react-admin-dashboard@6.4.0 start: `react-app-rewired start`
2023-10-04T08:46:05.737890+00:00 app[web.1]: npm ERR! spawn ENOENT
2023-10-04T08:46:05.737890+00:00 app[web.1]: npm ERR!

**Comment by camillalo** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
