### ISSUE TITLE
React Hook eslint?

### ISSUE THREAD

**Issue by yolinsoft** [timarney/react-app-rewired#477]
React Hook "useState" is called in function "pointRelPath" that is neither a React function component nor a custom React Hook function. React component names must start with an uppercase letter.

**Comment by dawnmist** [comment]
This is an error regarding your source code, and isn't related to react-app-rewired.

React has special handling for any function starting with "use", and as such create-react-app have defined some eslint rules that check for any code that clashes with their special handling.

Somewhere, you have a function called `useState` that is conflicting with React's special handling.
