### ISSUE TITLE
Cant set the path on url to reverse proxied app.

### ISSUE THREAD

**Issue by laurencefass** [timarney/react-app-rewired#480]
I am using nginx to reverse proxy a React app in development mode. My aim is to hang multiple React components from a single domain. e.g.

mysite.com/app1
mysite.com/app2
etc

Using the following config I can load the main page using mysite.com/app1 URL format but the config.js settings dont affect the URL for the socket, the assets or the manifest file which all point to mysite.com excluding the /app1 path

```
'use strict';

module.exports = {
  // The Webpack config to use when compiling your react app for development or production.
  webpack: function(config, env) {
    // ...add your webpack config

    // publicPath sets the path for index scripts: bundle.js, chunk.js, mainchunk.js
    config.output.publicPath = "/app1/"
    console.log("webpack config", config);
    return config;
  },
  // Use to create a webpack dev server configuration when running the development server with 'yarn start'.
  devServer: function(configFunction) {
    return function(proxy, allowedHost) {
      const config = configFunction(proxy, allowedHost);
//      config.sockPath = "/socketjs-node";
//      config.sockPort = 3123;
      console.log("devServer config", config);
      return config;
    };
  },
}
```

Live site here

https://rewired.syntapse.co.uk/app1/

note in developer mode that the main page URL loads correctly at the /app1 location but the websocket, json and image assets fail to load because no /app1 in URL i.e. these addresses are not picking up the publicPath setting. Are these set with another property?

Any help or advice appreciated.

Thanks

**Comment by dawnmist** [comment]
You don't need react-app-rewired for this task.

Create-react-app provide an environment variable that can be used when compiling the site to specify that the site will be mounted under a subdirectory. See: https://create-react-app.dev/docs/advanced-configuration

Set `PUBLIC_URL` to the subdirectory that the site would be mounted under when you compile the site, e.g.
```shell
# Linux/MacOS
PUBLIC_URL='/app1/' yarn build
```
For Windows syntax, see: https://create-react-app.dev/docs/adding-custom-environment-variables/#adding-temporary-environment-variables-in-your-shell

Or you can specify `PUBLIC_URL` in your `.env` file when building.

**Comment by laurencefass** [comment]
Thats very useful I will try some of those settings (I just need it working by any means necessary), though it doesnt resolve this issue: why the  path is being applied to the main bundle code but not to asset and socket URL's.

thanks

**Comment by laurencefass** [comment]
Thanks I tried removing all the config changes from the config.json file and updated using only React. Otherwise this is a clean installation of latest CRA.

**.env file**
﻿
```
PORT=3123
PUBLIC_URL='https://react.syntapse.co.uk/app1/'
```

**nginx.conf**

```
    location ^~ /app1/sockjs-node {
        proxy_pass http://0.0.0.0:3123/sockjs-node;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
    location ^~ /app1/ {
        proxy_pass http://0.0.0.0:3123/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
```

**browser** outout

```
bundle.js:1 Uncaught SyntaxError: Unexpected token '<'
0.chunk.js:1 Uncaught SyntaxError: Unexpected token '<'
main.chunk.js:1 Uncaught SyntaxError: Unexpected token '<'
manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.
﻿
```
​

**Comment by laurencefass** [comment]
screen dump shows unable to reach manifest, socket and asset because the /app1/ is not appended to URL though publicPath is set. ![image](https://user-images.githubusercontent.com/3512857/89891140-7458a800-dbcc-11ea-8a04-e98bb58c8e47.png)

**Comment by laurencefass** [comment]
tried setting devServer.public and devServer.publicPath to match webpack.publicPath

e.g:

```
module.exports = {
  // The Webpack config to use when compiling your react app for development or production.
  webpack: function(config, env) {
    // publicPath sets the path for index scripts: bundle.js, chunk.js, mainchunk.js
    // ERROR: DOESNT set URL path for socket, images and other assets
    config.output.publicPath = "/app1/"

    console.log("webpack config", config);
    return config;
  },
  // Use to create a webpack dev server configuration when running the development server with 'yarn start'.
  devServer: function(configFunction) {
    return function(proxy, allowedHost) {
      const config = configFunction(proxy, allowedHost);

      config.public="rewired.syntapse.co.uk"
      config.publicPath="/app1/";

      console.log("devServer config", config);
      return config;
    };
  },
```
nginx config remains untouched. strange result:

![image](https://user-images.githubusercontent.com/3512857/89892161-2ba1ee80-dbce-11ea-863c-fa57d156aaf4.png)

**Comment by laurencefass** [comment]
To fix the assets Ive tried setting the devServer.contentBasePublic path = "/app1" which is not being applied to the browser fech URL according to the specification,

https://webpack.js.org/configuration/dev-server/#devservercontentbasepublicpath

it is just omitted on the call from the browser. Not confident the changes im making in the config file are being applied.

![image](https://user-images.githubusercontent.com/3512857/89894134-7ffa9d80-dbd1-11ea-98af-0dbdfbb8cba8.png)

**Comment by laurencefass** [comment]
The equivalent (I think) config.js doesnt work and results in an error.

```
module.exports = {
  webpack: function(config, env) {
    **config.output.publicPath = "/app1/"**
    console.log("webpack config", config);
    return config;
  },
  devServer: function(configFunction) {
    return function(proxy, allowedHost) {
      const config = configFunction(proxy, allowedHost);
      **config.sockPath = "/app1/sockjs-node"**
      console.log("devServer config", config);
      return config;
    };
  },
}
```

**Comment by dawnmist** [comment]
In order to try to do it through editing the config-overrides, you'd need to have the configuration for several plugins to be also updated, otherwise all the urls that the plugins add to the index.html file will still refer to the files under the root directory of the server instead of your subdirectory.

That's why all the javascript, manifest file, and css are trying to be accessed from root.

Every place where `publicUrlOrPath` appears in the webpack.config file needs to be updated/replaced with your PUBLIC_URL value in order for it to work. See: https://github.com/facebook/create-react-app/blob/66bf7dfc43350249e2f09d138a20840dae8a0a4a/packages/react-scripts/config/webpack.config.js and search for `paths.publicUrlOrPath` - you'd need to update every usage in the config generated by that file.

You could probably modify it by using the `paths` option in react-app-rewired to change what `publicUrlOrPath` is set to before the webpack config gets created, so that it flows into all the various scripts. Note that I haven't tested this, but I believe that the following is all you'd need (no editing to webpack or devServer parts needed):
```js
module.exports = {
  paths: function(paths, env) {
    return { ...paths, publicUrlOrPath: '/app1/' };
  }
};
```
Unless there was something else you needed react-app-rewired for, I still believe you are better off using the environment variable that create-react-app provides for exactly this purpose (and which they have an invested interest in making sure that it will never break on upgrading create-react-app versions) rather than adding another dependency that you didn't need for the job.

**Comment by laurencefass** [comment]
Thanks dawnmist its all a constant learning curve. your advice worked and i have acheived my goals so onwards and upwads. closing now. many thanks again.
