### ISSUE TITLE
Will there be a dependency update for version 3 of React Scripts?

### ISSUE THREAD

**Issue by tavareshenrique** [timarney/react-app-rewired#481]
I wonder if react-app-rewired will be updated to version 3 of React Scripts.

I see you're still using 2.

**Comment by mjfwebb** [comment]
React Scripts version 4.0.0 is coming soon too.

**Comment by layerssss** [comment]
I was using rewired with CRA version 3 for a while without issues. But CRA 4.0.0 came out a few hours ago and broke it.

**Comment by alexchen1875** [comment]
ok....  i got some information when i upgrade react-srcript to v4.0 ,

![image](https://user-images.githubusercontent.com/3668637/98662155-55f87900-2382-11eb-903c-11ee799e6750.png)

so, i have to  downgrade  react-script 3.x

**Comment by sami616** [comment]
yes updating to 4 is also breaking my build

**Comment by gderidder** [comment]
Yes, same error for me rewiring eslint in combination with react-scripts 4...

**Comment by leojh** [comment]
Same

**Comment by sami616** [comment]
Was only really using this to import stuff outside of src, have migrated to using yarn workspaces which is a much better fit for my use case. 👍🏼

**Comment by timarney** [comment]
Closing this --- should be compatible up to v5 now 

https://github.com/timarney/react-app-rewired/pull/530#issuecomment-1001025219
