### ISSUE TITLE
Cannot find module 'react-dev-utils/crossSpawn' in react-app-rewired

### ISSUE THREAD

**Issue by sumitmoga** [timarney/react-app-rewired#484]
![image](https://user-images.githubusercontent.com/51422440/91458221-e3a7ea80-e8a2-11ea-9122-92eff09da455.png)

**Comment by dawnmist** [comment]
To run with react-app-rewired, you need it to be installed with your project as a devDependency - it's not intended to be able to be run through npx as far as I am aware.

Using npx is likely to be interfering with `react-app-rewired` finding the packages that get installed by `react-scripts`, including the `react-dev-utils` package.
