### ISSUE TITLE
NODE_PATH incompatible with rewired tests

### ISSUE THREAD

**Issue by alex-pex** [timarney/react-app-rewired#49]
I use the [NODE_PATH](https://github.com/timarney/react-app-rewired/blob/master/packages/react-app-rewired/config/paths.js#L38) env var to add an additional node module directory. With regular react-scripts there's no problem but it crashes with rewired tests.

I set up a mini-project to show the issue. You can run ```npm run start``` or ```npm run start:rewired``` and it works fine, ```npm run test``` too but ```npm run start:rewired``` shows _Cannot find module 'package.json'_

Here is the link to my repository : https://github.com/alex-pex/react-app-rewired-sample

**Comment by alex-pex** [comment]
Maybe you need to merge this patch : https://github.com/facebookincubator/create-react-app/commit/d24311ea79704361c8a5fa7fedb04013de6860e8

**Comment by timarney** [comment]
Thanks for setting up the mini-project that will be helpful to track down the issue.  

Hoping to find some time in July to bring this repo back closer to the lastest React Scripts 

Yes - looks like things are getting out of sync 

https://github.com/timarney/react-app-rewired/blob/master/packages/react-app-rewired/config/paths.js
