### ISSUE TITLE
How to prevent exucuting some code in app

### ISSUE THREAD

**Issue by Profesor08** [timarney/react-app-rewired#490]
How to prevent exucuting some code in app, after I run build task? Can i somehow detect in app? I want to exucute some code only in real user browser, but not while build task is executed.

**Comment by dawnmist** [comment]
Code in the app IS only executed when the project is run in a browser. Code in the app does not get executed when compiled. 

The only code executed during build time that you write would be what you put in the config-overrides.js file when building with react-app-rewired as that file contains compiling instructions.
