### ISSUE TITLE
On deployment of heroku react-app-rewired is not even accessing from package.json file. 

### ISSUE THREAD

**Issue by DKhateek1372** [timarney/react-app-rewired#491]
![Screenshot from 2020-09-18 13-36-34](https://user-images.githubusercontent.com/30972035/93572845-0ca83080-f9b4-11ea-9495-591d8e54b484.png)

**Comment by dawnmist** [comment]
Have you run `npm install` first?
Is the install a development or production install - if production, is react-app-rewired in the package.json `dependencies` or `devDependencies` section (production install only installs `dependencies`)?
Is the `node_modules/react-app-rewired` directory present?

The information you've provided looks like you haven't installed the react-app-rewired in that environment. With no actual details about your project at all, I have nothing I can use to help any further than that.

**Comment by DKhateek1372** [comment]
`{
  "name": "Deepak Dk",
  "version": "3.0.5",
  "private": true,
  "dependencies": {
    "@glidejs/glide": "^3.4.1",
    "@redq/js-info-bubble": "^0.8.1",
    "@uppy/core": "^1.5.1",
    "@uppy/dropbox": "^1.3.2",
    "@uppy/google-drive": "^1.3.2",
    "@uppy/instagram": "^1.3.2",
    "@uppy/react": "^1.3.2",
    "@uppy/tus": "^1.4.2",
    "antd": "^3.24.2",
    "antd-img-crop": "^3.10.0",
    "antd-local-icon": "^0.1.3",
    "auth0-lock": "^11.17.3",
    "axios": "^0.19.2",
    "card-react": "^1.2.7",
    "chart.js": "^2.8.0",
    "classnames": "^2.2.6",
    "clone": "^2.1.2",
    "d3-shape": "^1.3.5",
    "enzyme-adapter-react-16": "^1.14.0",
    "enzyme-react-intl": "^2.0.6",
    "express": "^4.17.1",
    "firebase": "^7.2.0",
    "formik": "^1.5.8",
    "frappe-charts": "^0.0.8",
    "fuse.js": "^3.4.5",
    "globalize": "^1.4.2",
    "google-maps-react": "^2.0.2",
    "history": "^4.10.1",
    "js-rich-marker": "^1.1.2",
    "leaflet": "^1.5.1",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "moment-range": "^4.0.2",
    "node-sass": "^4.12.0",
    "nprogress": "^0.2.0",
    "prop-types": "^15.7.2",
    "react": "^16.11.0",
    "react-addons-shallow-compare": "^15.6.2",
    "react-beautiful-dnd": "^11.0.5",
    "react-big-calendar": "^0.22.1",
    "react-chartjs-2": "^2.7.6",
    "react-codemirror": "^1.0.0",
    "react-count-down": "^1.2.1",
    "react-credit-cards": "^0.8.0",
    "react-custom-scrollbars": "^4.2.1",
    "react-daterange-picker": "^2.0.1",
    "react-dates": "^21.2.0",
    "react-dnd": "^7.4.5",
    "react-dnd-html5-backend": "^7.4.4",
    "react-dom": "^16.11.0",
    "react-drawer": "^1.3.4",
    "react-dropzone-component": "^3.2.0",
    "react-element-resize": "^0.2.2",
    "react-error-overlay": "^6.0.3",
    "react-flexbox-grid": "^2.1.2",
    "react-flip-move": "^3.0.3",
    "react-google-charts": "^3.0.15",
    "react-grid-layout": "^0.16.6",
    "react-icons": "^3.7.0",
    "react-id-swiper": "^2.3.2",
    "react-instantsearch": "^4.3.0",
    "react-intl": "^2.9.0",
    "react-loadable": "^5.5.0",
    "react-motion-drawer": "^3.1.0",
    "react-perfect-scrollbar": "^1.5.3",
    "react-placeholder": "^3.0.2",
    "react-quill": "^1.3.3",
    "react-redux": "^7.1.1",
    "react-router": "^5.1.2",
    "react-router-dom": "^5.1.2",
    "react-scripts": "^3.2.0",
    "react-sidebar": "^3.0.2",
    "react-speech-recognition": "^2.0.4",
    "react-tag-input": "^6.4.1",
    "react-throttle": "^0.3.0",
    "react-trend": "^1.2.5",
    "react-vis": "^1.11.7",
    "react-youtube": "^7.9.0",
    "recharts": "^1.7.1",
    "redux": "^4.0.4",
    "redux-devtools": "^3.5.0",
    "redux-devtools-dock-monitor": "^1.1.3",
    "redux-devtools-log-monitor": "^1.4.0",
    "redux-saga": "^1.1.1",
    "redux-saga-firebase": "^0.15.0",
    "redux-thunk": "^2.3.0",
    "reselect": "^4.0.0",
    "rheostat": "^3.0.2",
    "rich-marker": "^0.0.1",
    "styled-components": "^4.4.0",
    "styled-theme": "^0.3.3",
    "swiper": "^5.0.4"
  },
  "scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "serve": "serve -s build",
    "test": "react-scripts test  --coverage --testResultsProcessor jest-sonar-reporter --watchAll=false",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "babel-plugin-import": "^1.12.2",
    "customize-cra": "^0.8.0",
    "enzyme": "^3.10.0",
    "enzyme-to-json": "^3.4.2",
    "jest-sonar-reporter": "^2.0.0",
    "react-app-rewired": "^2.1.4",
    "redux-devtools-extension": "^2.13.8",
    "redux-mock-store": "^1.5.3"
  },
  "jestSonar": {
    "reportPath": "reports",
    "reportFile": "test-report.xml",
    "indent": 4
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
`

I tried installing package in the project.
this is my project package.json.
yes i have node_modules/react-app-rewired this directory present.
I also wrote the config_overide.js file.

**Comment by dawnmist** [comment]
So that directory is present _on the heroku server_ at the time when `npm start` is running?

The reason I ask, is because heroku's documentation for npm indicates that it may be deleting the `devDependencies` prior to deploying the application. It's expecting that you've built the application with `npm build`, and that the start script is for actually deploying the pre-built version, whereas in normal development the start script is used to deploy the dev environment. See: https://devcenter.heroku.com/articles/nodejs-support#package-installation

You can test if this is what is causing `react-app-rewired` to be "missing" by moving it into the `dependencies` instead of `devDependencies`. If react-app-rewired is then found (though it may complain about some of the other devDependencies being missing), it means that heroku is actually removing your devDependencies prior to running the start script.
