### ISSUE TITLE
Compatibility with React 17 / react-scripts 4.0.0

### ISSUE THREAD

**Issue by kenbankspeng** [timarney/react-app-rewired#497]
The following error occurs when using react-app-rewired@2.16 with React 17 and react-scripts@4.0.0.
The error does not occur with React 16 and react-scripts 3.

Cannot read property 'use' of undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! start: `react-app-rewired start`
npm ERR! Exit status 1

**Comment by ElForastero** [comment]
```log
node_modules/react-scripts/scripts/utils/verifyTypeScriptSetup.js:231
        appTsConfig.compilerOptions[option] = suggested;
                                            ^
TypeError: Cannot add property noFallthroughCasesInSwitch, object is not extensible
```

**Comment by jeggy** [comment]
I'm also getting this. This is coming from the `useEslintRc` function.

There is another issue for it reported here: https://github.com/arackaf/customize-cra/issues/274

**Comment by kenbankspeng** [comment]
Thank you @jeggy. I removed useEslintRc and the error went away.
