### ISSUE TITLE
Sass example doesn't work

### ISSUE THREAD

**Issue by charliesbox** [timarney/react-app-rewired#5]
I'm adding this to my new config file

```
module.exports = function override(config, env) {
  config.module.loaders.push({
	test: /\.scss$/,
	loaders: ["style", "css", "sass"]
  });
  console.log(config.module.loaders)
  return config;
}
```

But the styles are lost when testing the app.

I'm importing the new scss files, but nothing happens.

**Comment by pasviegas** [comment]
this fixes: https://github.com/timarney/react-app-rewired/pull/6

**Comment by timarney** [comment]
Can you try with the or just merged for that example?

**Comment by charliesbox** [comment]
Im using @pasviegas example and it worked :) thanks for this amazing library!

**Comment by timarney** [comment]
Thanks @pasviegas

**Comment by pasviegas** [comment]
Thanksyou @timarney! I am finally able to use create-react-app with relay in a decent way hehe.
