### ISSUE TITLE
Getting module not found errors on react-tap-event-plugin

### ISSUE THREAD

**Issue by c0debreaker** [timarney/react-app-rewired#50]
I decided to post the issue here rather than on twitter.

I'm using custom-react-scripts.

react-tap-event-plugin is version 2.0.1
react/react-dom version is 15.6.1

Here is my package.json - https://gist.github.com/c0debreaker/d3cbfe856e4807edd5a859a5c0231c8c

I'm getting this error when I run `npm run start`.

```
Error in ./~/react-tap-event-plugin/src/injectTapEventPlugin.js
Module not found: 'preact-compat/lib/EventPluginHub' in /Users/rcamara/repos/AllReact/dashboard/node_modules/react-tap-event-plugin/src

 @ ./~/react-tap-event-plugin/src/injectTapEventPlugin.js 23:2-41

Error in ./~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: 'preact-compat/lib/EventConstants' in /Users/rcamara/repos/AllReact/dashboard/node_modules/react-tap-event-plugin/src

 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 22:21-60

Error in ./~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: 'preact-compat/lib/EventPluginUtils' in /Users/rcamara/repos/AllReact/dashboard/node_modules/react-tap-event-plugin/src

 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 23:23-64

Error in ./~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: 'preact-compat/lib/EventPropagators' in /Users/rcamara/repos/AllReact/dashboard/node_modules/react-tap-event-plugin/src

 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 24:23-64

Error in ./~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: 'preact-compat/lib/SyntheticUIEvent' in /Users/rcamara/repos/AllReact/dashboard/node_modules/react-tap-event-plugin/src

 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 25:23-64

Error in ./~/react-tap-event-plugin/src/TapEventPlugin.js
Module not found: 'preact-compat/lib/ViewportMetrics' in /Users/rcamara/repos/AllReact/dashboard/node_modules/react-tap-event-plugin/src

 @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 27:22-62
```

**Comment by timarney** [comment]
Do you happen to know what version of CRA is custom scripts up to date with?

**Comment by c0debreaker** [comment]
Here are the top few lines of package.json
```
{
  "name": "custom-react-scripts",
  "version": "0.0.23",
  "description": "Configuration and scripts for Create React App.",
  "repository": {
    "type": "git",
    "url": "https://github.com/kitze/create-react-app/"
  },
  "license": "BSD-3-Clause",
  "engines": {
    "node": ">=4"
  },
```

**Comment by timarney** [comment]
Looks like it's using an older version of React Scripts - which uses an older version of Webpack.

![screen shot 2017-07-06 at 10 13 57 am](https://user-images.githubusercontent.com/62242/27915336-fc7a73c8-6233-11e7-8830-9cee06fb51ba.png)

Is there anything in custom-react-scripts that you need that you can't do with CRA + access to the config via this repo?

**Comment by c0debreaker** [comment]
I think the reason I used custom-react-scripts was the @observable which I use in Mobx. I couldn't remember if .env was part of the original CRA or if it's from custom-react-scripts

**Comment by timarney** [comment]
If your looking to use MobX + decorators CRA doesn't support that.

That said:
CRA + this repo + the MobX rewire will get you there. 

See -> test repo https://github.com/timarney/mobx-rewire-test it uses MobX + uses Preact when compiling for production.

**Comment by c0debreaker** [comment]
Cool! I'll keep you posted. Thanks!

**Comment by c0debreaker** [comment]
Just to confirm, I don't need custom-react-scripts anymore. Correct?

**Comment by timarney** [comment]
Create your app with CRA - this app gives you straight access to the config where you can do whatever you want ... at that point it's up to you.  

> I can't offer support for custom configs I just get you access

https://github.com/timarney/react-app-rewired#how-to-rewire-your-create-react-app-project

**Comment by c0debreaker** [comment]
Got a new error

```
Failed to compile.

./src/Components/MainContent/Irrigation/index.js
Syntax error: Unexpected token (14:0)

  12 | import './Indicator/assets/slider.css';
  13 |
> 14 | @inject('HomeAutomationStores') @observer
     | ^
  15 | class SprinklerZone extends React.Component {
  16 |   handleClick = (e) => {
  17 |     this.props.onClick(e);

```

**Comment by timarney** [comment]
Is there a repo I can look at?

**Comment by c0debreaker** [comment]
It's in a private repo. Which files do you want to see?

**Comment by timarney** [comment]
Maybe...  I just updated my test repo to use @inject("store") @observer

https://github.com/timarney/mobx-rewire-test/blob/master/src/App.js

That's working - what's in your .env file?

**Comment by c0debreaker** [comment]
```
NODE_PATH=src

REACT_APP_BABEL_STAGE_0=true
REACT_APP_DECORATORS=true
```
Sorry just got back from lunch :)

**Comment by timarney** [comment]
Don't need those ... that's custom-react-script stuff

**Comment by c0debreaker** [comment]
My imports though are referencing to the directories inside src directory. That's why I have NODE_PATH.

Here is what I did few minutes ago
```
 ❯ npm uninstall --save react-app-rewire-mobx react-app-rewire-preact react-app-rewired
```

I uninstalled them. Then I reinstalled it again.
```
 ❯ npm install --save react-app-rewire-mobx react-app-rewire-preact react-app-rewired
```

Then I retried npm start but still got the same error
```
Failed to compile.

./src/Components/MainContent/Irrigation/index.js
Syntax error: Unexpected token (14:0)

  12 | import './Indicator/assets/slider.css';
  13 |
> 14 | @inject('HomeAutomationStores') @observer
     | ^
  15 | class SprinklerZone extends React.Component {
  16 |   handleClick = (e) => {
  17 |     this.props.onClick(e);
```

Just in case, here is my latest package.json - https://gist.github.com/c0debreaker/030beaeaf91195baf4d567021c4bac4e

**Comment by timarney** [comment]
Might be related to https://github.com/timarney/react-app-rewired/issues/49 

I don't gave time to dig into that at the moment but it's on my list.

**Comment by c0debreaker** [comment]
Thank you Tim!

**Comment by c0debreaker** [comment]
Oh, I actually did the patch last night but I was getting more errors. Maybe I was missing a step. Anyways, thanks for helping me.

**Comment by themre** [comment]
i'm using rewired with mobx with no problems:
```
"react-scripts": "^1.0.10"
"react-app-rewire-mobx": "^1.0.3",
"react-app-rewired": "^1.0.8",
"react": "^15.6.1",
"mobx": "3.1.0",
 "mobx-react": "4.1.0",
```
try setting up clean project.

**Comment by c0debreaker** [comment]
@themre, are you using decorators  ?

**Comment by themre** [comment]
yes

**Comment by themre** [comment]
also, I have this: `"babel-plugin-transform-decorators-legacy": "1.3.4",`

**Comment by c0debreaker** [comment]
Cool! I'll try it now.

**Comment by c0debreaker** [comment]
It's working now but not with Preact. I uninstalled `babel-plugin-transform-decorators-legacy` since the @inject decorartor was still not working.

What I had to do is edit `config-overrides.js` and placed the code below
```
const rewireMobX = require('react-app-rewire-mobx');
module.exports = function override(config, env) {
  config = rewireMobX(config, env);
  return config;
}
```
Now what I need to figure out is how to use this -> `react-app-rewire-preact`

**Comment by c0debreaker** [comment]
These are the steps how I was able to get rid of the error I posted on this ticket. Thanks you Tim for suggesting the Mobx rewire. The reason why this didn't work earlier is because I wasn't aware I have to use it in config-overrides.js

1. Install react-app-rewire modules
```
"react-app-rewire-mobx": "^1.0.6",
"react-app-rewired": "^1.0.8",
```

2. Create config-overrides.js
```
const rewireMobX = require('react-app-rewire-mobx');
module.exports = function override(config, env) {
  config = rewireMobX(config, env);
  return config;
}
```

However, I feel like I'm back to my original setup since I was already using decorators via custom-react-scripts and `.env`. My main objective was to try Preact. I'm not sure how I'll add `react-app-rewire-preact` on my existing config-overrides.js.

**Comment by DonnieWest** [comment]
@c0debreaker you should be able to just follow the preact guide but instead of creating a new config-overrides.js you can just import rewirePreact and modify the config again like so

```
const rewireMobX = require('react-app-rewire-mobx');
const rewirePreact = require('react-app-rewire-preact');

module.exports = function override(config, env) {
  config = rewireMobX(config, env);
  config = rewirePreact(config, env);
  return config;
}
```

**Comment by timarney** [comment]
As per @DonnieWest 

You can also use the env param to use Preact only when doing a build
```
module.exports = function override(config, env) {
  
  config = rewireMobX(config,env);

  if (env === "production") {
    console.log("⚡ Production build with Preact");
    config = rewirePreact(config, env);
  }
  return config;
}

```

If you look at https://github.com/timarney/mobx-rewire-test it's all there decorators, mobx, preact

**Comment by c0debreaker** [comment]
I remember doing what DonnieWest wrote last night but it failed. I'll try it again.

I'll check your link Tim. Thank.

**Comment by c0debreaker** [comment]
Failed. Looks like `.env` file is not being read anymore. My components can't be found after I added `config = rewirePreact(config, env);`

```
./src/App.js
Module not found: Can't resolve 'Services/WebSockets' in '/Users/rcamara/repos/AllReact/dashboard/src'
```

**Comment by c0debreaker** [comment]
Using this code, it's working now. I had to npm install --save emotion. It was failing in emotion/babel.

```
const rewireMobX = require('react-app-rewire-mobx');
const rewirePreact = require('react-app-rewire-preact');
const {injectBabelPlugin} = require('react-app-rewired');

/* config-overrides.js */
module.exports = function override(config, env) {
  if (env === "production") {
    console.log("⚡ Production build with Preact");
    config = rewirePreact(config, env);
  }

  config = injectBabelPlugin('emotion/babel',config)
  config = rewireMobX(config,env);
  return config;
}
```

My question now is how do I verify Preact is really getting used by my code?

**Comment by c0debreaker** [comment]
I found the culprit why it fails after I used rewired-app-rewire-preact during `npm run build`

Here is the config after Mobx rewire is called - https://gist.github.com/c0debreaker/71a1043fb3a4b845d317f976bb4768d6

Here is teh config after Preact rewire is called after the Mobx rewire - https://gist.github.com/c0debreaker/11683fa629ee0a0f186bfcc5a1602ee3

The resolve modules got deleted.

Here is the error I'm getting when react-app-rewire-preact is present
```
Failed to compile.

Module not found: Error: Can't resolve 'Services/WebSockets' in '/Users/rcamara/repos/AllReact/dashboard/src'
```

**Comment by timarney** [comment]
Thanks @c0debreaker looks like this repo needs to be re-aligned with the latest CRA there we're some larger changes in the 1.0.0 release which seem to be causing a series of issues.

**Comment by c0debreaker** [comment]
Cool!

**Comment by c0debreaker** [comment]
Decided to make a workaround. My app is now rendering using the bundle (yarn run build) though I haven't played with my app yet. I'm not sure if there are parts that are not working. :)
To get `yarn run build` not to fail, I had to comment out `injectTapEventPlugin`
```
//import injectTapEventPlugin from 'react-tap-event-plugin';
```

Before commenting out injectTapEventPlugin, I was getting this error
```
Module not found: Error: Can't resolve 'react-dom/lib/EventPluginHub' in '/Users/rcamara/repos/AllReact/dashboard/node_modules/react-tap-event-plugin/src'
```

Here is the workaround I did for config-override.js. It's ugly but works.
```
const rewireMobX = require('react-app-rewire-mobx');
const rewirePreact = require('react-app-rewire-preact');
const {injectBabelPlugin} = require('react-app-rewired');

/* config-overrides.js */
module.exports = function override(config, env) {
  config = injectBabelPlugin('emotion/babel',config)
  config = rewireMobX(config, env);
  const resolveObj = config.resolve;
  if (env === "production") {
    config = rewirePreact(config, env);
    config.resolve['modules'] = resolveObj['modules'];
    config.resolve['extensions'] = resolveObj['extensions'];
    config.resolve['plugins'] = resolveObj['plugins'];
    Object.keys(resolveObj.alias).forEach(function(p) {
      config.resolve.alias[p] = resolveObj.alias[p];
    })
    console.log("⚡ Production build with Preact");
  }
  return config;
}
```

Also, I was able to bring down the bundle size ~38k bytes lower.
```
151.99 KB (-38.07 KB)  build/static/js/main.3980ff1d.js
3.18 KB (+199 B)       build/static/css/main.0c920bea.css
```
vs
```
190.06 KB (+38.07 KB)  build/static/js/main.ee95400f.js
2.99 KB (-199 B)       build/static/css/main.c0a5bf64.css
```

**Comment by timarney** [comment]
Closing this issue.  If you run into something else lets open a specific issue for that case.
