### ISSUE TITLE
mobx and mobx-react should be peer dependencies

### ISSUE THREAD

**Issue by mweststrate** [timarney/react-app-rewired#51]
I think :) See also https://github.com/mobxjs/mobx/issues/1082

I saw double mobx entries in people's module tree which doesn't seem to be correct: 

```
├─ mobx-react@4.1.0
├─ mobx@3.1.0
└─ react-app-rewire-mobx@1.0.3
   ├─ mobx-react@4.2.2
   └─ mobx@3.1.16
```

**Comment by timarney** [comment]
@mweststrate is my understanding of Peer Dependencies correct?  

If something is listed under peerDependencies when a user installs that "rewire" those packages will get pulled in as well?

That is to say a user creates an app using CRA - they install react-app-rewired + the mobx rewire (which in turn installs mobx + mobx-react) ... if the user doesn't have those installed.

Also would you recommend  for version number ~1.0 ?

https://nodejs.org/en/blog/npm/peer-dependencies/

**Comment by mweststrate** [comment]
In recent versions peer dependencies will not be installed automatically,
but user will be pointed out that he should install them. So hey has to
install `react-app-rewired mobx mobx-react`. But it is the only correct
thing to do, otherwise he cannot (properly) update mobx versions etc
without you releasing a different version from rewired

Op do 6 jul. 2017 om 15:44 schreef Tim Arney <notifications@github.com>:

**Comment by DonnieWest** [comment]
I've not looked into it yet, but I'd assume this is also true for the other packages? ie preact-rewire

**Comment by timarney** [comment]
@DonnieWest I would say yes the other rewires will need to be updated as well 

> But it is the only correct thing to do, otherwise he cannot (properly) update mobx versions etc without you releasing a different version from rewired

Note: Any packages that are just adding a babel plugin should be able to use 
```
injectBabelPlugin('transform-decorators-legacy', config)
```
The MobX package now makes use of it https://github.com/timarney/react-app-rewired/commit/63d2f60861fd468e018c0fce4920ad8787221417
