### ISSUE TITLE
using my own eslint file?

### ISSUE THREAD

**Issue by moeinrahimi** [timarney/react-app-rewired#517]

**Comment by dawnmist** [comment]
Very simple example, using customize-cra to provide the override method:
```js
const { override, useEslintRc } = require('customize-cra');

module.exports = override(useEslintRc());
```

If you want to use a different filename/config file type for eslint, you can specify the filename as a parameter in the `useEslintRc` function:
```js
const { override, useEslintRc } = require('customize-cra');
const path = require('path');

module.exports = override(useEslintRc(path.resolve(__dirname, '.eslintrc.js')));
```

**Comment by moeinrahimi** [comment]
thank you. would you mind help me to integrate this with my code? I'm using postcss loader.
```
module.exports = config => {
  require('react-app-rewire-postcss')(config, {
     plugins: loader => [
      require('postcss-rtl')()
    ]
  });
  return config;
};
```

**Comment by dawnmist** [comment]
The `override` function can take a list of functions/rewires as input parameters. You can provide custom functions to override that take the config as a parameter and return a modified config, so the following should do what you are after:
```js
const { override, useEslintRc } = require('customize-cra');

module.exports = override(
  useEslintRc(),
  (config) => {
    require('react-app-rewire-postcss')(config, {
      plugins: loader => [
        require('postcss-rtl')()
      ]
    });
    return config;
  }
);
```

**Comment by moeinrahimi** [comment]
one more thing I want to add for people reaching out later. I forgot to install eslint dependency and it leads to override function not work as excepted and also you will get no error corresponding to dependency not being installed.
