### ISSUE TITLE
get public index.html

### ISSUE THREAD

**Issue by reactVsVue** [timarney/react-app-rewired#518]
There are two independent folders in public, and everyone has index.html, but public don't have index.html ,How to configure to point to the corresponding index.html What about it

**Comment by dawnmist** [comment]
I'm sorry, I don't understand what you are asking/what you need to do.

**Comment by reactVsVue** [comment]
![image](https://user-images.githubusercontent.com/54300019/105928774-27389780-6081-11eb-95dc-5aec3f62908c.png)
this is my public，When I run “react-app-rewired build", there is report an error: "public/index.html is necessary"

**Comment by LoveReact86** [comment]
html I want to use mail, my phone is blocked by other hackers, what should I do?

**Comment by timarney** [comment]
Given this isn't a repo bug going to close this.
