### ISSUE TITLE
config-overrides.js does not support async

### ISSUE THREAD

**Issue by ooooevan** [timarney/react-app-rewired#519]
I want to do something async before `module.exports`, but it does not support
related to https://github.com/timarney/react-app-rewired/issues/365

```js
module.exports = function override(config, env) {
  return new Promise((resolve)=>{
    // code...
    resolve(config)
  })
};
```
Failed to compile.
Entry module not found: Error: Cant resolve './src' in 'E:\xxx\xx'

can it supported async ?

version: ^2.1.3

**Comment by patricktran** [comment]
I just submitted a PR to add async/wait support for devServer configuration
https://github.com/timarney/react-app-rewired/pull/543
