### ISSUE TITLE
react-app-rewire-less not working on Windows

### ISSUE THREAD

**Issue by speicus** [timarney/react-app-rewired#53]
When running Node on Windows `rewireLess() ` fails to locate file-loader config because it uses `rule.loader.endsWith('/file-loader/index.js')` to detect it.

Naturally, on Windows the path separators will be backslashes instead of slashes (`'\file-loader\index.js'`), and the check will fail. You could use `path.sep` or just look for `'file-loader'` without the index.js part to fix this.

**Comment by timarney** [comment]
@Hurtak can you comment on this?

**Comment by Hurtak** [comment]
Looks like an easy fix. I will fix it later today or on the weekend.

**Comment by timarney** [comment]
react-app-rewire-less@2.0.4
