### ISSUE TITLE
.eslintcache constantly generated and create-react-app has fix similar promblem

### ISSUE THREAD

**Issue by anitakym** [timarney/react-app-rewired#532]
when use react-app-rewired, .eslintcache constantly generated(hurdle to debug and should be in node_moules and be ignored)

create-react-app has fixed this problem

they Move ESLint cache file into node_modules

see: https://github.com/facebook/create-react-app/pull/9977

**Comment by dawnmist** [comment]
That should flow directly through when you update to the new version of react-scripts.

We actually use the definitions provided by react-scripts as the default config. The fix in the referenced pull request was to modify the webpack config - which means that when using their version of react-scripts you'll get that config modification as part of the default config.

**Comment by anitakym** [comment]
thx
