### ISSUE TITLE
css prefix_exceptions 2.1.8

### ISSUE THREAD

**Issue by bobhuangab** [timarney/react-app-rewired#540]
Creating an optimized production build...
Failed to compile.

./src/index.css
TypeError: Cannot read property 'prefix_exceptions' of undefined
    at Array.map (<anonymous>)

"react-app-rewired": "2.1.8"
node v10.13.0

**Comment by dawnmist** [comment]
That sounds like a code error resulting in the compilation failing, rather than a fault with the build system itself.

I'd need more information - if at all possible access to an example repo demonstrating the issue - in order to trace that through further.

**Comment by bobhuangab** [comment]
solve the problem myself
nvm use 10.14.2 solves the problem
was using 10.13.0
