### ISSUE TITLE
anyone using rewire with webpack 5?

### ISSUE THREAD

**Issue by louischristopherchen** [timarney/react-app-rewired#550]
I just want to start my new project with webpack 5 and rewire.
I have checked the issue for CR4, and they said it's work perfectly.
I want to make sure it's work fine with webpack 5.

**Comment by TimRChen** [comment]
![image](https://user-images.githubusercontent.com/22197215/134801491-cbd38a97-9105-4025-9ba1-181d63886554.png)

**Comment by TimRChen** [comment]
react-app-rewired current no active. I recommand to use craco.  [https://github.com/gsoft-inc/craco/issues/313](url)

**Comment by ImanMh** [comment]
@TimRChen CRACO has the same issue. It does not work with CRA@5

**Comment by dawnmist** [comment]
I believe the original issue was that the version number for react-scripts at the time had the `-next. 37` ending, and hence the version number wasn't being parsed from the version string. Now that react-scripts 5 has actually been released this should not continue to be an issue/react-app-rewired should work.

Please let me know if this fails when the version number does not have a `-xxx` suffix.

**Comment by timarney** [comment]
Closing this - can re-open if it does turn out to be a bug with this repo.
