### ISSUE TITLE
CRA 5

### ISSUE THREAD

**Issue by likunyan** [timarney/react-app-rewired#599]
```shell
yarn add --exact react-scripts@5.0.0
```

Example➜~/WebstormProjects/antic(master✗)» yarn start                                                                                                                                            [11:53:03]
yarn run v1.22.4
$ react-app-rewired start
Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'writeToDisk'. These properties are valid:
   object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, setupMiddlewares?, static?, watchFiles?, webSocketServer? }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by dawnmist** [comment]
What is in your config-overrides file? What webpack modules/plugins are you adding to the CRA configuration?

The error message given is saying that the `devServer` configuration overrides specified contain an invalid option `writeToDisk`. That'll either be something you've added yourself to your config-overrides.js file, or something that is being added as a result of a webpack plugin/module that you're adding. It's a configuration error in your local environment/project, not a bug in react-app-rewired as react-app-rewired doesn't itself add anything to the configuration (it simply enables you to add things to the configuration).

**Comment by likunyan** [comment]
```javascript
/* eslint-disable react-hooks/rules-of-hooks */
const { override, useBabelRc, overrideDevServer } = require("customize-cra");

const devServerConfig = () => (config) => {
  return {
    ...config,
    writeToDisk: true,
  };
};

module.exports = {
  webpack: override(useBabelRc()),
  devServer: overrideDevServer(devServerConfig()),
};
```
