### ISSUE TITLE
webpack plugins/resolve not working with yarn workspace

### ISSUE THREAD

**Issue by tonisives** [timarney/react-app-rewired#618]
There's and issue with react-scripts 5 where some libraries require polyfills.

adding 
```
  config.resolve.fallback = {
    ...config.resolve.fallback,
    stream: require.resolve("stream-browserify"),
    buffer: require.resolve("buffer"),
  }
```
works in a normal CRA, but not in yarn workspaces.

[here](https://github.com/terra-money/terra.js/issues/223) is and issue about the missing polyfills.

### Resolution
Yarn workspaces are supported in [craco](https://github.com/gsoft-inc/craco)

**Comment by dawnmist** [comment]
What happens in a yarn workspaces project?
What are the actual errors received?
Does building complete but the bundle not contain the fallback polyfills, or does the build itself break?
Can you provide an example project showing the problem that I can use to investigate it?
What is your config-overrides that is failing to work?

The link you've provided shows what happens in a normal CRA project, but nothing about a workspaces project or how that acts differently.

**Comment by timarney** [comment]
Closing this as there hasn't been any activity.
