### ISSUE TITLE
react-scripts  upgrade v5.0.1

### ISSUE THREAD

**Issue by iRoySwift** [timarney/react-app-rewired#623]
WARNING in ../lensing/dist/main.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from "data" URL: data:application/json;charset=utf-8;base64,eyJ2ZXJza [...]

https://github.com/facebook/create-react-app/pull/11752

**Comment by dawnmist** [comment]
I'm sorry - I don't understand why you've posted this against react-app-rewired when it appears to be known react-scripts bug (based on your link). We don't have any control over the react-scripts code itself.

**Comment by shugibugi8** [comment]
Hii @iRoySwift , 
I can help you but I didn't understand your question well [,](https://www.dubainv.co.il/%D7%94%D7%A9%D7%A7%D7%A2%D7%95%D7%AA-%D7%A0%D7%93%D7%9C%D7%9F-%D7%91%D7%93%D7%95%D7%91%D7%90%D7%99) can you claery you question ? I've fixed alot of issues on Github I like to face challenges dor fixing them and get more expirence with Github ! can you ellobrate your quez more ?

**Comment by timarney** [comment]
This doesn't seem to be a bug with this repo so I'm going to close it.
