### ISSUE TITLE
set externals for webpack.config.js

### ISSUE THREAD

**Issue by boyboi86** [timarney/react-app-rewired#625]
Apologise if I'm in the wrong place, but it seems that I need to config "externals" in webpack.config.js which I cannot since I'm using react 18.

Is there a way to set "externals" ?

`https://webpack.js.org/configuration/externals/`

**Comment by dawnmist** [comment]
I'm not sure why you need to set externals, but the way you'd do it is with the webpack function.

Something like this if only changing the webpack config:
```js
module.exports = (config) => {
  config.externals = {
    ...config.externals,
    // your changes here
  };
  return config;
};
```
or if you're changing other stuff as well (devServer, jest testing, etc):
```js
module.exports = {
  webpack: (config) => {
    config.externals = {
      ...config.externals,
      // your changes here
    };
    return config;
  },
  jest: (jestConfig) => { }
  devServer: (config) => { }
}
```

**Comment by boyboi86** [comment]
@dawnmist thank you for your reply and advise!
