### ISSUE TITLE
How to use Create-React-App + TypeScript + Ant-Design without Eject

### ISSUE THREAD

**Issue by comerc** [timarney/react-app-rewired#64]
[react-app-rewired](https://github.com/timarney/react-app-rewired) + [awesome-typescript-loader](https://github.com/s-panferov/awesome-typescript-loader) = [babel-plugin-import](https://github.com/ant-design/babel-plugin-import)

[boilerplate project](https://github.com/comerc/cra-ts-antd)

happy coding!

**Comment by rm-rf-etc** [comment]
Time for an updated version. Looks like the current CRA requires customize-cra?
