### ISSUE TITLE
Broken when used with lerna bootstrap --hoist

### ISSUE THREAD

**Issue by andreigec** [timarney/react-app-rewired#65]
Lerna bootstrap --hoist moves all shared node_modules deps of packages into the lerna root directory.

react-app-rewired (RAR) is building the create react app (CRA) webpack path from cwd of the project being built, which node_modules folder won't have either CRA or RAR, so it chokes.

Will need to resolve CRA's webpack config from RAR's node modules location.
build.js -
const webpackConfig = paths.scriptVersionDir + '/config/webpack.config.prod';

**Comment by timarney** [comment]
Adding this as a note on this issue.

https://github.com/lerna/lerna/blob/master/doc/hoist.md

**Comment by aaronjensen** [comment]
This is also broken w/ yarn workspaces (same thing, basically)

**Comment by aaronjensen** [comment]
For now, we're doing this after our yarn install/lerna bootstrap:

```bash
ln -s ../../../node_modules/react-scripts packages/our-app/node_modules/react-scripts
```

**Comment by timarney** [comment]
Noting this 

https://learn.viewsdx.com/how-to-use-yarn-workspaces-with-create-react-app-and-create-react-native-app-expo-to-share-common-ea27bc4bad62


https://github.com/viewsdx/yarn-workspaces-cra-crna

From the Medium post

<img width="790" alt="screen shot 2017-12-02 at 11 42 50 am" src="https://user-images.githubusercontent.com/62242/33517648-f49d41e8-d755-11e7-9f83-bf841b825c5d.png">

**Comment by timarney** [comment]
Also https://github.com/facebookincubator/create-react-app/pull/3435

**Comment by timarney** [comment]
Happy to accept a PR on this ... 

Going to close concluding https://github.com/timarney/react-app-rewired/issues/65#issuecomment-329544472 as a workaround.
