### ISSUE TITLE
provide a way to extend babelTransform for jest

### ISSUE THREAD

**Issue by Guria** [timarney/react-app-rewired#69]
I need a way to extend `babelTransform.js` for jest other then `.babelrc` because I have to make js require statements to create config for babel plugin.

I tried to use `.babelrc.js`, but seems it will be supported only by babel@7 which still in alpha/beta state.

**Comment by timarney** [comment]
Might not help but did you see https://github.com/timarney/react-app-rewired/issues/43

https://github.com/Gregoirevda/react-app-rewired-jest-overwrite/blob/master/package.json

**Comment by Guria** [comment]
Yeah. not helps because I need some code evaluation before.
I am  trying to get [this part](https://github.com/bem/create-bem-react-app/blob/155e5a117bdc45983a878d9c6d6d95cb5a062341/packages/bem-react-scripts/config/jest/babelTransform.js#L18-L25) work.

It would be possible with babel@7 and .babelrc.js support but I wonder if there another way to get around it.

**Comment by Guria** [comment]
@timarney how about to allow jest config override:
```js
// config-overrides.js
module.exports = {
  webpack: (babelConfig, env) => rewireSmthWebpack(babelConfig, env),
  jest: (jestConfig, env) => rewireSmthJest(jestConfig, env),
}
```
we can still support simplified setup when exported only one function for webpack config only.

**Comment by timarney** [comment]
I'm open to this idea.  

1. Biggest thing is not breaking existing stuff.  At a glance you've taken that into consideration.
2. Would you be up for helping maintain this as new versions of react-scripts come out?

**Comment by Guria** [comment]
Yes. I could help with it

**Comment by timarney** [comment]
Great - I'll take a proper look at this next week.
