### ISSUE TITLE
Creating Rewired module instead of just example

### ISSUE THREAD

**Issue by pasviegas** [timarney/react-app-rewired#7]
Hey! What do you think about creating small modules for common configs in this project? Then instead of just having people could just use the modules or look at the source code in case they want anything super fancy.

ex:
```js
import { rewireSass, rewireRelay } from 'react-app-rewired';

module.exports = function override(config, env) {
  return rewireRelay(rewireSass(config, env), env);
};
```

**Comment by timarney** [comment]
Cool idea I'm totally game for that.  Looks like a nice clean way to go from what I see.

Any thoughts @geelen ?

**Comment by timarney** [comment]
@pasviegas if you want to put together a sample module we can at least start there.  I'll have time next week to help get this setup.

**Comment by pasviegas** [comment]
I created some simple default rewires and changed the readme to show how to use it. All very simple, just so we can start.

PR: https://github.com/timarney/react-app-rewired/pull/8
