### ISSUE TITLE
NODE_PATH doesn't work for tests. Cannot find module

### ISSUE THREAD

**Issue by RIP21** [timarney/react-app-rewired#70]
### Is this a bug report?
Yes

### Can you also reproduce the problem with npm 4.x?
No. Same for latest npm 5 and npm 4.

### Environment

1. `node -v`: v7.10.1
2. `npm -v`: 4.2.0
3. `yarn --version`: 0.27.5
4. `npm ls react-scripts`: 1.0.11
5. Operating system: Mac OS 10.12.6

### Steps to Reproduce
1. Set NODE_PATH to `NODE_PATH=./` in `.env`
2. Try to import like: `import Comp from 'src/components/Comp'`
3. `yarn start` runs fine.
4. `yarn test` running tests where their imported modules have such `src/....` imports
P.S. `npm run start / test` give same results as for `yarn`

### Expected Behavior
Tests should run fine and import all modules with no problems at all.

### Actual Behavior
They all fail except those which are never use any dep with`src/....` imports

[Screenshot](http://i.imgur.com/oF4548p.png)

### Working example.
https://github.com/RIP21/no-env-imports-tests
`yarn install && yarn start` - that is it.

**Comment by timarney** [comment]
Will need to take another look at this ran into this prior https://github.com/timarney/react-app-rewired/issues/37

@hassanbazzi 
@svicalifornia

**Comment by RIP21** [comment]
@timarney 
Also, maybe it's more complicated. I tried to solve this problem with overriding aliases in the webpack config, but no result too. In regular `start` mode app is using aliases perfectly, while in `test` totally ignore them.

BTW. Thanks for an amazing job!

**Comment by RIP21** [comment]
@timarney @hassanbazzi @svicalifornia it's not solved yet?
Will be very happy to see this fix.

**Comment by timarney** [comment]
Hoping someone can pick this one up - I'm tight for time at the moment.

**Comment by Guria** [comment]
@RIP21 could you check if #89 fixes the problem?

**Comment by RIP21** [comment]
@Guria hey. I'm on vacation till Monday. Could you check yourself using repro repo that is attache?  Thanks.

**Comment by Guria** [comment]
@RIP21 tried your repo with react-scripts without react-app-rewired and it fails on `npm test` too. So it seems for me as CRA issue.

**Comment by Guria** [comment]
As stated in https://github.com/facebookincubator/create-react-app/issues/2230#issuecomment-302924530 it wouldn't work if NODE_PATH is already set in your system.

So basically you have two options:
* `unset NODE_ENV` before any script ran, to enable value from `.env` 
* `set NODE_ENV=./`  before any script ran, and don't use `.env`

**Comment by Guria** [comment]
Not a rewired issue from my point of view.

**Comment by RIP21** [comment]
I tried both for React scripts and rewired when opening issue. And with rewired it was broken. Maybe it got autofixed somehow with new versions of CRA. Also maybe it's platform dependent. I have Mac. Don't know. Once I return back I will try again. Thanks for your efforts :)

**Comment by RIP21** [comment]
So basically with latest `react-scripts` and `rewired` it's a very funny behavior. First run is green. If you run it again right after successful one, it fails, and after that again, it succeeds and then fails if you run again :D So it's really weird :)
So steps are following:
- Checkout example repo (I updated it to the latest versions of everything)
- run `yarn test`
- If succeeded, click `a` to rerun all tests.
- It will fail.
- Click `a` to rerun again
- It will succeed.
- Click `a` to rerun again
- It will fail

**Comment by Guria** [comment]
Reproduced on my side.
It seems very strange for me since `rewired` provides rewired config and just passes config to jest as command line arguments.
Anyway I have managed to fix it with rewriting the way to override jest config. PR soon.

**Comment by Guria** [comment]
See #92
