### ISSUE TITLE
react-app-rewire-mobx not working with decorator @observable

### ISSUE THREAD

**Issue by topvis** [timarney/react-app-rewired#77]
react-scripts version 1.0.12.

I following the instruction from this link: https://github.com/timarney/react-app-rewired/tree/master/packages/react-app-rewire-mobx

The app will run without decorator. Once I use decorator, I got "Syntax error: C:/.../...js: Unexpected token" at the "@observable".

Did I miss anything? 

I tried installing babel-plugin-transform-decorators-legacy  and then added config = injectBabelPlugin('transform-decorators-legacy',config); in the config-overrides.js and it didn't work either.

Thanks.

**Comment by timarney** [comment]
Please try cloning and running this repo to see if it works for you - https://github.com/timarney/mobx-rewire-test I updated it to the latest  1.0.12 release and the tests are passing.

**Comment by topvis** [comment]
@timarney I tried it and I got the same error.  I also saw this message "babel-loader not found" message after running yarn start (see screenshot below). I do have babel-loader installed. I'm in Windows 10.

![image](https://user-images.githubusercontent.com/5996531/29848405-521334a2-8cee-11e7-90e9-732f32e862fc.png)

**Comment by timarney** [comment]
That error would be coming from this file.

https://github.com/timarney/react-app-rewired/blob/master/packages/react-app-rewired/index.js

Right for time these days but I'll dig into it further as time allows.

**Comment by topvis** [comment]
I removed the slash "/" from this row: `return rule.loader && rule.loader.indexOf("babel-loader/") != -1;` in https://github.com/timarney/react-app-rewired/blob/master/packages/react-app-rewired/index.js
Now it works!
