### ISSUE TITLE
Unable to run scripts/test

### ISSUE THREAD

**Issue by ohmyjersh** [timarney/react-app-rewired#79]
When converting our application to rewired, I hit an issue when converting the tests to also use rewired.  The error is:  "ReferenceError: paths is not defined"

const override = require(paths.projectDir + '/config-overrides');

It looks like it's because it's trying to execute the above line of code before, const paths = require("../config/paths"); has been set.

Bubbling up this assignment fixes the issue, which I have created a pull request here: https://github.com/timarney/react-app-rewired/pull/78

Thanks for this library, it's freaking awesome.

**Comment by timarney** [comment]
Thanks react-app-rewired@1.2.4
