### ISSUE TITLE
babel-loader not found

### ISSUE THREAD

**Issue by mygh021** [timarney/react-app-rewired#83]
$ react-app-rewired start
babel-loader not found

os:windows

fix:   modify react-app-rewired/index.js
return rule.loader && (rule.loader.indexOf("babel-loader") != -1 || rule.loader.indexOf("babel-loader/") != -1);

soluction from https://segmentfault.com/q/1010000010933493

**Comment by Lienviws** [comment]
it seams like the 'react-scripts config' was changed especially about 'babel-loader'.
hopes to fix it

**Comment by timarney** [comment]
Working now?  

version 1.2.5

**Comment by Lienviws** [comment]
It works on my code.
Thanks.
