### ISSUE TITLE
Cannot find module 'babel-preset-react-app'

### ISSUE THREAD

**Issue by FezVrasta** [timarney/react-app-rewired#84]
I get this error when I run the tests:

```
● Test suite failed to run

    Cannot find module 'babel-preset-react-app'

      at Function.Module._resolveFilename (module.js:485:15)
      at Function.resolve (internal/module.js:18:19)
      at Object.<anonymous> (node_modules/react-app-rewired/config/jest/babelTransform.js:21:21)
```

Actually, I can't seem to find `babel-preset-react-app` inside my `node_modules` root folder. I see it's located inside `node_modules/react-scripts/node_modules/babel-preset-react-app`.

Maybe `create-react-app` changed the way the dependency is required?

**Comment by timarney** [comment]
What version of react scripts are you using?

**Comment by FezVrasta** [comment]
Latest

**Comment by RIP21** [comment]
@FezVrasta sounds as stupid suggestion but really try to remove node_modules and install them again.
Or try to use yarn instead of npm.
Also, make sure that your node version is at least 6.
And if anything of that helps, just install this preset putting it in package.json. 
Don't know what can be a reason really. Sometimes there is a packages on npm which include into dependencies some Babel stuff and other development only dependencies by mistake, causing conflicts with react-scripts defaults. Be sure that you don't have any conflicts.

**Comment by FezVrasta** [comment]
I already tried to clean the `node_modules` folder, I tried both yarn and npm and I'm no latest Node.

I think this module should list `babel-preset-react-app` in its `dependencies` since it requires it to work... Or at least, `peerDependencies`

**Comment by timarney** [comment]
Curious can you try that 1.2.6 release and see what happens?

**Comment by FezVrasta** [comment]
I get the same error (only when I run `yarn test`)

**Comment by Guria** [comment]
Try delete node_modules and lock files then install deps again

**Comment by FezVrasta** [comment]
Already tried

**Comment by aaron-harvey** [comment]
@Guria removing the lock file, in addition to node_modules worked for me (yarn v1.0.1).  Thanks.

**Comment by FezVrasta** [comment]
I tried again with a fresh project and it worked, so weird. I guess it's solved

**Comment by tkh44** [comment]
I was able to resolve this by doing what @Guria suggested 

`delete node_modules and lock files then install deps again`

 AND running

`jest --resetModules`

**Comment by congson0710** [comment]
@Guria 's solution works !

**Comment by jcabrerazuniga** [comment]
How can we lock files?

**Comment by dawnmist** [comment]
@jcabrerazuniga Sorry, it means to delete the files that the package managers create (that have `lock` in their name) that keep track of the actual versions of packages installed. If you use yarn, delete `yarn.lock`. If you use npm, delete `package-lock.json`.

**Comment by Pomelo1213** [comment]
thx. it`s work

**Comment by AuthorOfTheSurf** [comment]
I had to update my `.babelrc` from

```
{
  "presets": ["env", "react"]
}
```

to

```
{
  "presets": ["@babel/env", "@babel/react"]
}
```

to resolve this issue.

**Comment by JackWong992** [comment]
> I had to update my `.babelrc` from
> 
> ```
> {
>   "presets": ["env", "react"]
> }
> ```
> to
> 
> ```
> {
>   "presets": ["@babel/env", "@babel/react"]
> }
> ```
> to resolve this issue.

Thank you, I solved my problem with your help.

**Comment by mvaden** [comment]
For me, removing `yarn.lock` did the trick since I was already using NPM.
