### ISSUE TITLE
Cannot read property 'some' of undefined

### ISSUE THREAD

**Issue by MBehtemam** [timarney/react-app-rewired#85]
Hi, i follow [this instruction](https://ant.design/docs/react/use-with-create-react-app) for using `react-app-rewired` and `ant design` and `create-react-app` but after i changed script section of `package.json` and then run the `npm start` i get this error : 
![screenshot from 2017-09-02 09-02-21](https://user-images.githubusercontent.com/1811124/29992956-c960c278-8fbd-11e7-9264-bba72097b3d9.png)

that say cant not read property 'some' of undefined, i check the source and i think it maybe cant load babel plugin so i try to re install the `babel-plugin-import` but the error still happend.

**Comment by timarney** [comment]
What version of react scripts are you running?

**Comment by MBehtemam** [comment]
my react script version in package.json is `"react-scripts": "0.9.5"`

**Comment by RIP21** [comment]
@MBehtemam it's too old. It still uses Webpack 1. Please update to the latest create-react-app (so react scripts) and then it will work fine.

**Comment by MBehtemam** [comment]
after updating the `create-react-app` and` react scripts` everything work well . thanks.
