### ISSUE TITLE
Can i use file.less

### ISSUE THREAD

**Issue by MBehtemam** [timarney/react-app-rewired#86]
Hi, for customizing theme of ant.desing i using `react-app-rewired` and successfully i can edit and add my customization the to the `config-override.js` and it's pretty good except when my customization is huge and has may variables, accourding to the ant documentation i use less files, can i use less files with react-app-rewired insideof directly putting my variables in `config-overrride.js` ?

**Comment by timarney** [comment]
Maybe see https://github.com/timarney/react-app-rewired/issues/64 

You should be able to use the LESS rewire

![less](https://user-images.githubusercontent.com/62242/30004185-89829ac4-9098-11e7-99a6-14f8cafdb7f2.png)

cc:@comerc

**Comment by timarney** [comment]
Does using the LESS rewire help your use case?

@Hurtak might be able to help as well.

**Comment by Hurtak** [comment]
Hi, sorry but I do not understand the question, can you maybe provide some example code?

**Comment by timarney** [comment]
ping @MBehtemam

**Comment by Stoneleee** [comment]
Yeah, I also want to use Sass, and confused how to use react-app-rewired,

**Comment by timarney** [comment]
Closing this if you can provide more details we can open it again.
