### ISSUE TITLE
Can i use svg loader？

### ISSUE THREAD

**Issue by walkinMrwang** [timarney/react-app-rewired#87]
This tool really works well. Do it now support SVG loader?

**Comment by walkinMrwang** [comment]
I want to use it in antd mobile

**Comment by timarney** [comment]
Your given the config object so for the most part you can alter however you need.

**Comment by walkinMrwang** [comment]
The official example is simple. Can you give an example of SVG configuration?Thank you very much

**Comment by lnhrdt** [comment]
@walkinMrwang if you're referring to [SVG React Loader](https://github.com/jhamlet/svg-react-loader) I just wrote a rewire for it:

https://github.com/codebandits/react-app-rewire-svg-react-loader
