### ISSUE TITLE
.env file not loaded in tests

### ISSUE THREAD

**Issue by FezVrasta** [timarney/react-app-rewired#88]
I think this issue affects this project:

https://github.com/facebookincubator/create-react-app/issues/2230

**Comment by Guria** [comment]
@FezVrasta could you check if #89 fixes the problem?

**Comment by Guria** [comment]
See https://github.com/timarney/react-app-rewired/issues/70#issuecomment-327399976

check if NODE_PATH is already set in your environment

**Comment by FezVrasta** [comment]
NODE_PATH isn't defined in my system. I'll test your PR ASAP

**Comment by timarney** [comment]
You can test using 1.2.6

**Comment by FezVrasta** [comment]
It works, thanks!
