### ISSUE TITLE
Environment specific files are not prioritized over .env.

### ISSUE THREAD

**Issue by aaron-harvey** [timarney/react-app-rewired#98]
It seems like variables in `.env.{NODE_ENV}` do not have proper priority over variables defined in `.env`, but `.env.{NODE_ENV}.local` is working correctly (as long as the variable is not defined in `.env`).

**Comment by timarney** [comment]
1. Are you following the guidelines set here https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-custom-environment-variables ?

2. Is the rewired version of your app behaving different than a non-rewired version i.e. it's working with straight CRA but not rewired CRA

**Comment by aaron-harvey** [comment]
1) Yes,
2) Yes, when I react-scripts start .env variables get overridden by .env.development, but react-app-rewired start does not behave the same way.  I tested it with a fresh CRA as well.

I can put together a quick repo if it would help.

**Comment by timarney** [comment]
Yes a repo would be helpful.

**Comment by aaron-harvey** [comment]
https://github.com/aaron-harvey/rewired-env-test

`yarn start`

> FOO: _FOO is set in .env
> BAR: _BAR should be overridden in .env.local
> BAZ: _BAZ should be overridden by .env.development
> QUX: _QUX should be overridden in .env.development.local

`yarn run react-app-rewired start`

> FOO: _FOO is set in .env
> BAR: _BAR is set in .env
> BAZ: _BAZ is set in .env
> QUX: _QUX is set in .env

**Comment by andriijas** [comment]
Also having these issues unfortunately.

**Comment by andriijas** [comment]
Problem is that rewired loaded env files and when react tried to load them, they were already set.

I fixed it in #99
